# FASE 0 — Definición formal del problema

En esta fase no realizaremos gráficos ni modelado.  
El objetivo es dejar documentado, dentro del notebook, el problema de aprendizaje automático antes de comenzar cualquier análisis técnico.

Aquí definiremos:

- cuál es la base principal,
- cuáles son las bases auxiliares,
- cuál es la unidad de análisis,
- cuál es el target exacto,
- qué representa cada fila,
- qué columnas corresponden a identificadores,
- qué columnas pueden ser candidatas a features,
- qué columnas podrían generar leakage,
- y por qué esta fase es obligatoria dentro del flujo del proyecto.

Esta fase es clave porque evita errores metodológicos posteriores, especialmente al momento de construir el dataset de modelado y seleccionar variables.

In [31]:
# =========================
# FASE 0 - Definición formal del problema
# CELDA 1 - Estructura base del proyecto
# =========================

fase_0_definicion = {
    "base_principal": None,
    "bases_auxiliares": [],
    "unidad_de_analisis": None,
    "target_exacto": None,
    "significado_de_cada_fila": None,
    "columnas_identificadoras": [],
    "columnas_candidatas_a_features": [],
    "columnas_con_posible_leakage": [],
    "justificacion_fase_obligatoria": None
}

fase_0_definicion

{'base_principal': None,
 'bases_auxiliares': [],
 'unidad_de_analisis': None,
 'target_exacto': None,
 'significado_de_cada_fila': None,
 'columnas_identificadoras': [],
 'columnas_candidatas_a_features': [],
 'columnas_con_posible_leakage': [],
 'justificacion_fase_obligatoria': None}

## Registro conceptual del problema

En esta celda dejaremos registrada la definición conceptual del proyecto.  
Todavía no estamos leyendo archivos ni validando columnas: primero dejamos por escrito cómo entendemos el problema.

La recomendación es completar esta celda con nombres reales de tablas, columnas y criterios metodológicos del proyecto.

In [32]:
# =========================
# FASE 0 - Definición formal del problema
# CELDA 1 - Estructura base del proyecto
# =========================

fase_0_definicion = {
    "base_principal": "dataset_elpino.csv",
    "bases_auxiliares": [
        "CIE-9.xlsx",
        "CIE-10.xlsx",
        "IR-GRD V3.1 CON PRECIOS FONASA 2016.xlsx",
        "Tablas maestras bases GRD.xlsx"
    ],
    "unidad_de_analisis": "egreso/episodio hospitalario codificado",
    "target_exacto": "GRD",
    "significado_de_cada_fila": (
        "Cada fila representa un caso hospitalario ya codificado, resumido mediante "
        "diagnóstico principal, diagnósticos secundarios, procedimiento principal, "
        "procedimientos secundarios, edad, sexo y el GRD asignado."
    ),
    "columnas_identificadoras": [],
    "columnas_candidatas_a_features": [],
    "columnas_con_posible_leakage": [],
    "justificacion_fase_obligatoria": None
}

fase_0_definicion

{'base_principal': 'dataset_elpino.csv',
 'bases_auxiliares': ['CIE-9.xlsx',
  'CIE-10.xlsx',
  'IR-GRD V3.1 CON PRECIOS FONASA 2016.xlsx',
  'Tablas maestras bases GRD.xlsx'],
 'unidad_de_analisis': 'egreso/episodio hospitalario codificado',
 'target_exacto': 'GRD',
 'significado_de_cada_fila': 'Cada fila representa un caso hospitalario ya codificado, resumido mediante diagnóstico principal, diagnósticos secundarios, procedimiento principal, procedimientos secundarios, edad, sexo y el GRD asignado.',
 'columnas_identificadoras': [],
 'columnas_candidatas_a_features': [],
 'columnas_con_posible_leakage': [],
 'justificacion_fase_obligatoria': None}

## Registro conceptual del problema con nombres reales

En esta celda dejamos registrada la definición conceptual del proyecto usando los nombres reales de la base principal y de las tablas auxiliares encontradas en el dataset del proyecto.

In [33]:
# =========================
# FASE 0 - Definición formal del problema
# CELDA 2 - Completar definición conceptual del problema
# =========================

columnas_diag = [f"Diag {i:02d} Principal (cod+des)" if i == 1 else f"Diag {i:02d} Secundario (cod+des)" for i in range(1, 36)]
columnas_proc = [f"Proced {i:02d} Principal (cod+des)" if i == 1 else f"Proced {i:02d} Secundario (cod+des)" for i in range(1, 31)]

# Corrección explícita para mantener exactamente los nombres reales
columnas_diag[0] = "Diag 01 Principal (cod+des)"
columnas_proc[0] = "Proced 01 Principal (cod+des)"

fase_0_definicion["base_principal"] = "dataset_elpino.csv"

fase_0_definicion["bases_auxiliares"] = [
    "CIE-9.xlsx",
    "CIE-10.xlsx",
    "IR-GRD V3.1 CON PRECIOS FONASA 2016.xlsx",
    "Tablas maestras bases GRD.xlsx"
]

fase_0_definicion["unidad_de_analisis"] = "egreso/episodio hospitalario codificado"

fase_0_definicion["target_exacto"] = "GRD"

fase_0_definicion["significado_de_cada_fila"] = (
    "Cada fila representa un egreso o episodio hospitalario codificado, "
    "con un conjunto de diagnósticos, procedimientos, variables demográficas "
    "y un GRD final asignado."
)

fase_0_definicion["columnas_identificadoras"] = []

fase_0_definicion["columnas_candidatas_a_features"] = (
    columnas_diag
    + columnas_proc
    + ["Edad en años", "Sexo (Desc)"]
)

fase_0_definicion["columnas_con_posible_leakage"] = (
    columnas_proc
    + ["GRD"]
)

fase_0_definicion["justificacion_fase_obligatoria"] = (
    "Esta fase es obligatoria porque antes de entrenar un modelo debemos definir "
    "correctamente la variable objetivo, la unidad de analisis, el significado de cada registro, "
    "las columnas utilizables y las columnas que podrian introducir fuga de informacion. "
    "En este proyecto esto es especialmente importante porque el GRD se relaciona directamente "
    "con la codificacion clinica del caso, por lo que una mala seleccion de variables podria "
    'convertir el problema en una prediccion tautologica en lugar de un problema predictivo real.'
)

fase_0_definicion

{'base_principal': 'dataset_elpino.csv',
 'bases_auxiliares': ['CIE-9.xlsx',
  'CIE-10.xlsx',
  'IR-GRD V3.1 CON PRECIOS FONASA 2016.xlsx',
  'Tablas maestras bases GRD.xlsx'],
 'unidad_de_analisis': 'egreso/episodio hospitalario codificado',
 'target_exacto': 'GRD',
 'significado_de_cada_fila': 'Cada fila representa un egreso o episodio hospitalario codificado, con un conjunto de diagnósticos, procedimientos, variables demográficas y un GRD final asignado.',
 'columnas_identificadoras': [],
 'columnas_candidatas_a_features': ['Diag 01 Principal (cod+des)',
  'Diag 02 Secundario (cod+des)',
  'Diag 03 Secundario (cod+des)',
  'Diag 04 Secundario (cod+des)',
  'Diag 05 Secundario (cod+des)',
  'Diag 06 Secundario (cod+des)',
  'Diag 07 Secundario (cod+des)',
  'Diag 08 Secundario (cod+des)',
  'Diag 09 Secundario (cod+des)',
  'Diag 10 Secundario (cod+des)',
  'Diag 11 Secundario (cod+des)',
  'Diag 12 Secundario (cod+des)',
  'Diag 13 Secundario (cod+des)',
  'Diag 14 Secundario (cod+des)',
  'Diag 15 Secundario (cod+des)',
  'Diag 16 Secundario (cod+des)',
  'Diag 17 Secundario (cod+des)',
  'Diag 18 Secundario (cod+des)',
  'Diag 19 Secundario (cod+des)',
  'Diag 20 Secundario (cod+des)',
  'Diag 21 Secundario (cod+des)',
  'Diag 22 Secundario (cod+des)',
  'Diag 23 Secundario (cod+des)',
  'Diag 24 Secundario (cod+des)',
  'Diag 25 Secundario (cod+des)',
  'Diag 26 Secundario (cod+des)',
  'Diag 27 Secundario (cod+des)',
  'Diag 28 Secundario (cod+des)',
  'Diag 29 Secundario (cod+des)',
  'Diag 30 Secundario (cod+des)',
  'Diag 31 Secundario (cod+des)',
  'Diag 32 Secundario (cod+des)',
  'Diag 33 Secundario (cod+des)',
  'Diag 34 Secundario (cod+des)',
  'Diag 35 Secundario (cod+des)',
  'Proced 01 Principal (cod+des)',
  'Proced 02 Secundario (cod+des)',
  'Proced 03 Secundario (cod+des)',
  'Proced 04 Secundario (cod+des)',
  'Proced 05 Secundario (cod+des)',
  'Proced 06 Secundario (cod+des)',
  'Proced 07 Secundario (cod+des)',
  'Proced 08 Secundario (cod+des)',
  'Proced 09 Secundario (cod+des)',
  'Proced 10 Secundario (cod+des)',
  'Proced 11 Secundario (cod+des)',
  'Proced 12 Secundario (cod+des)',
  'Proced 13 Secundario (cod+des)',
  'Proced 14 Secundario (cod+des)',
  'Proced 15 Secundario (cod+des)',
  'Proced 16 Secundario (cod+des)',
  'Proced 17 Secundario (cod+des)',
  'Proced 18 Secundario (cod+des)',
  'Proced 19 Secundario (cod+des)',
  'Proced 20 Secundario (cod+des)',
  'Proced 21 Secundario (cod+des)',
  'Proced 22 Secundario (cod+des)',
  'Proced 23 Secundario (cod+des)',
  'Proced 24 Secundario (cod+des)',
  'Proced 25 Secundario (cod+des)',
  'Proced 26 Secundario (cod+des)',
  'Proced 27 Secundario (cod+des)',
  'Proced 28 Secundario (cod+des)',
  'Proced 29 Secundario (cod+des)',
  'Proced 30 Secundario (cod+des)',
  'Edad en años',
  'Sexo (Desc)'],
 'columnas_con_posible_leakage': ['Proced 01 Principal (cod+des)',
  'Proced 02 Secundario (cod+des)',
  'Proced 03 Secundario (cod+des)',
  'Proced 04 Secundario (cod+des)',
  'Proced 05 Secundario (cod+des)',
  'Proced 06 Secundario (cod+des)',
  'Proced 07 Secundario (cod+des)',
  'Proced 08 Secundario (cod+des)',
  'Proced 09 Secundario (cod+des)',
  'Proced 10 Secundario (cod+des)',
  'Proced 11 Secundario (cod+des)',
  'Proced 12 Secundario (cod+des)',
  'Proced 13 Secundario (cod+des)',
  'Proced 14 Secundario (cod+des)',
  'Proced 15 Secundario (cod+des)',
  'Proced 16 Secundario (cod+des)',
  'Proced 17 Secundario (cod+des)',
  'Proced 18 Secundario (cod+des)',
  'Proced 19 Secundario (cod+des)',
  'Proced 20 Secundario (cod+des)',
  'Proced 21 Secundario (cod+des)',
  'Proced 22 Secundario (cod+des)',
  'Proced 23 Secundario (cod+des)',
  'Proced 24 Secundario (cod+des)',
  'Proced 25 Secundario (cod+des)',
  'Proced 26 Secundario (cod+des)',
  'Proced 27 Secundario (cod+des)',
  'Proced 28 Secundario (cod+des)',
  'Proced 29 Secundario (cod+des)',
  'Proced 30 Secundario (cod+des)',
  'GRD'],
 'justificacion_fase_obligatoria': 'Esta fase es obligatoria porque antes de entrenar un modelo debemos definir correctamente la variable objetivo, la unidad de analisis, el significado de cada registro, las columnas utilizables y las columnas que podrian introducir fuga de informacion. En este proyecto esto es especialmente importante porque el GRD se relaciona directamente con la codificacion clinica del caso, por lo que una mala seleccion de variables podria convertir el problema en una prediccion tautologica en lugar de un problema predictivo real.'}

## Validación mínima de completitud

En esta celda verificamos que la definición de la fase 0 no quede vacía.  
No valida todavía si los nombres existen en los archivos, pero sí nos ayuda a detectar si olvidamos completar elementos críticos del problema.

In [34]:
# =========================
# FASE 0 - Definición formal del problema
# CELDA 3 - Validación mínima de campos obligatorios
# =========================

def validar_fase_0(definicion: dict):
    errores = []

    for clave, valor in definicion.items():
        if valor is None:
            errores.append(f"El campo '{clave}' está vacío (None).")
        elif isinstance(valor, str) and not valor.strip():
            errores.append(f"El campo '{clave}' está vacío ('').")
        elif isinstance(valor, list) and len(valor) == 0 and clave != "columnas_identificadoras":
            errores.append(f"El campo '{clave}' está vacío ([]).")

    return errores

errores_fase_0 = validar_fase_0(fase_0_definicion)

if len(errores_fase_0) == 0:
    print("✅ Fase 0 completada a nivel conceptual.")
else:
    print("⚠️ Faltan definiciones en la Fase 0:")
    for e in errores_fase_0:
        print("-", e)

✅ Fase 0 completada a nivel conceptual.

## Resumen legible de la definición del problema

En esta celda generamos una salida ordenada y legible para dejar trazabilidad dentro del notebook.  
Esto servirá como referencia antes de comenzar la auditoría técnica de las tablas.

In [35]:
# =========================
# FASE 0 - Definición formal del problema
# CELDA 4 - Resumen estructurado
# =========================

def imprimir_resumen_fase_0(definicion: dict):
    print("=" * 100)
    print("RESUMEN FASE 0 - DEFINICIÓN DEL PROBLEMA")
    print("=" * 100)
    print(f"Base principal: {definicion['base_principal']}")
    print(f"Bases auxiliares: {definicion['bases_auxiliares']}")
    print(f"Unidad de análisis: {definicion['unidad_de_analisis']}")
    print(f"Target exacto: {definicion['target_exacto']}")
    print(f"Significado de cada fila: {definicion['significado_de_cada_fila']}")
    print(f"Columnas identificadoras: {definicion['columnas_identificadoras']}")
    print(f"Número de columnas candidatas a features: {len(definicion['columnas_candidatas_a_features'])}")
    print(f"Número de columnas con posible leakage: {len(definicion['columnas_con_posible_leakage'])}")
    print("\nPrimeras 10 columnas candidatas a features:")
    print(definicion["columnas_candidatas_a_features"][:10])
    print("\nPrimeras 10 columnas con posible leakage:")
    print(definicion["columnas_con_posible_leakage"][:10])
    print("\nJustificación metodológica:")
    print(definicion["justificacion_fase_obligatoria"])
    print("=" * 100)

imprimir_resumen_fase_0(fase_0_definicion)

====================================================================================================
RESUMEN FASE 0 - DEFINICIÓN DEL PROBLEMA
====================================================================================================
Base principal: dataset_elpino.csv
Bases auxiliares: ['CIE-9.xlsx', 'CIE-10.xlsx', 'IR-GRD V3.1 CON PRECIOS FONASA 2016.xlsx', 'Tablas maestras bases GRD.xlsx']
Unidad de análisis: egreso/episodio hospitalario codificado
Target exacto: GRD
Significado de cada fila: Cada fila representa un egreso o episodio hospitalario codificado, con un conjunto de diagnósticos, procedimientos, variables demográficas y un GRD final asignado.
Columnas identificadoras: []
Número de columnas candidatas a features: 67
Número de columnas con posible leakage: 31

Primeras 10 columnas candidatas a features:
['Diag 01 Principal (cod+des)', 'Diag 02 Secundario (cod+des)', 'Diag 03 Secundario (cod+des)', 'Diag 04 Secundario (cod+des)', 'Diag 05 Secundario (cod+des)', 'Diag 06 Secundario (cod+des)', 'Diag 07 Secundario (cod+des)', 'Diag 08 Secundario (cod+des)', 'Diag 09 Secundario (cod+des)', 'Diag 10 Secundario (cod+des)']

Primeras 10 columnas con posible leakage:
['Proced 01 Principal (cod+des)', 'Proced 02 Secundario (cod+des)', 'Proced 03 Secundario (cod+des)', 'Proced 04 Secundario (cod+des)', 'Proced 05 Secundario (cod+des)', 'Proced 06 Secundario (cod+des)', 'Proced 07 Secundario (cod+des)', 'Proced 08 Secundario (cod+des)', 'Proced 09 Secundario (cod+des)', 'Proced 10 Secundario (cod+des)']

Justificación metodológica:
Esta fase es obligatoria porque antes de entrenar un modelo debemos definir correctamente la variable objetivo, la unidad de analisis, el significado de cada registro, las columnas utilizables y las columnas que podrian introducir fuga de informacion. En este proyecto esto es especialmente importante porque el GRD se relaciona directamente con la codificacion clinica del caso, por lo que una mala seleccion de variables podria convertir el problema en una prediccion tautologica en lugar de un problema predictivo real.
====================================================================================================

## Clasificación explícita de columnas con riesgo de leakage

En esta celda no solo listamos columnas riesgosas, sino que además dejamos escrita la razón por la cual podrían generar fuga de información.

Esto es importante porque no toda columna problemática debe eliminarse automáticamente: primero debe justificarse su riesgo metodológico.

In [36]:
# =========================
# FASE 0 - Definición formal del problema
# CELDA 5 - Registro explicativo de posibles columnas con leakage
# =========================

leakage_detallado = {
    "columnas_post_alta_o_de_resultado_final": [
        "GRD"
    ],
    "columnas_que_codifican_directamente_la_resolucion_clinica_del_caso": columnas_proc,
    "columnas_que_pueden_hacer_tautologica_la_prediccion_si_no_se_controlan": (
        columnas_diag + columnas_proc
    ),
    "observaciones": (
        "En este proyecto, el principal riesgo metodologico es que el GRD se asigna a partir "
        "de la codificacion clinica del caso. Por eso, si usamos sin criterio los diagnósticos "
        "y procedimientos completos tal como quedaron registrados al cierre del episodio, "
        "podríamos estar reconstruyendo el GRD en vez de predecirlo de forma prospectiva. "
        "Esto no significa que deban eliminarse automaticamente, sino que su uso debe justificarse "
        "segun el objetivo exacto del modelo."
    )
}

leakage_detallado

{'columnas_post_alta_o_de_resultado_final': ['GRD'],
 'columnas_que_codifican_directamente_la_resolucion_clinica_del_caso': ['Proced 01 Principal (cod+des)',
  'Proced 02 Secundario (cod+des)',
  'Proced 03 Secundario (cod+des)',
  'Proced 04 Secundario (cod+des)',
  'Proced 05 Secundario (cod+des)',
  'Proced 06 Secundario (cod+des)',
  'Proced 07 Secundario (cod+des)',
  'Proced 08 Secundario (cod+des)',
  'Proced 09 Secundario (cod+des)',
  'Proced 10 Secundario (cod+des)',
  'Proced 11 Secundario (cod+des)',
  'Proced 12 Secundario (cod+des)',
  'Proced 13 Secundario (cod+des)',
  'Proced 14 Secundario (cod+des)',
  'Proced 15 Secundario (cod+des)',
  'Proced 16 Secundario (cod+des)',
  'Proced 17 Secundario (cod+des)',
  'Proced 18 Secundario (cod+des)',
  'Proced 19 Secundario (cod+des)',
  'Proced 20 Secundario (cod+des)',
  'Proced 21 Secundario (cod+des)',
  'Proced 22 Secundario (cod+des)',
  'Proced 23 Secundario (cod+des)',
  'Proced 24 Secundario (cod+des)',
  'Proced 25 Secundario (cod+des)',
  'Proced 26 Secundario (cod+des)',
  'Proced 27 Secundario (cod+des)',
  'Proced 28 Secundario (cod+des)',
  'Proced 29 Secundario (cod+des)',
  'Proced 30 Secundario (cod+des)'],
 'columnas_que_pueden_hacer_tautologica_la_prediccion_si_no_se_controlan': ['Diag 01 Principal (cod+des)',
  'Diag 02 Secundario (cod+des)',
  'Diag 03 Secundario (cod+des)',
  'Diag 04 Secundario (cod+des)',
  'Diag 05 Secundario (cod+des)',
  'Diag 06 Secundario (cod+des)',
  'Diag 07 Secundario (cod+des)',
  'Diag 08 Secundario (cod+des)',
  'Diag 09 Secundario (cod+des)',
  'Diag 10 Secundario (cod+des)',
  'Diag 11 Secundario (cod+des)',
  'Diag 12 Secundario (cod+des)',
  'Diag 13 Secundario (cod+des)',
  'Diag 14 Secundario (cod+des)',
  'Diag 15 Secundario (cod+des)',
  'Diag 16 Secundario (cod+des)',
  'Diag 17 Secundario (cod+des)',
  'Diag 18 Secundario (cod+des)',
  'Diag 19 Secundario (cod+des)',
  'Diag 20 Secundario (cod+des)',
  'Diag 21 Secundario (cod+des)',
  'Diag 22 Secundario (cod+des)',
  'Diag 23 Secundario (cod+des)',
  'Diag 24 Secundario (cod+des)',
  'Diag 25 Secundario (cod+des)',
  'Diag 26 Secundario (cod+des)',
  'Diag 27 Secundario (cod+des)',
  'Diag 28 Secundario (cod+des)',
  'Diag 29 Secundario (cod+des)',
  'Diag 30 Secundario (cod+des)',
  'Diag 31 Secundario (cod+des)',
  'Diag 32 Secundario (cod+des)',
  'Diag 33 Secundario (cod+des)',
  'Diag 34 Secundario (cod+des)',
  'Diag 35 Secundario (cod+des)',
  'Proced 01 Principal (cod+des)',
  'Proced 02 Secundario (cod+des)',
  'Proced 03 Secundario (cod+des)',
  'Proced 04 Secundario (cod+des)',
  'Proced 05 Secundario (cod+des)',
  'Proced 06 Secundario (cod+des)',
  'Proced 07 Secundario (cod+des)',
  'Proced 08 Secundario (cod+des)',
  'Proced 09 Secundario (cod+des)',
  'Proced 10 Secundario (cod+des)',
  'Proced 11 Secundario (cod+des)',
  'Proced 12 Secundario (cod+des)',
  'Proced 13 Secundario (cod+des)',
  'Proced 14 Secundario (cod+des)',
  'Proced 15 Secundario (cod+des)',
  'Proced 16 Secundario (cod+des)',
  'Proced 17 Secundario (cod+des)',
  'Proced 18 Secundario (cod+des)',
  'Proced 19 Secundario (cod+des)',
  'Proced 20 Secundario (cod+des)',
  'Proced 21 Secundario (cod+des)',
  'Proced 22 Secundario (cod+des)',
  'Proced 23 Secundario (cod+des)',
  'Proced 24 Secundario (cod+des)',
  'Proced 25 Secundario (cod+des)',
  'Proced 26 Secundario (cod+des)',
  'Proced 27 Secundario (cod+des)',
  'Proced 28 Secundario (cod+des)',
  'Proced 29 Secundario (cod+des)',
  'Proced 30 Secundario (cod+des)'],
 'observaciones': 'En este proyecto, el principal riesgo metodologico es que el GRD se asigna a partir de la codificacion clinica del caso. Por eso, si usamos sin criterio los diagnósticos y procedimientos completos tal como quedaron registrados al cierre del episodio, podríamos estar reconstruyendo el GRD en vez de predecirlo de forma prospectiva. Esto no significa que deban eliminarse automaticamente, sino que su uso debe justificarse segun el objetivo exacto del modelo.'}

## Conclusión operativa de la fase 0

En esta última celda dejamos una conclusión ejecutiva que nos servirá como puente hacia la siguiente fase: inventario técnico y auditoría estructural de las tablas.

In [37]:
# =========================
# FASE 0 - Definición formal del problema
# CELDA 6 - Conclusión operativa
# =========================

conclusion_fase_0 = """
La Fase 0 deja formalmente definido el problema de modelado antes de cualquier análisis exploratorio.
La base principal identificada es dataset_elpino.csv, mientras que las bases auxiliares disponibles son
CIE-9.xlsx, CIE-10.xlsx, IR-GRD V3.1 CON PRECIOS FONASA 2016.xlsx y Tablas maestras bases GRD.xlsx.

Cada fila de la base principal representa un egreso o episodio hospitalario codificado con diagnósticos,
procedimientos, edad, sexo y un GRD final asignado. No se observan identificadores explícitos en la tabla
principal, por lo que la trazabilidad de paciente individual no puede asumirse por ahora.

El target definido es GRD. Sin embargo, debido a que el GRD se relaciona directamente con la codificación
clínica del caso, será indispensable evaluar cuidadosamente el riesgo de leakage antes de construir
el dataset final de modelado.
"""

print(conclusion_fase_0)

La Fase 0 deja formalmente definido el problema de modelado antes de cualquier análisis exploratorio.
La base principal identificada es dataset_elpino.csv, mientras que las bases auxiliares disponibles son
CIE-9.xlsx, CIE-10.xlsx, IR-GRD V3.1 CON PRECIOS FONASA 2016.xlsx y Tablas maestras bases GRD.xlsx.

Cada fila de la base principal representa un egreso o episodio hospitalario codificado con diagnósticos,
procedimientos, edad, sexo y un GRD final asignado. No se observan identificadores explícitos en la tabla
principal, por lo que la trazabilidad de paciente individual no puede asumirse por ahora.

El target definido es GRD. Sin embargo, debido a que el GRD se relaciona directamente con la codificación
clínica del caso, será indispensable evaluar cuidadosamente el riesgo de leakage antes de construir
el dataset final de modelado.

# FASE 1 — Inventario técnico completo de las tablas

En esta fase realizaremos un análisis estructural completo de todas las bases de datos disponibles en el proyecto.

Para cada tabla se construirá una ficha técnica que incluya:

- nombre del archivo
- número de filas y columnas
- columnas disponibles
- tipo de cada columna
- porcentaje de valores nulos por columna
- posibles llaves primarias
- duplicados según llave
- observaciones de calidad

El objetivo es entender la estructura real de los datos antes de integrarlos o modelarlos.

Además, se buscará clasificar cada tabla en:

- tabla principal
- tablas auxiliares
- catálogos
- tablas de enriquecimiento
- tablas no utilizables

Esto permitirá construir un mapa de datos sólido para las siguientes fases.

In [38]:
# =========================
# FASE 1 - Inventario técnico
# CELDA 1 - Imports y configuración
# =========================

import pandas as pd
import numpy as np
from pathlib import Path

# Ruta base (ajústala si estás en Colab)
DATA_PATH = Path(".")

print("Ruta de trabajo:", DATA_PATH.resolve())

Ruta de trabajo: C:\Desarrollo\Proyectos\Activos\clinical-grd-classification

## Función general de perfilado de tablas

En esta celda creamos una función que permitirá analizar cualquier tabla de forma automática.

Esta función calculará:

- dimensiones
- tipos de datos
- nulos
- columnas
- duplicados
- muestra de datos

Esto nos permitirá reutilizar la misma lógica para todas las bases del proyecto.

In [39]:
# =========================
# FASE 1 - Inventario técnico
# CELDA 2 - Función de perfilado
# =========================

def perfil_tabla(df, nombre_tabla):
    
    print("=" * 100)
    print(f"PERFIL DE TABLA: {nombre_tabla}")
    print("=" * 100)
    
    # Dimensiones
    print("\n📌 Dimensiones:")
    print(f"Filas: {df.shape[0]}")
    print(f"Columnas: {df.shape[1]}")
    
    # Columnas
    print("\n📌 Columnas:")
    print(df.columns.tolist())
    
    # Tipos
    print("\n📌 Tipos de datos:")
    print(df.dtypes)
    
    # Nulos
    print("\n📌 Porcentaje de nulos:")
    nulos = df.isnull().mean().sort_values(ascending=False) * 100
    print(nulos[nulos > 0])
    
    # Duplicados totales
    print("\n📌 Filas duplicadas (completas):")
    print(df.duplicated().sum())
    
    # Muestra
    print("\n📌 Muestra de datos:")
    display(df.head(3))
    
    print("=" * 100)

## Análisis de la base principal

Se carga la base principal del proyecto:

- dataset_elpino.csv

Esta es la tabla más importante, ya que contiene los casos a predecir (GRD).

In [40]:
# =========================
# FASE 1 - Inventario técnico
# CELDA 3 - Carga base principal
# =========================

df_main = pd.read_csv("data/raw/dataset_elpino.csv", sep=";")

perfil_tabla(df_main, "dataset_elpino.csv")

====================================================================================================
PERFIL DE TABLA: dataset_elpino.csv
====================================================================================================

📌 Dimensiones:
Filas: 14561
Columnas: 68

📌 Columnas:
['Diag 01 Principal (cod+des)', 'Diag 02 Secundario (cod+des)', 'Diag 03 Secundario (cod+des)', 'Diag 04 Secundario (cod+des)', 'Diag 05 Secundario (cod+des)', 'Diag 06 Secundario (cod+des)', 'Diag 07 Secundario (cod+des)', 'Diag 08 Secundario (cod+des)', 'Diag 09 Secundario (cod+des)', 'Diag 10 Secundario (cod+des)', 'Diag 11 Secundario (cod+des)', 'Diag 12 Secundario (cod+des)', 'Diag 13 Secundario (cod+des)', 'Diag 14 Secundario (cod+des)', 'Diag 15 Secundario (cod+des)', 'Diag 16 Secundario (cod+des)', 'Diag 17 Secundario (cod+des)', 'Diag 18 Secundario (cod+des)', 'Diag 19 Secundario (cod+des)', 'Diag 20 Secundario (cod+des)', 'Diag 21 Secundario (cod+des)', 'Diag 22 Secundario (cod+des)', 'Diag 23 Secundario (cod+des)', 'Diag 24 Secundario (cod+des)', 'Diag 25 Secundario (cod+des)', 'Diag 26 Secundario (cod+des)', 'Diag 27 Secundario (cod+des)', 'Diag 28 Secundario (cod+des)', 'Diag 29 Secundario (cod+des)', 'Diag 30 Secundario (cod+des)', 'Diag 31 Secundario (cod+des)', 'Diag 32 Secundario (cod+des)', 'Diag 33 Secundario (cod+des)', 'Diag 34 Secundario (cod+des)', 'Diag 35 Secundario (cod+des)', 'Proced 01 Principal (cod+des)', 'Proced 02 Secundario (cod+des)', 'Proced 03 Secundario (cod+des)', 'Proced 04 Secundario (cod+des)', 'Proced 05 Secundario (cod+des)', 'Proced 06 Secundario (cod+des)', 'Proced 07 Secundario (cod+des)', 'Proced 08 Secundario (cod+des)', 'Proced 09 Secundario (cod+des)', 'Proced 10 Secundario (cod+des)', 'Proced 11 Secundario (cod+des)', 'Proced 12 Secundario (cod+des)', 'Proced 13 Secundario (cod+des)', 'Proced 14 Secundario (cod+des)', 'Proced 15 Secundario (cod+des)', 'Proced 16 Secundario (cod+des)', 'Proced 17 Secundario (cod+des)', 'Proced 18 Secundario (cod+des)', 'Proced 19 Secundario (cod+des)', 'Proced 20 Secundario (cod+des)', 'Proced 21 Secundario (cod+des)', 'Proced 22 Secundario (cod+des)', 'Proced 23 Secundario (cod+des)', 'Proced 24 Secundario (cod+des)', 'Proced 25 Secundario (cod+des)', 'Proced 26 Secundario (cod+des)', 'Proced 27 Secundario (cod+des)', 'Proced 28 Secundario (cod+des)', 'Proced 29 Secundario (cod+des)', 'Proced 30 Secundario (cod+des)', 'Edad en años', 'Sexo (Desc)', 'GRD']

📌 Tipos de datos:
Diag 01 Principal (cod+des)         str
Diag 02 Secundario (cod+des)        str
Diag 03 Secundario (cod+des)        str
Diag 04 Secundario (cod+des)        str
Diag 05 Secundario (cod+des)        str
                                  ...
Proced 29 Secundario (cod+des)      str
Proced 30 Secundario (cod+des)      str
Edad en años                      int64
Sexo (Desc)                         str
GRD                                 str
Length: 68, dtype: object

📌 Porcentaje de nulos:
Series([], dtype: float64)

📌 Filas duplicadas (completas):
144

📌 Muestra de datos:

,Diag 01 Principal (cod+des),Diag 02 Secundario (cod+des),Diag 03 Secundario (cod+des),Diag 04 Secundario (cod+des),Diag 05 Secundario (cod+des),Diag 06 Secundario (cod+des),Diag 07 Secundario (cod+des),Diag 08 Secundario (cod+des),Diag 09 Secundario (cod+des),Diag 10 Secundario (cod+des),...,Proced 24 Secundario (cod+des),Proced 25 Secundario (cod+des),Proced 26 Secundario (cod+des),Proced 27 Secundario (cod+des),Proced 28 Secundario (cod+des),Proced 29 Secundario (cod+des),Proced 30 Secundario (cod+des),Edad en años,Sexo (Desc),GRD
0,A41.8 - Otras septicemias especificadas,B37.6 - Endocarditis debida a candida (I39.8*),"I39.8 - Endocarditis, válvula no especificada,...",N10 - Nefritis tubulointersticial aguda,B96.1 - Klebsiella pneumoniae [K. pneumoniae] ...,L89.9 - Úlcera de decúbito y area de presión n...,L08.9 - Infección local de la piel y del tejid...,B96.2 - Escherichia coli [E. coli] como causa ...,A41.5 - Sepsis por otros organnismos Gram nega...,J86.9 - Piotórax sin fístula,...,99.84 - AISLAMIENTO,88.72 - ECOCARDIOGRAFIA,90.42 - EXAMEN MICROSCOPICO RESPIRATORIO.CULTIVO,90.52 - EXAMEN MICROSCOPICO SANGRE.CULTIVO,91.39 - EXAMEN MICROSCOPICO URINARIO INFERIOR....,91.33 - EXAMEN MICROSCOPICO URINARIO INFERIOR....,87.03 - TOMOGRAFIA AXIAL COMPUTERIZADA CABEZA,40,Hombre,184103 - MH SEPTICEMIA W/MCC
1,"U07.1 - COVID-19, virus identificado",J12.8 - Neumonía debida a otros virus,R06.0 - Disnea,R05 - Tos,"R50.9 - Fiebre, no especificada",Z29.0 - Aislamiento,Z01.7 - Examen de laboratorio,"J96.00 - Insuficiencia respiratoria aguda, Tip...",J94.2 - Hemotórax,J92.9 - Paquipleuritis sin asbestosis,...,91.62 - EXAMEN MICROSCOPICO PIEL.CULTIVO,90.43 - EXAMEN MICROSCOPICO RESPIRATORIO.CULTI...,91.39 - EXAMEN MICROSCOPICO URINARIO INFERIOR....,90.52 - EXAMEN MICROSCOPICO SANGRE.CULTIVO,91.32 - EXAMEN MICROSCOPICO URINARIO INFERIOR....,96.59 - IRRIGACION HERIDA OTRA,90.99 - EXAMEN MICROSCOPICO DIGESTIVO INFERIOR...,53,Hombre,041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
2,K56.5 - Adherencias [bridas] intestinales con ...,R57.2 - Shock séptico,R57.1 - Choque hipovolémico,J80 - Síndrome de dificultad respiratoria del ...,Y95 - Afección nosocomial,J15.0 - Neumonía debida a Klebsiella pneumoniae,U82.2 - Resistencia a Betalactamasas de amplio...,B95.6 - Staphylococcus aureus como causa de en...,B96.8 - Otros agentes bacterianos especificado...,B37.1 - Candidiasis pulmonar,...,99.84 - AISLAMIENTO,91.73 - EXAMEN MICROSCOPICO HERIDA OPERATORIA....,90.53 - EXAMEN MICROSCOPICO SANGRE.CULTIVO Y S...,99.26 - INYECCION TRANQUILIZANTE,89.39 - OTRAS MEDICIONES Y EXAMENES NO QUIRURG...,89.66 - GASOMETRIA VENA,89.65 - GASOMETRIA ARTERIA,65,Hombre,041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...

====================================================================================================

## Evaluación de posibles llaves primarias

En esta celda intentamos identificar si existe alguna columna que pueda funcionar como llave única.

Esto es crítico porque:
- define si podemos hacer joins confiables
- permite detectar duplicados estructurales

In [41]:
# =========================
# FASE 1 - Inventario técnico
# CELDA 4 - Evaluación de llaves
# =========================

def evaluar_unicidad(df):
    resultados = {}
    
    for col in df.columns:
        resultados[col] = df[col].nunique() == len(df)
    
    return pd.Series(resultados)

unicidad = evaluar_unicidad(df_main)

print("Columnas que podrían ser llave primaria:")
print(unicidad[unicidad == True])

Columnas que podrían ser llave primaria:
Series([], dtype: bool)

## Duplicados por posibles llaves

Si identificamos columnas candidatas a llave, aquí verificamos duplicados.

In [42]:
# =========================
# FASE 1 - Inventario técnico
# CELDA 5 - Duplicados por columna
# =========================

duplicados_por_columna = {}

for col in df_main.columns:
    duplicados_por_columna[col] = df_main.duplicated(subset=[col]).sum()

pd.Series(duplicados_por_columna).sort_values(ascending=False).head(10)

Sexo (Desc)                     14559
Diag 35 Secundario (cod+des)    14535
Diag 34 Secundario (cod+des)    14526
Diag 33 Secundario (cod+des)    14522
Diag 32 Secundario (cod+des)    14516
Diag 30 Secundario (cod+des)    14506
Diag 31 Secundario (cod+des)    14504
Diag 29 Secundario (cod+des)    14493
Diag 28 Secundario (cod+des)    14479
Diag 27 Secundario (cod+des)    14473
dtype: int64

## Análisis de bases auxiliares

Ahora se analizan las tablas auxiliares:

- CIE-9.xlsx
- CIE-10.xlsx
- IR-GRD V3.1 CON PRECIOS FONASA 2016.xlsx
- Tablas maestras bases GRD.xlsx

Estas tablas son clave para enriquecer la información clínica.

In [43]:
# =========================
# FASE 1 - Inventario técnico
# CELDA 6 - Carga auxiliares
# =========================

try:
    cie9 = pd.read_excel("data/raw/CIE-9.xlsx")
    perfil_tabla(cie9, "CIE-9.xlsx")
except:
    print("⚠️ No se pudo cargar CIE-9.xlsx")

try:
    cie10 = pd.read_excel("data/raw/CIE-10.xlsx")
    perfil_tabla(cie10, "CIE-10.xlsx")
except:
    print("⚠️ No se pudo cargar CIE-10.xlsx")

try:
    grd = pd.read_excel("data/raw/IR-GRD V3.1 CON PRECIOS FONASA 2016.xlsx")
    perfil_tabla(grd, "IR-GRD.xlsx")
except:
    print("⚠️ No se pudo cargar IR-GRD")

try:
    tablas_maestras = pd.read_excel("data/raw/Tablas maestras bases GRD.xlsx")
    perfil_tabla(tablas_maestras, "Tablas maestras")
except:
    print("⚠️ No se pudo cargar tablas maestras")

====================================================================================================
PERFIL DE TABLA: CIE-9.xlsx
====================================================================================================

📌 Dimensiones:
Filas: 4646
Columnas: 5

📌 Columnas:
['Código', 'Descripción', 'Categoría', 'Sección', 'Capítulo']

📌 Tipos de datos:
Código         float64
Descripción        str
Categoría          str
Sección            str
Capítulo           str
dtype: object

📌 Porcentaje de nulos:
Series([], dtype: float64)

📌 Filas duplicadas (completas):
1

📌 Muestra de datos:

,Código,Descripción,Categoría,Sección,Capítulo
0,0.00,PROCEDIMIENTO E INTERVENCION NCOC,"00 PROCEDIMIENTOS E INTERVENCIONES, NO CLASIFI...",00. (00 00) PROCEDIMIENTOS E INTERVENCIONES NO...,00. (00 00) PROCEDIMIENTOS E INTERVENCIONES NO...
1,0.00,ULTRASONIDO TERAPEUTICO,"00 PROCEDIMIENTOS E INTERVENCIONES, NO CLASIFI...",00. (00 00) PROCEDIMIENTOS E INTERVENCIONES NO...,00. (00 00) PROCEDIMIENTOS E INTERVENCIONES NO...
2,0.01,ULTRASONIDO TERAPEUTICO.VASO CABEZA Y CUELLO,"00 PROCEDIMIENTOS E INTERVENCIONES, NO CLASIFI...",00. (00 00) PROCEDIMIENTOS E INTERVENCIONES NO...,00. (00 00) PROCEDIMIENTOS E INTERVENCIONES NO...

====================================================================================================
====================================================================================================
PERFIL DE TABLA: CIE-10.xlsx
====================================================================================================

📌 Dimensiones:
Filas: 39873
Columnas: 6

📌 Columnas:
['Versión', 'Código', 'Descripción', 'Categoría', 'Sección', 'Capítulo']

📌 Tipos de datos:
Versión        str
Código         str
Descripción    str
Categoría      str
Sección        str
Capítulo       str
dtype: object

📌 Porcentaje de nulos:
Series([], dtype: float64)

📌 Filas duplicadas (completas):
0

📌 Muestra de datos:

,Versión,Código,Descripción,Categoría,Sección,Capítulo
0,CIE-v2013,A00,Cólera,A00 CÓLERA,A00-A09 ENFERMEDADES INFECCIOSAS INTESTINALES,Cap.01 CIERTAS ENFERMEDADES INFECCIOSAS Y PAR...
1,CIE-v2013,A00.0,"Cólera debido a Vibrio cholerae O1, biotipo ch...",A00 CÓLERA,A00-A09 ENFERMEDADES INFECCIOSAS INTESTINALES,Cap.01 CIERTAS ENFERMEDADES INFECCIOSAS Y PAR...
2,CIE-v2013,A00.1,"Cólera debido a Vibrio cholerae O1, biotipo El...",A00 CÓLERA,A00-A09 ENFERMEDADES INFECCIOSAS INTESTINALES,Cap.01 CIERTAS ENFERMEDADES INFECCIOSAS Y PAR...

====================================================================================================
====================================================================================================
PERFIL DE TABLA: IR-GRD.xlsx
====================================================================================================

📌 Dimensiones:
Filas: 1095
Columnas: 8

📌 Columnas:
['IR-GRD CÓDIGO', 'NOMBRE DEL GRUPO GRD', 'Peso v31', 'CDM_COD', 'CATEGORÍA DIAGNÓSTICA MAYOR CDM', 'TIPO_COD', 'TIPO GRD', 'Precio FONASA 2016']

📌 Tipos de datos:
IR-GRD CÓDIGO                        int64
NOMBRE DEL GRUPO GRD                   str
Peso v31                           float64
CDM_COD                              int64
CATEGORÍA DIAGNÓSTICA MAYOR CDM        str
TIPO_COD                               str
TIPO GRD                               str
Precio FONASA 2016                 float64
dtype: object

📌 Porcentaje de nulos:
Precio FONASA 2016    1.278539
dtype: float64

📌 Filas duplicadas (completas):
0

📌 Muestra de datos:

,IR-GRD CÓDIGO,NOMBRE DEL GRUPO GRD,Peso v31,CDM_COD,CATEGORÍA DIAGNÓSTICA MAYOR CDM,TIPO_COD,TIPO GRD,Precio FONASA 2016
0,11011,PH PROCEDIMIENTOS VASCULARES INTRACRANEALES,2.4330,1,SISTEMA NERVIOSO,PH,PROCEDIMIENTO HOSPITALIZADO,3.936157e+06
1,11012,PH PROCEDIMIENTOS VASCULARES INTRACRANEALES W/CC,3.6066,1,SISTEMA NERVIOSO,PH,PROCEDIMIENTO HOSPITALIZADO,5.834832e+06
2,11013,PH PROCEDIMIENTOS VASCULARES INTRACRANEALES W/MCC,5.8425,1,SISTEMA NERVIOSO,PH,PROCEDIMIENTO HOSPITALIZADO,9.452117e+06

====================================================================================================
====================================================================================================
PERFIL DE TABLA: Tablas maestras
====================================================================================================

📌 Dimensiones:
Filas: 377
Columnas: 2

📌 Columnas:
['HOSPITALES', 'Unnamed: 1']

📌 Tipos de datos:
HOSPITALES    int64
Unnamed: 1      str
dtype: object

📌 Porcentaje de nulos:
Series([], dtype: float64)

📌 Filas duplicadas (completas):
0

📌 Muestra de datos:

   HOSPITALES                              Unnamed: 1
0      101100  Hospital Dr. Juan Noé Crevanni (Arica)
1      101203                            Clínica Hebe
2      101212                     Clínica San Agustín

====================================================================================================

## Clasificación de tablas

En esta celda construimos un resumen conceptual del rol de cada tabla dentro del proyecto.

In [44]:
# =========================
# FASE 1 - Inventario técnico
# CELDA 7 - Clasificación de tablas
# =========================

clasificacion_tablas = {
    "dataset_elpino.csv": "Tabla principal (casos clínicos con GRD)",
    "CIE-9.xlsx": "Catálogo de procedimientos clínicos",
    "CIE-10.xlsx": "Catálogo de diagnósticos clínicos",
    "IR-GRD V3.1 CON PRECIOS FONASA 2016.xlsx": "Tabla de enriquecimiento (GRD + atributos)",
    "Tablas maestras bases GRD.xlsx": "Tablas maestras auxiliares"
}

clasificacion_tablas

{'dataset_elpino.csv': 'Tabla principal (casos clínicos con GRD)',
 'CIE-9.xlsx': 'Catálogo de procedimientos clínicos',
 'CIE-10.xlsx': 'Catálogo de diagnósticos clínicos',
 'IR-GRD V3.1 CON PRECIOS FONASA 2016.xlsx': 'Tabla de enriquecimiento (GRD + atributos)',
 'Tablas maestras bases GRD.xlsx': 'Tablas maestras auxiliares'}

## Conclusión de la fase 1

Aquí dejamos una síntesis clara del mapa de datos identificado.

In [45]:
# =========================
# FASE 1 - Inventario técnico
# CELDA 8 - Conclusión
# =========================

conclusion_fase_1 = """
Se identificó que dataset_elpino.csv es la tabla principal del proyecto,
conteniendo los casos clínicos con su respectivo GRD.

Las tablas CIE-9 y CIE-10 corresponden a catálogos clínicos,
mientras que IR-GRD y tablas maestras corresponden a tablas de enriquecimiento.

No se identificaron llaves primarias evidentes en la tabla principal,
lo que implica que cada fila debe tratarse como un episodio independiente.

Este análisis permite avanzar hacia la fase de auditoría de calidad
y preparación de datos para integración.
"""

print(conclusion_fase_1)

Se identificó que dataset_elpino.csv es la tabla principal del proyecto,
conteniendo los casos clínicos con su respectivo GRD.

Las tablas CIE-9 y CIE-10 corresponden a catálogos clínicos,
mientras que IR-GRD y tablas maestras corresponden a tablas de enriquecimiento.

No se identificaron llaves primarias evidentes en la tabla principal,
lo que implica que cada fila debe tratarse como un episodio independiente.

Este análisis permite avanzar hacia la fase de auditoría de calidad
y preparación de datos para integración.

# FASE 2 — Auditoría estructural de la base principal

En esta fase se realiza un análisis exploratorio inicial (EDA) de la base principal.

El objetivo es:

- comprender la estructura real del dataset
- evaluar calidad de datos
- detectar problemas estructurales
- clasificar correctamente las variables

Esto es obligatorio antes de cualquier modelamiento, ya que permite evitar errores críticos como leakage, ruido o mala definición del target.

## 2.1 Vista inicial del dataset

Se analiza:

- dimensiones
- primeras filas
- últimas filas
- muestra aleatoria
- tipos de datos
- uso de memoria

Esto permite tener una visión general del dataset antes de profundizar.

In [46]:
# =========================
# FASE 2 - CELDA 1
# Vista inicial
# =========================

print("Shape:", df_main.shape)

display(df_main.head(3))
display(df_main.tail(3))
display(df_main.sample(3, random_state=42))

Shape: (14561, 68)

,Diag 01 Principal (cod+des),Diag 02 Secundario (cod+des),Diag 03 Secundario (cod+des),Diag 04 Secundario (cod+des),Diag 05 Secundario (cod+des),Diag 06 Secundario (cod+des),Diag 07 Secundario (cod+des),Diag 08 Secundario (cod+des),Diag 09 Secundario (cod+des),Diag 10 Secundario (cod+des),...,Proced 24 Secundario (cod+des),Proced 25 Secundario (cod+des),Proced 26 Secundario (cod+des),Proced 27 Secundario (cod+des),Proced 28 Secundario (cod+des),Proced 29 Secundario (cod+des),Proced 30 Secundario (cod+des),Edad en años,Sexo (Desc),GRD
0,A41.8 - Otras septicemias especificadas,B37.6 - Endocarditis debida a candida (I39.8*),"I39.8 - Endocarditis, válvula no especificada,...",N10 - Nefritis tubulointersticial aguda,B96.1 - Klebsiella pneumoniae [K. pneumoniae] ...,L89.9 - Úlcera de decúbito y area de presión n...,L08.9 - Infección local de la piel y del tejid...,B96.2 - Escherichia coli [E. coli] como causa ...,A41.5 - Sepsis por otros organnismos Gram nega...,J86.9 - Piotórax sin fístula,...,99.84 - AISLAMIENTO,88.72 - ECOCARDIOGRAFIA,90.42 - EXAMEN MICROSCOPICO RESPIRATORIO.CULTIVO,90.52 - EXAMEN MICROSCOPICO SANGRE.CULTIVO,91.39 - EXAMEN MICROSCOPICO URINARIO INFERIOR....,91.33 - EXAMEN MICROSCOPICO URINARIO INFERIOR....,87.03 - TOMOGRAFIA AXIAL COMPUTERIZADA CABEZA,40,Hombre,184103 - MH SEPTICEMIA W/MCC
1,"U07.1 - COVID-19, virus identificado",J12.8 - Neumonía debida a otros virus,R06.0 - Disnea,R05 - Tos,"R50.9 - Fiebre, no especificada",Z29.0 - Aislamiento,Z01.7 - Examen de laboratorio,"J96.00 - Insuficiencia respiratoria aguda, Tip...",J94.2 - Hemotórax,J92.9 - Paquipleuritis sin asbestosis,...,91.62 - EXAMEN MICROSCOPICO PIEL.CULTIVO,90.43 - EXAMEN MICROSCOPICO RESPIRATORIO.CULTI...,91.39 - EXAMEN MICROSCOPICO URINARIO INFERIOR....,90.52 - EXAMEN MICROSCOPICO SANGRE.CULTIVO,91.32 - EXAMEN MICROSCOPICO URINARIO INFERIOR....,96.59 - IRRIGACION HERIDA OTRA,90.99 - EXAMEN MICROSCOPICO DIGESTIVO INFERIOR...,53,Hombre,041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
2,K56.5 - Adherencias [bridas] intestinales con ...,R57.2 - Shock séptico,R57.1 - Choque hipovolémico,J80 - Síndrome de dificultad respiratoria del ...,Y95 - Afección nosocomial,J15.0 - Neumonía debida a Klebsiella pneumoniae,U82.2 - Resistencia a Betalactamasas de amplio...,B95.6 - Staphylococcus aureus como causa de en...,B96.8 - Otros agentes bacterianos especificado...,B37.1 - Candidiasis pulmonar,...,99.84 - AISLAMIENTO,91.73 - EXAMEN MICROSCOPICO HERIDA OPERATORIA....,90.53 - EXAMEN MICROSCOPICO SANGRE.CULTIVO Y S...,99.26 - INYECCION TRANQUILIZANTE,89.39 - OTRAS MEDICIONES Y EXAMENES NO QUIRURG...,89.66 - GASOMETRIA VENA,89.65 - GASOMETRIA ARTERIA,65,Hombre,041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...

,Diag 01 Principal (cod+des),Diag 02 Secundario (cod+des),Diag 03 Secundario (cod+des),Diag 04 Secundario (cod+des),Diag 05 Secundario (cod+des),Diag 06 Secundario (cod+des),Diag 07 Secundario (cod+des),Diag 08 Secundario (cod+des),Diag 09 Secundario (cod+des),Diag 10 Secundario (cod+des),...,Proced 24 Secundario (cod+des),Proced 25 Secundario (cod+des),Proced 26 Secundario (cod+des),Proced 27 Secundario (cod+des),Proced 28 Secundario (cod+des),Proced 29 Secundario (cod+des),Proced 30 Secundario (cod+des),Edad en años,Sexo (Desc),GRD
14558,K92.1 - Melena,I10 - Hipertensión esencial (primaria),E11.9 - Diabetes mellitus tipo 2 sin complicac...,"I50.9 - Insuficiencia cardíaca, no especificada","K25.9 - Úlcera gástrica, no especificada como ...","M16.9 - Coxartrosis, no especificada",G47.3 - Apnea del sueño,Z99.8 - Dependencia de otras máquinas y dispos...,-,-,...,-,-,-,-,-,-,-,58,Hombre,064182 - MH OTROS DIAGNÓSTICOS SOBRE APARATO D...
14559,E78.1 - Hipergliceridemia pura,I10 - Hipertensión esencial (primaria),Z92.2 - Historia personal de uso (presente) de...,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,47,Hombre,104121 - MH ERRORES CONGÉNITOS DE METABOLISMO
14560,"S06.51 - Hemorragia subdural traumática, con h...","S06.21 - Traumatismo cerebral difuso, con heri...","W18.09 - Otras caídas en el mismo nivel, vivie...",J69.0 - Neumonitis debida a aspiración de alim...,D29.1 - Tumor benigno de la próstata,Z59.0 - Problemas relacionados con la falta de...,Z02.7 - Extensión de certificado médico,-,-,-,...,89.66 - GASOMETRIA VENA,89.66 - GASOMETRIA VENA,90.39 - EXAMEN MICROSCOPICO ORL.OTRO,90.42 - EXAMEN MICROSCOPICO RESPIRATORIO.CULTIVO,90.52 - EXAMEN MICROSCOPICO SANGRE.CULTIVO,90.59 - EXAMEN MICROSCOPICO SANGRE.OTRO,90.59 - EXAMEN MICROSCOPICO SANGRE.OTRO,73,Hombre,041203 - PH PROCEDIMIENTOS NO COMPLEJOS SOBRE ...

,Diag 01 Principal (cod+des),Diag 02 Secundario (cod+des),Diag 03 Secundario (cod+des),Diag 04 Secundario (cod+des),Diag 05 Secundario (cod+des),Diag 06 Secundario (cod+des),Diag 07 Secundario (cod+des),Diag 08 Secundario (cod+des),Diag 09 Secundario (cod+des),Diag 10 Secundario (cod+des),...,Proced 24 Secundario (cod+des),Proced 25 Secundario (cod+des),Proced 26 Secundario (cod+des),Proced 27 Secundario (cod+des),Proced 28 Secundario (cod+des),Proced 29 Secundario (cod+des),Proced 30 Secundario (cod+des),Edad en años,Sexo (Desc),GRD
6551,P70.4 - Otras hipoglicemias neonatales,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,0,Hombre,"158171 - MH NEONATO, PESO AL NACER >2499 GR SI..."
2417,K43.2 - Hernia incisional sin obstruccion ni g...,I10 - Hipertensión esencial (primaria),E11.9 - Diabetes mellitus tipo 2 sin complicac...,Z92.2 - Historia personal de uso (presente) de...,-,-,-,-,-,-,...,-,-,-,-,-,-,-,74,Hombre,061121 - PH PROCEDIMIENTOS SOBRE HERNIA EXCEPT...
3467,"K35.8 - Apendicitis aguda, otra y no especificada","E66.9 - Obesidad, no especificada",-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,20,Mujer,061131 - PH PROCEDIMIENTOS SOBRE APÉNDICE

In [47]:
# =========================
# FASE 2 - CELDA 2
# Tipos de datos
# =========================

df_main.dtypes.value_counts()

str      67
int64     1
Name: count, dtype: int64

In [48]:
# =========================
# FASE 2 - CELDA 3
# Uso de memoria
# =========================

memoria = df_main.memory_usage(deep=True).sum() / (1024**2)
print(f"Memoria aproximada: {memoria:.2f} MB")

Memoria aproximada: 64.22 MB

In [49]:
# =========================
# FASE 2 - CELDA 4
# Columnas sospechosas
# =========================

cols = pd.Series(df_main.columns)

cols[cols.duplicated()]

Series([], dtype: str)

## 2.2 Calidad básica del dataset

Se evaluará:

- nulos por columna
- nulos por fila
- porcentaje de completitud
- duplicados exactos
- valores fuera de rango o inconsistentes

In [50]:
# =========================
# FASE 2 - CELDA 5
# Nulos por columna
# =========================

nulos_col = df_main.isnull().mean().sort_values(ascending=False) * 100

nulos_col.head(15)

Diag 01 Principal (cod+des)     0.0
Diag 02 Secundario (cod+des)    0.0
Diag 03 Secundario (cod+des)    0.0
Diag 04 Secundario (cod+des)    0.0
Diag 05 Secundario (cod+des)    0.0
Diag 06 Secundario (cod+des)    0.0
Diag 07 Secundario (cod+des)    0.0
Diag 08 Secundario (cod+des)    0.0
Diag 09 Secundario (cod+des)    0.0
Diag 10 Secundario (cod+des)    0.0
Diag 11 Secundario (cod+des)    0.0
Diag 12 Secundario (cod+des)    0.0
Diag 13 Secundario (cod+des)    0.0
Diag 14 Secundario (cod+des)    0.0
Diag 15 Secundario (cod+des)    0.0
dtype: float64

In [51]:
# =========================
# FASE 2 - CELDA 6
# Nulos por fila
# =========================

nulos_fila = df_main.isnull().sum(axis=1)

print("Promedio de nulos por fila:", nulos_fila.mean())
print("Máximo de nulos en una fila:", nulos_fila.max())

Promedio de nulos por fila: 0.0
Máximo de nulos en una fila: 0

In [52]:
# =========================
# FASE 2 - CELDA 7
# Completitud
# =========================

completitud = 100 - nulos_col

completitud.describe()

count     68.0
mean     100.0
std        0.0
min      100.0
25%      100.0
50%      100.0
75%      100.0
max      100.0
dtype: float64

In [53]:
# =========================
# FASE 2 - CELDA 8
# Duplicados exactos
# =========================

df_main.duplicated().sum()

np.int64(144)

In [54]:
# =========================
# FASE 2 - CELDA 9
# Validación básica de valores
# =========================

print("Edad - mínimo:", df_main["Edad en años"].min())
print("Edad - máximo:", df_main["Edad en años"].max())

print("\nValores únicos en Sexo:")
print(df_main["Sexo (Desc)"].unique())

Edad - mínimo: 0
Edad - máximo: 121

Valores únicos en Sexo:
<StringArray>
['Hombre', 'Mujer']
Length: 2, dtype: str

## 2.3 Clasificación de variables

Se clasifican las variables en:

- identificadores
- target
- numéricas
- categóricas
- códigos clínicos

Esto permitirá preparar correctamente el dataset para modelamiento.

In [55]:
# =========================
# FASE 2 - CELDA 10
# Clasificación de variables
# =========================

numericas = df_main.select_dtypes(include=["int64", "float64"]).columns.tolist()
categoricas = df_main.select_dtypes(include=["object"]).columns.tolist()

print("Numéricas:", len(numericas))
print("Categóricas:", len(categoricas))

Numéricas: 1
Categóricas: 67

C:\Users\panch\AppData\Local\Temp\ipykernel_9248\3981831969.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categoricas = df_main.select_dtypes(include=["object"]).columns.tolist()

In [56]:
# =========================
# FASE 2 - CELDA 11
# Clasificación manual
# =========================

target = ["GRD"]

demograficas = [
    "Edad en años",
    "Sexo (Desc)"
]

diagnosticos = [col for col in df_main.columns if "Diag" in col]
procedimientos = [col for col in df_main.columns if "Proced" in col]

print("Diagnósticos:", len(diagnosticos))
print("Procedimientos:", len(procedimientos))

Diagnósticos: 35
Procedimientos: 30

In [57]:
# =========================
# FASE 2 - CELDA 12
# Resumen final
# =========================

resumen_variables = {
    "target": target,
    "demograficas": demograficas,
    "diagnosticos": len(diagnosticos),
    "procedimientos": len(procedimientos),
    "numericas": len(numericas),
    "categoricas": len(categoricas)
}

resumen_variables

{'target': ['GRD'],
 'demograficas': ['Edad en años', 'Sexo (Desc)'],
 'diagnosticos': 35,
 'procedimientos': 30,
 'numericas': 1,
 'categoricas': 67}

# FASE 3 — EDA profundo del target (GRD)

En esta fase se analizará en profundidad la variable objetivo del proyecto: **GRD**.

El objetivo es responder, con evidencia, preguntas clave como:

- cuál es el formato real del target,
- cuántas clases distintas existen,
- cuáles son las clases más frecuentes,
- cuántas clases son raras,
- si hay desbalance severo,
- y si el problema parece viable como clasificación multiclase directa.

Este análisis es obligatorio antes de entrenar, porque en problemas de clasificación no basta con accuracy:
debemos entender la distribución del target para decidir correctamente las métricas, la estrategia de modelado
y el tratamiento de clases raras.

In [58]:
# =========================
# FASE 3 - EDA profundo del target
# CELDA 1 - Copia de trabajo y revisión inicial
# =========================

df_target = df_main.copy()

print("Shape de trabajo:", df_target.shape)
print("Nombre del target:", "GRD")

Shape de trabajo: (14561, 68)
Nombre del target: GRD

## 3.1 Formato real del target

En esta celda revisamos:

- tipo de dato del target,
- ejemplos reales de valores,
- longitud de los textos,
- consistencia general del formato.

Esto nos permitirá identificar si el GRD está limpio o si existen valores mal escritos, vacíos o inconsistentes.

In [59]:
# =========================
# FASE 3 - EDA profundo del target
# CELDA 2 - Inspección básica del target
# =========================

target_col = "GRD"

print("Tipo de dato del target:", df_target[target_col].dtype)
print("\nPrimeros 10 valores del target:")
display(df_target[target_col].head(10))

print("\nMuestra aleatoria de 10 valores del target:")
display(df_target[target_col].sample(10, random_state=42).reset_index(drop=True))

Tipo de dato del target: str

Primeros 10 valores del target:

0                         184103 - MH SEPTICEMIA W/MCC
1    041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
2    041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
3    041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...
4    041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...
5    041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
6    041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
7    041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
8    041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...
9    041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...
Name: GRD, dtype: str

Muestra aleatoria de 10 valores del target:

0    158171 - MH NEONATO, PESO AL NACER >2499 GR SI...
1    061121 - PH PROCEDIMIENTOS SOBRE HERNIA EXCEPT...
2            061131 - PH PROCEDIMIENTOS SOBRE APÉNDICE
3    061121 - PH PROCEDIMIENTOS SOBRE HERNIA EXCEPT...
4    054192 - MH TRASTORNOS DE LA CONDUCCIÓN Y ARRI...
5    114122 - MH INFECCIONES DE RIÑÓN Y TRACTO URIN...
6    044153 - MH INFECCIONES E INFLAMACIONES RESPIR...
7    158132 - MH NEONATO, PESO AL NACER 2000-2499 G...
8    061201 - PH PROCEDIMIENTOS COMPLEJOS DEL TRACT...
9    146121 - PH PARTO VAGINAL CON PROCED., EXCEPTO...
Name: GRD, dtype: str

In [60]:
# =========================
# FASE 3 - EDA profundo del target
# CELDA 3 - Longitud y consistencia del target
# =========================

grd_str = df_target[target_col].astype(str).str.strip()

longitudes_grd = grd_str.str.len()

print("Resumen de longitudes del target:")
display(longitudes_grd.describe())

print("\nLongitudes únicas más frecuentes:")
display(longitudes_grd.value_counts().sort_index().head(20))

Resumen de longitudes del target:

count    14561.000000
mean        51.656960
std         19.958476
min         18.000000
25%         36.000000
50%         52.000000
75%         67.000000
max        105.000000
Name: GRD, dtype: float64

Longitudes únicas más frecuentes:

GRD
18     54
19    816
20      1
21     69
22     35
23     11
24    297
25    774
26     86
27    112
28     85
29    140
30    219
31    118
32    211
33      7
34     59
35    107
36    558
37    128
Name: count, dtype: int64

## 3.2 Casos nulos, inválidos o mal formados

En esta celda buscamos valores del target que podrían ser problemáticos, por ejemplo:

- cadenas vacías,
- guiones,
- valores nulos,
- textos sospechosos.

Esto es importante porque cualquier problema en el target invalida el modelado si no se corrige antes.

In [61]:
# =========================
# FASE 3 - EDA profundo del target
# CELDA 4 - Detección de casos inválidos
# =========================

grd_limpio = df_target[target_col].astype(str).str.strip()

mask_vacio = grd_limpio.eq("")
mask_guion = grd_limpio.eq("-")
mask_nan_texto = grd_limpio.str.lower().isin(["nan", "none", "null"])

print("Casos vacíos:", mask_vacio.sum())
print("Casos con '-':", mask_guion.sum())
print("Casos tipo 'nan'/'none'/'null':", mask_nan_texto.sum())
print("Nulos reales de pandas:", df_target[target_col].isnull().sum())

Casos vacíos: 0
Casos con '-': 0
Casos tipo 'nan'/'none'/'null': 0
Nulos reales de pandas: 0

In [62]:
# =========================
# FASE 3 - EDA profundo del target
# CELDA 5 - Valores sospechosos poco frecuentes
# =========================

valores_unicos_target = pd.Series(grd_limpio.unique()).sort_values().reset_index(drop=True)

print("Cantidad de valores únicos del target:", len(valores_unicos_target))
display(valores_unicos_target.head(20))

Cantidad de valores únicos del target: 526

0     011202 - PH PROCEDIMIENTOS SOBRE NERVIOS CRANE...
1     014102 - MH ENFERMEDADES Y TRASTORNOS ESPINALE...
2     014103 - MH ENFERMEDADES Y TRASTORNOS ESPINALE...
3     014111 - MH ENFERMEDADES DEGENERATIVAS Y NEOPL...
4     014112 - MH ENFERMEDADES DEGENERATIVAS Y NEOPL...
5     014113 - MH ENFERMEDADES DEGENERATIVAS Y NEOPL...
6     014131 - MH HEMORRAGIA INTRACRANEAL NO TRAUMÁTICA
7     014132 - MH HEMORRAGIA INTRACRANEAL NO TRAUMÁT...
8     014133 - MH HEMORRAGIA INTRACRANEAL NO TRAUMÁT...
9     014141 - MH ACCIDENTE CEREBROVASCULAR CON INFARTO
10    014142 - MH ACCIDENTE CEREBROVASCULAR CON INFA...
11    014143 - MH ACCIDENTE CEREBROVASCULAR CON INFA...
12    014151 - MH ACVA NO ESPECÍFICO Y OCLUSIÓN PREC...
13                     014161 - MH ISQUEMIA TRANSITORIA
14                014162 - MH ISQUEMIA TRANSITORIA W/CC
15               014163 - MH ISQUEMIA TRANSITORIA W/MCC
16    014171 - MH ENFERMEDADES DE NERVIOS CRANEALES ...
17    014172 - MH ENFERMEDADES DE NERVIOS CRANEALES ...
18    014173 - MH ENFERMEDADES DE NERVIOS CRANEALES ...
19    014193 - MH INFECCIONES NO BACTERIANAS DEL SIS...
dtype: str

## 3.3 Tabla de frecuencias del target

Aquí calculamos la distribución completa del GRD:

- frecuencia absoluta
- frecuencia relativa
- porcentaje acumulado

Esta tabla será la base para entender el desbalance y la cola larga del problema.

In [ ]:
# =========================
# FASE 3 - EDA profundo del target
# CELDA 6 - Tabla de frecuencias completa
# =========================

freq_target = grd_limpio.value_counts(dropna=False).rename_axis("GRD").reset_index(name="frecuencia")
freq_target["porcentaje"] = freq_target["frecuencia"] / freq_target["frecuencia"].sum() * 100
freq_target["porcentaje_acumulado"] = freq_target["porcentaje"].cumsum()

print("Cantidad de clases únicas:", freq_target.shape[0])
display(freq_target.head(20))

In [ ]:
# =========================
# FASE 3 - EDA profundo del target
# CELDA 7 - Top 20 clases más frecuentes
# =========================

top20_target = freq_target.head(20).copy()
display(top20_target)

## 3.4 Cobertura acumulada del target

En esta celda evaluamos cuánto del dataset queda cubierto por las clases más frecuentes.

Esto es importante para medir si pocas clases concentran gran parte de los casos o si el target está muy disperso.

In [ ]:
# =========================
# FASE 3 - EDA profundo del target
# CELDA 8 - Cobertura acumulada de clases frecuentes
# =========================

for k in [5, 10, 20, 30, 50, 100]:
    if k <= len(freq_target):
        cobertura = freq_target["porcentaje"].head(k).sum()
        print(f"Top {k:>3} clases cubren: {cobertura:6.2f}% del dataset")

## 3.5 Clases raras

Aquí cuantificamos el tamaño de la cola rara del target.

En particular, revisamos cuántas clases tienen exactamente:

- 1 observación
- 2 observaciones
- 3 observaciones
- 5 o menos observaciones

Esto permite decidir si el problema es viable como clasificación multiclase directa o si requerirá estrategias especiales.

In [ ]:
# =========================
# FASE 3 - EDA profundo del target
# CELDA 9 - Conteo de clases raras
# =========================

conteo_frecuencias = freq_target["frecuencia"].value_counts().sort_index()

print("Cantidad de clases con 1 observación:", (freq_target["frecuencia"] == 1).sum())
print("Cantidad de clases con 2 observaciones:", (freq_target["frecuencia"] == 2).sum())
print("Cantidad de clases con 3 observaciones:", (freq_target["frecuencia"] == 3).sum())
print("Cantidad de clases con 5 o menos observaciones:", (freq_target["frecuencia"] <= 5).sum())
print("Cantidad de clases con 10 o menos observaciones:", (freq_target["frecuencia"] <= 10).sum())

In [ ]:
# =========================
# FASE 3 - EDA profundo del target
# CELDA 10 - Tabla de clases raras
# =========================

tabla_clases_raras = {
    "frecuencia_1": freq_target.loc[freq_target["frecuencia"] == 1, "GRD"].tolist(),
    "frecuencia_2": freq_target.loc[freq_target["frecuencia"] == 2, "GRD"].tolist(),
    "frecuencia_3": freq_target.loc[freq_target["frecuencia"] == 3, "GRD"].tolist(),
    "frecuencia_5_o_menos": freq_target.loc[freq_target["frecuencia"] <= 5, "GRD"].tolist(),
}

print("Cantidad de clases en frecuencia_1:", len(tabla_clases_raras["frecuencia_1"]))
print("Cantidad de clases en frecuencia_2:", len(tabla_clases_raras["frecuencia_2"]))
print("Cantidad de clases en frecuencia_3:", len(tabla_clases_raras["frecuencia_3"]))
print("Cantidad de clases en frecuencia_5_o_menos:", len(tabla_clases_raras["frecuencia_5_o_menos"]))

## 3.6 Visualización del desbalance del target

En esta sección graficamos:

- top 20 clases más frecuentes,
- distribución de frecuencias,
- curva de cola larga,
- y cobertura acumulada.

Estos gráficos son obligatorios porque ayudan a ver visualmente la concentración y el desbalance del problema.

In [ ]:
# =========================
# FASE 3 - EDA profundo del target
# CELDA 11 - Imports gráficos
# =========================

import matplotlib.pyplot as plt

In [ ]:
# =========================
# FASE 3 - EDA profundo del target
# CELDA 12 - Barplot top 20 clases
# =========================

plt.figure(figsize=(14, 6))
plt.bar(top20_target["GRD"], top20_target["frecuencia"])
plt.xticks(rotation=90)
plt.title("Top 20 clases GRD más frecuentes")
plt.xlabel("GRD")
plt.ylabel("Frecuencia")
plt.tight_layout()
plt.show()

In [ ]:
# =========================
# FASE 3 - EDA profundo del target
# CELDA 13 - Curva de cola larga
# =========================

plt.figure(figsize=(14, 6))
plt.plot(range(1, len(freq_target) + 1), freq_target["frecuencia"].values)
plt.title("Curva de cola larga del target GRD")
plt.xlabel("Ranking de clase")
plt.ylabel("Frecuencia")
plt.tight_layout()
plt.show()

In [ ]:
# =========================
# FASE 3 - EDA profundo del target
# CELDA 14 - Cobertura acumulada
# =========================

plt.figure(figsize=(14, 6))
plt.plot(range(1, len(freq_target) + 1), freq_target["porcentaje_acumulado"].values)
plt.axhline(80, linestyle="--")
plt.axhline(90, linestyle="--")
plt.axhline(95, linestyle="--")
plt.title("Cobertura acumulada de clases GRD")
plt.xlabel("Número de clases ordenadas por frecuencia")
plt.ylabel("Porcentaje acumulado (%)")
plt.tight_layout()
plt.show()

In [ ]:
# =========================
# FASE 3 - EDA profundo del target
# CELDA 15 - Histograma de frecuencias de clase
# =========================

plt.figure(figsize=(10, 6))
plt.hist(freq_target["frecuencia"], bins=30)
plt.title("Histograma de frecuencias por clase GRD")
plt.xlabel("Frecuencia de la clase")
plt.ylabel("Cantidad de clases")
plt.tight_layout()
plt.show()

## 3.7 Resumen ejecutivo del target

En esta celda resumimos los hallazgos principales del target para dejar trazabilidad metodológica antes de pasar a decisiones de modelado.

In [ ]:
# =========================
# FASE 3 - EDA profundo del target
# CELDA 16 - Resumen ejecutivo
# =========================

resumen_target = {
    "n_observaciones": len(df_target),
    "n_clases_unicas": freq_target.shape[0],
    "clase_mas_frecuente": freq_target.iloc[0]["GRD"],
    "frecuencia_clase_mas_frecuente": int(freq_target.iloc[0]["frecuencia"]),
    "porcentaje_clase_mas_frecuente": float(freq_target.iloc[0]["porcentaje"]),
    "clases_con_1_caso": int((freq_target["frecuencia"] == 1).sum()),
    "clases_con_5_o_menos": int((freq_target["frecuencia"] <= 5).sum()),
    "top_10_cobertura_pct": float(freq_target["porcentaje"].head(10).sum()),
    "top_20_cobertura_pct": float(freq_target["porcentaje"].head(20).sum()),
}

resumen_target

## 3.8 Conclusión metodológica preliminar

Esta celda deja por escrito qué decisiones habilita el análisis del target.

A partir de esta fase podremos decidir si:

- la clasificación multiclase directa es razonable,
- el desbalance es extremo,
- necesitaremos estrategias de rare classes,
- y qué métricas serán más adecuadas para evaluar el modelo.

In [ ]:
# =========================
# FASE 3 - EDA profundo del target
# CELDA 17 - Conclusión preliminar
# =========================

conclusion_fase_3 = """
El análisis del target GRD permitirá determinar si el problema puede abordarse como una clasificación
multiclase directa o si será necesario aplicar estrategias especiales para clases raras.

En particular, esta fase busca medir la cantidad real de clases, la concentración de casos en clases
dominantes, la existencia de cola larga y el nivel de desbalance del problema. Con esa evidencia podremos
definir mejor las métricas de evaluación, priorizando métricas robustas al desbalance como macro-F1,
weighted-F1, recall por clase y matriz de confusión, en lugar de depender únicamente de accuracy.
"""

print(conclusion_fase_3)

El análisis del target GRD evidencia que el problema presenta alta cardinalidad (526 clases) y una distribución fuertemente desbalanceada con presencia de cola larga.

Se observa que una proporción significativa de clases posee muy baja frecuencia, incluyendo 76 clases con una sola observación y 224 clases con cinco o menos observaciones, lo que dificulta el aprendizaje robusto de modelos de clasificación multiclase directa.

Asimismo, las clases más frecuentes no concentran una proporción dominante del dataset (la clase más frecuente representa aproximadamente un 5.6%), lo que refuerza la complejidad del problema.

En base a esta evidencia, se concluye que una estrategia de clasificación directa sobre el GRD completo no es metodológicamente adecuada, siendo necesario considerar alternativas como:

- agrupación de clases (por categoría diagnóstica o jerarquía GRD),
- filtrado de clases raras,
- o enfoques jerárquicos de clasificación.

Finalmente, se establece que la evaluación del modelo deberá priorizar métricas robustas al desbalance, como F1-score (macro y weighted), en lugar de depender únicamente de accuracy.

# FASE 4 — EDA univariado de variables

En esta fase se realiza un análisis individual de cada variable del dataset.

Se separa el análisis en:

- variables numéricas
- variables categóricas

El objetivo es evaluar:

- calidad de datos
- distribución
- cardinalidad
- presencia de valores extremos
- utilidad potencial para el modelo

Esto permitirá tomar decisiones sobre:

- limpieza
- transformación
- encoding
- eliminación de variables

## 4A — Análisis de variables numéricas

Se analizarán variables numéricas para identificar:

- valores fuera de rango
- asimetría
- presencia de outliers
- necesidad de transformaciones

En este dataset, la principal variable numérica es:
- Edad en años

In [ ]:
# =========================
# FASE 4 - CELDA 1
# Variables numéricas
# =========================

numericas = df_main.select_dtypes(include=["int64", "float64"]).columns.tolist()

print("Variables numéricas:", numericas)

In [ ]:
# =========================
# FASE 4 - CELDA 2
# Estadísticos descriptivos
# =========================

df_main[numericas].describe()

In [ ]:
# =========================
# FASE 4 - CELDA 3
# Percentiles detallados
# =========================

df_main[numericas].quantile([0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99])

In [ ]:
# =========================
# FASE 4 - CELDA 4
# Asimetría
# =========================

df_main[numericas].skew()

In [ ]:
# =========================
# FASE 4 - CELDA 5
# Histograma
# =========================

import matplotlib.pyplot as plt

for col in numericas:
    plt.figure()
    plt.hist(df_main[col], bins=30)
    plt.title(f"Histograma - {col}")
    plt.xlabel(col)
    plt.ylabel("Frecuencia")
    plt.show()

In [ ]:
# =========================
# FASE 4 - CELDA 6
# Boxplot
# =========================

for col in numericas:
    plt.figure()
    plt.boxplot(df_main[col])
    plt.title(f"Boxplot - {col}")
    plt.show()

In [ ]:
# =========================
# FASE 4 - CELDA 7
# Outliers simples (IQR)
# =========================

for col in numericas:
    q1 = df_main[col].quantile(0.25)
    q3 = df_main[col].quantile(0.75)
    iqr = q3 - q1
    
    outliers = df_main[(df_main[col] < q1 - 1.5*iqr) | (df_main[col] > q3 + 1.5*iqr)]
    
    print(f"{col} → outliers:", len(outliers))

## 4B — Análisis de variables categóricas

Se analizarán las variables categóricas para evaluar:

- cardinalidad
- distribución
- presencia de categorías raras
- consistencia de valores

Esto es especialmente importante en este dataset, ya que la mayoría de variables son categóricas.

In [ ]:
# =========================
# FASE 4 - CELDA 8
# Variables categóricas
# =========================

categoricas = df_main.select_dtypes(include=["object"]).columns.tolist()

print("Cantidad de variables categóricas:", len(categoricas))

In [ ]:
# =========================
# FASE 4 - CELDA 9
# Cardinalidad por variable
# =========================

cardinalidad = {}

for col in categoricas:
    cardinalidad[col] = df_main[col].nunique()

cardinalidad = pd.Series(cardinalidad).sort_values(ascending=False)

cardinalidad.head(15)

In [ ]:
# =========================
# FASE 4 - CELDA 10
# Nulos reales en categóricas
# =========================

def contar_nulos_reales(col):
    col = col.astype(str).str.strip()
    return ((col == "") | (col == "-") | (col == "nan")).mean() * 100

nulos_cat = {}

for col in categoricas:
    nulos_cat[col] = contar_nulos_reales(df_main[col])

pd.Series(nulos_cat).sort_values(ascending=False).head(15)

In [ ]:
# =========================
# FASE 4 - CELDA 11
# Top categorías por variable
# =========================

def top_categorias(df, col, n=5):
    return df[col].value_counts().head(n)

for col in categoricas[:5]:  # puedes ampliar después
    print(f"\n🔹 {col}")
    display(top_categorias(df_main, col))

In [ ]:
# =========================
# FASE 4 - CELDA 12
# Variables de alta cardinalidad
# =========================

alta_card = [col for col in categoricas if df_main[col].nunique() > 50]

print("Variables de alta cardinalidad:", len(alta_card))
alta_card[:10]

In [ ]:
# =========================
# FASE 4 - CELDA 13
# Categorías raras
# =========================

def categorias_raras(df, col, umbral=5):
    vc = df[col].value_counts()
    return (vc <= umbral).sum()

raras = {}

for col in categoricas:
    raras[col] = categorias_raras(df_main, col)

pd.Series(raras).sort_values(ascending=False).head(15)

In [ ]:
# =========================
# FASE 4 - CELDA 14
# Barplot categórico
# =========================

col = "Sexo (Desc)"

df_main[col].value_counts().plot(kind="bar", title=col)
plt.show()

El análisis univariado evidencia que el dataset presenta una fuerte predominancia de variables categóricas de alta cardinalidad, particularmente en los diagnósticos clínicos, los cuales superan ampliamente las mil categorías por variable.

Además, se observa que múltiples variables presentan un porcentaje de valores nulos superior al 95%, lo que indica una baja utilidad informativa y sugiere su eliminación para evitar introducir ruido en el modelo.

En relación con la variable numérica edad, se identifica una distribución equilibrada sin sesgos significativos, con valores coherentes en el contexto clínico, incluyendo presencia de pacientes neonatales. La variable no requiere transformaciones, aunque se identifica como candidata a generación de variables derivadas.

En cuanto a las variables categóricas, se detecta la presencia de una gran cantidad de categorías poco frecuentes, lo que refuerza la necesidad de aplicar técnicas de agrupación o reducción de cardinalidad, tales como agrupación por categorías clínicas o consolidación en categorías “otras”.

En base a este análisis, se concluye que el dataset requiere un proceso de reducción de dimensionalidad categórica y limpieza estructural antes de ser utilizado en modelos de aprendizaje automático.

# FASE 5 — EDA bivariado completo

En esta fase se analiza la relación entre TODAS las variables del dataset y el target `GRD`.

A diferencia del análisis anterior (enfocado en variables clave), aquí se realiza un barrido sistemático para:

- identificar variables con señal real
- detectar variables irrelevantes o constantes
- evaluar cardinalidad y posibles problemas de encoding
- priorizar variables para modelado

El análisis se separa en:
- variables numéricas vs target
- variables categóricas vs target

In [ ]:
# =========================
# FASE 5A - CELDA 1
# Identificación de variables numéricas
# =========================

import numpy as np

variables_numericas = df_main.select_dtypes(include=[np.number]).columns.tolist()

print("Variables numéricas encontradas:", len(variables_numericas))
variables_numericas

In [ ]:
# =========================
# FASE 5A - CELDA 2
# Subconjunto top clases del target
# =========================

top_n = 10

top_classes = df_main["GRD"].value_counts().head(top_n).index.tolist()
df_top_num = df_main[df_main["GRD"].isin(top_classes)].copy()

print("Clases consideradas:")
for c in top_classes:
    print("-", c)

## Función de análisis numérico vs target

Esta función permitirá evaluar cada variable numérica de forma consistente.

In [ ]:
# =========================
# FASE 5A - CELDA 3
# Función análisis numérico
# =========================

import seaborn as sns
import matplotlib.pyplot as plt

def analizar_numerica_vs_target(df, col, target="GRD"):
    
    print("="*80)
    print(f"ANÁLISIS NUMÉRICO: {col}")
    print("="*80)
    
    df_temp = df[[col, target]].dropna()
    
    if df_temp[col].nunique() <= 1:
        print("Variable constante → sin valor predictivo")
        return
    
    print("Resumen estadístico:")
    display(df_temp.groupby(target)[col].describe())
    
    # Boxplot
    plt.figure(figsize=(12,5))
    sns.boxplot(data=df_temp, x=target, y=col)
    plt.xticks(rotation=90)
    plt.title(f"{col} vs {target}")
    plt.show()

In [ ]:
# =========================
# FASE 5A - CELDA 4
# Ejecución automática numéricas
# =========================

for col in variables_numericas:
    analizar_numerica_vs_target(df_top_num, col)

## 5B — Variables categóricas vs target

Se analizarán todas las variables categóricas en relación con el target.

Se evaluará:

- frecuencia de categorías
- relación con el target
- proporciones condicionadas
- fuerza de asociación

Dado el alto número de categorías, se limitará el análisis a las más frecuentes para mantener interpretabilidad.

In [ ]:
# =========================
# FASE 5B - CELDA 5
# Identificación variables categóricas
# =========================

variables_categoricas = df_main.select_dtypes(include=["object"]).columns.tolist()

# eliminar target
variables_categoricas = [col for col in variables_categoricas if col != "GRD"]

print("Variables categóricas:", len(variables_categoricas))
variables_categoricas

## Función de análisis categórico vs target

Esta función permitirá evaluar cada variable categórica de forma automatizada.

In [ ]:
# =========================
# FASE 5B - CELDA 6
# Función categórica
# =========================

def analizar_categorica_vs_target(df, col, target="GRD", top_n=15):
    
    print("="*80)
    print(f"ANÁLISIS CATEGÓRICO: {col}")
    print("="*80)
    
    df_temp = df[[col, target]].dropna()
    
    cardinalidad = df_temp[col].nunique()
    print(f"Cardinalidad: {cardinalidad}")
    
    if cardinalidad == 1:
        print("Variable constante → sin valor predictivo")
        return
    
    vc = df_temp[col].value_counts()
    top_cats = vc.head(top_n).index
    
    df_temp = df_temp[df_temp[col].isin(top_cats)]
    
    tabla = pd.crosstab(df_temp[col], df_temp[target])
    tabla_prop = tabla.div(tabla.sum(axis=1), axis=0)
    
    print("Top categorías:")
    display(vc.head(10))
    
    print("Proporciones por categoría:")
    display(tabla_prop.round(3))
    
    # Heatmap
    plt.figure(figsize=(12,6))
    sns.heatmap(tabla_prop, cmap="Reds")
    plt.title(f"{col} vs {target} (proporciones)")
    plt.show()
    
    # Fuerza de asociación simple
    max_prop = tabla_prop.max(axis=1).sort_values(ascending=False)
    
    print("Categorías más predictivas:")
    display(max_prop.head(10))
    
    return max_prop.max()

In [ ]:
# =========================
# FASE 5B - CELDA 7
# Ejecución automática categóricas
# =========================

ranking_variables = []

for col in variables_categoricas:
    try:
        score = analizar_categorica_vs_target(df_main, col)
        
        if score is not None:
            ranking_variables.append({
                "variable": col,
                "score_max": score
            })
            
    except Exception as e:
        print(f"Error en {col}: {e}")

## Ranking de variables según señal

Se construye un ranking simple basado en la máxima proporción observada por categoría.
Esto permite identificar qué variables tienen mayor poder discriminativo respecto al target.

In [ ]:
# =========================
# FASE 5B - CELDA 8
# Ranking final
# =========================

df_ranking = pd.DataFrame(ranking_variables).sort_values(
    by="score_max", ascending=False
)

df_ranking.head(20)

## Cierre de la fase

Este análisis permite:

- identificar variables altamente predictivas
- detectar variables con bajo valor
- evaluar cardinalidad y complejidad
- preparar decisiones para feature engineering

La información obtenida será clave para definir el conjunto final de variables del modelo.

# FASE 6 — Relaciones entre variables (features)

En esta fase analizamos la relación entre las variables explicativas del dataset.

A diferencia de fases anteriores, aquí no estudiamos variables de forma aislada, sino que buscamos entender:

- relaciones entre variables
- redundancia de información
- posibles dependencias estructurales
- patrones de valores faltantes

Este análisis permitirá tomar decisiones sobre:
- selección de variables
- eliminación de redundancia
- construcción de nuevas features

## 6A — Correlación entre variables numéricas

Se analizará la relación entre variables numéricas mediante:

- correlación de Pearson (lineal)
- correlación de Spearman (no lineal / monotónica)

Esto permitirá identificar:
- variables redundantes
- relaciones fuertes
- posibles problemas de multicolinealidad

In [ ]:
# =========================
# FASE 6A - CELDA 1
# Identificación variables numéricas
# =========================

import numpy as np

variables_numericas = df_main.select_dtypes(include=[np.number]).columns.tolist()

print("Variables numéricas encontradas:", len(variables_numericas))
variables_numericas

In [ ]:
# =========================
# FASE 6A - CELDA 2
# Correlación Pearson
# =========================

import seaborn as sns
import matplotlib.pyplot as plt

if len(variables_numericas) > 1:
    corr_pearson = df_main[variables_numericas].corr(method="pearson")
    
    plt.figure(figsize=(10, 8))
    sns.heatmap(corr_pearson, cmap="coolwarm", center=0)
    plt.title("Correlación Pearson")
    plt.show()
else:
    print("No hay suficientes variables numéricas para correlación")

In [ ]:
# =========================
# FASE 6A - CELDA 3
# Correlación Spearman
# =========================

if len(variables_numericas) > 1:
    corr_spearman = df_main[variables_numericas].corr(method="spearman")
    
    plt.figure(figsize=(10, 8))
    sns.heatmap(corr_spearman, cmap="coolwarm", center=0)
    plt.title("Correlación Spearman")
    plt.show()
else:
    print("No hay suficientes variables numéricas para correlación")

## 6B — Asociación entre variables categóricas

Dado que gran parte del dataset es categórico, se evaluará la asociación entre variables categóricas usando Cramér’s V.

Esto permitirá detectar:
- dependencia entre variables
- redundancia estructural
- posibles agrupaciones

In [ ]:
# =========================
# FASE 6B - CELDA 4
# Variables categóricas
# =========================

variables_categoricas = df_main.select_dtypes(include=["object"]).columns.tolist()
variables_categoricas = [col for col in variables_categoricas if col != "GRD"]

print("Variables categóricas:", len(variables_categoricas))

In [ ]:
# =========================
# FASE 6B - CELDA 5
# Función Cramér's V
# =========================

import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency

def cramers_v(x, y):
    tabla = pd.crosstab(x, y)
    
    if tabla.shape[0] < 2 or tabla.shape[1] < 2:
        return np.nan
    
    chi2 = chi2_contingency(tabla)[0]
    n = tabla.sum().sum()
    r, k = tabla.shape
    
    return np.sqrt(chi2 / (n * (min(k - 1, r - 1))))

In [ ]:
# =========================
# FASE 6B - CELDA 6
# Matriz de asociación (subset para control)
# =========================

# IMPORTANTE: limitar variables para evitar explosión computacional
subset_vars = variables_categoricas[:10]

matriz_asociacion = pd.DataFrame(index=subset_vars, columns=subset_vars)

for f1 in subset_vars:
    for f2 in subset_vars:
        if f1 == f2:
            matriz_asociacion.loc[f1, f2] = 1.0
        else:
            df_temp = df_main[[f1, f2]].dropna()
            matriz_asociacion.loc[f1, f2] = cramers_v(df_temp[f1], df_temp[f2])

matriz_asociacion = matriz_asociacion.astype(float)

matriz_asociacion

In [ ]:
# =========================
# FASE 6B - CELDA 7
# Heatmap asociación categórica
# =========================

plt.figure(figsize=(8, 6))
sns.heatmap(matriz_asociacion, annot=True, cmap="viridis")
plt.title("Asociación entre variables categóricas (Cramér's V)")
plt.show()

## 6C — Scatterplots entre variables numéricas

Se visualizan relaciones entre variables numéricas relevantes para detectar:

- relaciones no lineales
- clusters
- outliers

In [ ]:
# =========================
# FASE 6C - CELDA 8
# Scatterplots (si aplica)
# =========================

if len(variables_numericas) >= 2:
    sns.pairplot(df_main[variables_numericas].dropna().sample(500))
else:
    print("No hay suficientes variables numéricas para scatterplots")

## 6D — Correlación de valores faltantes

Se analiza si los valores faltantes están relacionados entre variables,
lo que puede indicar patrones estructurales en los datos.

In [ ]:
# =========================
# FASE 6D - CELDA 9
# Matriz de missingness
# =========================

missing = df_main.isnull().astype(int)

missing_corr = missing.corr()

missing_corr

In [ ]:
# =========================
# FASE 6D - CELDA 10
# Heatmap missingness
# =========================

plt.figure(figsize=(10, 8))
sns.heatmap(missing_corr, cmap="coolwarm")
plt.title("Correlación de valores faltantes")
plt.show()

# FASE 7 — Análisis de datos faltantes

En esta fase se analiza en profundidad la presencia de valores faltantes en el dataset.

No se trata solo de contar nulos, sino de entender:

- dónde están
- cómo se distribuyen
- si siguen patrones estructurales
- si tienen significado clínico

Este análisis permitirá decidir:
- eliminar variables
- imputar valores
- crear variables indicadoras
- mantener nulos si tienen significado

## 7A — Porcentaje de nulos por columna

Se calcula el porcentaje de valores faltantes para cada variable del dataset.
Esto permite identificar columnas problemáticas o incompletas.

In [ ]:
# =========================
# FASE 7A - CELDA 1
# Nulos por columna
# =========================

nulls_col = df_main.isnull().sum()
nulls_pct_col = (nulls_col / len(df_main)) * 100

df_nulls_col = pd.DataFrame({
    "nulos": nulls_col,
    "porcentaje": nulls_pct_col
}).sort_values(by="porcentaje", ascending=False)

df_nulls_col.head(20)

## 7B — Porcentaje de nulos por fila

Se analiza cuántos valores faltantes tiene cada registro.
Esto permite detectar:
- filas incompletas
- registros problemáticos
- posibles patrones de ausencia de datos

In [ ]:
# =========================
# FASE 7B - CELDA 2
# Nulos por fila
# =========================

nulls_row = df_main.isnull().sum(axis=1)
nulls_pct_row = (nulls_row / df_main.shape[1]) * 100

df_main["nulls_row"] = nulls_row
df_main["nulls_pct_row"] = nulls_pct_row

df_main[["nulls_row", "nulls_pct_row"]].describe()

In [ ]:
# =========================
# FASE 7B - CELDA 3
# Distribución de nulos por fila
# =========================

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
sns.histplot(df_main["nulls_pct_row"], bins=30)
plt.title("Distribución de % de nulos por fila")
plt.xlabel("% nulos")
plt.show()

## 7C — Mapa de valores faltantes

Se visualiza la estructura de los valores faltantes para detectar:

- patrones en bloques
- columnas dependientes
- estructura tipo "slots"

In [ ]:
# =========================
# FASE 7C - CELDA 4
# Heatmap de nulos
# =========================

plt.figure(figsize=(12,6))
sns.heatmap(df_main.isnull(), cbar=False)
plt.title("Mapa de valores faltantes")
plt.show()

## 7D — Relación entre nulos y el target

Se analiza si la presencia de valores faltantes está asociada al target.

Esto permite detectar:
- sesgos
- patrones estructurales relevantes para el modelo

In [ ]:
# =========================
# FASE 7D - CELDA 5
# Ejemplo con variables clave
# =========================

columnas_clave = df_nulls_col.head(10).index.tolist()

for col in columnas_clave:
    
    print("="*60)
    print(f"NULOS vs GRD → {col}")
    print("="*60)
    
    df_temp = df_main[[col, "GRD"]].copy()
    df_temp["es_nulo"] = df_temp[col].isnull()
    
    tabla = pd.crosstab(df_temp["es_nulo"], df_temp["GRD"], normalize="index")
    display(tabla.round(3))

## 7E — Interpretación de los valores faltantes

En datasets clínicos como este, los valores faltantes suelen tener significado estructural.

Ejemplo:
- Diag 01 → casi siempre presente
- Diag 10 → muchas veces nulo

Esto NO es missing aleatorio, sino:

→ ausencia de diagnóstico adicional

Por lo tanto:
- el nulo puede tener significado clínico
- no siempre debe imputarse

# FASE 8 — EDA y auditoría de bases auxiliares

En esta fase analizamos las bases auxiliares como fuentes analíticas.

El objetivo es responder, para cada auxiliar:

- qué representa,
- qué aporta al problema,
- cuál es su llave,
- qué cobertura tiene respecto a la base principal,
- si la llave está limpia,
- si existen duplicados por llave,
- si la relación es 1:1, 1:n o n:n,
- si sus columnas son utilizables antes del modelado,
- si aporta contexto clínico útil,
- si introduce ruido,
- si expone leakage,
- y si requiere agregación previa antes de un merge.

Esta fase es crítica porque evita integrar tablas por intuición y obliga a validar su utilidad real.

## Preparación conceptual de las comparaciones

Antes de auditar las auxiliares, dejamos explícito qué se comparará con qué:

- `CIE-10` corresponde a diagnósticos → se comparará contra columnas `Diag`
- `CIE-9` corresponde a procedimientos → se comparará contra columnas `Proced`
- tablas GRD se auditarán con foco en riesgo de leakage

Además, construiremos versiones limpias de los códigos en la base principal para poder medir cobertura real.

In [ ]:
# =========================
# FASE 8 - CELDA 1
# Imports y definición de columnas diagnósticas/procedimientos
# =========================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

diag_cols = [c for c in df_main.columns if c.startswith("Diag ")]
proc_cols = [c for c in df_main.columns if c.startswith("Proced ")]

print("Cantidad de columnas diagnósticas:", len(diag_cols))
print("Cantidad de columnas de procedimientos:", len(proc_cols))

print("\nPrimeras columnas diagnósticas:")
print(diag_cols[:5])

print("\nPrimeras columnas de procedimientos:")
print(proc_cols[:5])

## Limpieza de códigos de la base principal

Las columnas de la base principal vienen en formato `cod+des`, por lo que debemos extraer únicamente el código para poder comparar contra las llaves de las auxiliares.

Se construirá:

- una versión limpia del diagnóstico principal,
- una versión limpia del procedimiento principal,
- y conjuntos de códigos únicos de todos los diagnósticos y procedimientos presentes en la base.

In [ ]:
# =========================
# FASE 8 - CELDA 2
# Función de extracción de código
# =========================

def extraer_codigo(x):
    if pd.isna(x):
        return np.nan
    
    x = str(x).strip().upper()
    
    if x in ["", "-", "NAN", "NONE", "NULL"]:
        return np.nan
    
    # toma el bloque antes del primer espacio
    return x.split(" ")[0]

df_main["diag_principal_cod"] = df_main["Diag 01 Principal (cod+des)"].apply(extraer_codigo)
df_main["proc_principal_cod"] = df_main["Proced 01 Principal (cod+des)"].apply(extraer_codigo)

display(df_main[["Diag 01 Principal (cod+des)", "diag_principal_cod",
                 "Proced 01 Principal (cod+des)", "proc_principal_cod"]].head(10))

In [ ]:
# =========================
# FASE 8 - CELDA 3
# Conjuntos de códigos únicos en la base principal
# =========================

def extraer_codigos_unicos(df, cols):
    valores = []
    for c in cols:
        valores.extend(df[c].dropna().apply(extraer_codigo).dropna().tolist())
    return set(valores)

diag_codes_main_all = extraer_codigos_unicos(df_main, diag_cols)
proc_codes_main_all = extraer_codigos_unicos(df_main, proc_cols)

diag_codes_main_principal = set(df_main["diag_principal_cod"].dropna())
proc_codes_main_principal = set(df_main["proc_principal_cod"].dropna())

print("Diagnósticos únicos (todos los slots):", len(diag_codes_main_all))
print("Diagnósticos únicos (solo principal):", len(diag_codes_main_principal))
print("Procedimientos únicos (todos los slots):", len(proc_codes_main_all))
print("Procedimientos únicos (solo principal):", len(proc_codes_main_principal))

## Función general de auditoría de auxiliar

Se define una función reusable para analizar cualquier base auxiliar, incluyendo:

- dimensiones
- nulos
- calidad de llave
- duplicados por llave
- tipo de relación
- cobertura respecto a la base principal
- consistencia de códigos

In [ ]:
# =========================
# FASE 8 - CELDA 4
# Función general de auditoría
# =========================

def auditar_auxiliar(df_aux, nombre, key_col, codigos_main=None):
    print("=" * 100)
    print(f"AUDITORÍA DE AUXILIAR: {nombre}")
    print("=" * 100)
    
    print("\n1) Dimensiones")
    print(df_aux.shape)
    
    print("\n2) Columnas")
    print(df_aux.columns.tolist())
    
    print("\n3) Nulos por columna (%)")
    nulls_pct = (df_aux.isnull().sum() / len(df_aux) * 100).sort_values(ascending=False)
    display(nulls_pct.to_frame("pct_nulos"))
    
    print("\n4) Calidad de la llave")
    print("Columna llave:", key_col)
    print("Nulos en llave:", df_aux[key_col].isnull().sum())
    print("Valores únicos en llave:", df_aux[key_col].nunique(dropna=True))
    print("Duplicados por llave:", df_aux[key_col].duplicated().sum())
    
    conteo = df_aux[key_col].value_counts(dropna=False)
    print("\n5) Tipo de relación según la llave")
    print("Máximo registros por llave:", conteo.max())
    print("Promedio registros por llave:", conteo.mean())
    
    if conteo.max() == 1:
        print("→ Relación aparente: 1:1")
    else:
        print("→ Relación aparente: 1:n o n:n")
    
    if codigos_main is not None:
        aux_keys = set(df_aux[key_col].dropna().astype(str).str.strip().str.upper())
        inter = codigos_main.intersection(aux_keys)
        faltantes_main = codigos_main - aux_keys
        
        print("\n6) Cobertura respecto a la base principal")
        print("Códigos únicos en main:", len(codigos_main))
        print("Códigos únicos en auxiliar:", len(aux_keys))
        print("Match:", len(inter))
        print("Cobertura (%):", round(len(inter) / len(codigos_main) * 100, 2) if len(codigos_main) > 0 else np.nan)
        print("Códigos de main no encontrados en auxiliar:", len(faltantes_main))
        
        return {
            "nulls_pct": nulls_pct,
            "duplicados_llave": int(df_aux[key_col].duplicated().sum()),
            "max_registros_por_llave": int(conteo.max()),
            "cobertura_pct": round(len(inter) / len(codigos_main) * 100, 2) if len(codigos_main) > 0 else np.nan,
            "faltantes_main": faltantes_main
        }
    
    return {
        "nulls_pct": nulls_pct,
        "duplicados_llave": int(df_aux[key_col].duplicated().sum()),
        "max_registros_por_llave": int(conteo.max())
    }

## 8A — CIE-10

### Qué representa
Diccionario clínico de diagnósticos.

### Qué aporta
Aporta descripción clínica y, si está disponible, niveles jerárquicos como capítulo o categoría.

### Qué vamos a validar
- limpieza de llave
- duplicados
- tipo de relación
- cobertura contra diagnósticos de la base principal
- utilidad de sus columnas antes del modelado

In [ ]:
# =========================
# FASE 8A - CELDA 5
# Estandarización mínima CIE-10
# =========================

cie10 = cie10.copy()
cie10["Código"] = cie10["Código"].astype(str).str.strip().str.upper()

resultado_cie10_principal = auditar_auxiliar(
    cie10,
    "CIE-10 vs diagnóstico principal",
    key_col="Código",
    codigos_main=diag_codes_main_principal
)

resultado_cie10_total = auditar_auxiliar(
    cie10,
    "CIE-10 vs todos los diagnósticos",
    key_col="Código",
    codigos_main=diag_codes_main_all
)

## Nulos y duplicados de CIE-10 en forma visual

Se generan tablas y gráficos simples para revisar rápidamente la calidad estructural de la base.

In [ ]:
# =========================
# FASE 8A - CELDA 6
# Gráfico de nulos CIE-10
# =========================

nulls_cie10 = (cie10.isnull().sum() / len(cie10) * 100).sort_values(ascending=False)

plt.figure(figsize=(10, 5))
plt.bar(nulls_cie10.index.astype(str), nulls_cie10.values)
plt.xticks(rotation=90)
plt.ylabel("% nulos")
plt.title("CIE-10 — porcentaje de nulos por columna")
plt.tight_layout()
plt.show()

In [ ]:
# =========================
# FASE 8A - CELDA 7
# Categorías relevantes CIE-10
# =========================

# Mostrar columnas potencialmente útiles
print("Columnas disponibles en CIE-10:")
print(cie10.columns.tolist())

# Intento de detectar columnas semánticas relevantes
cols_relevantes_cie10 = [c for c in cie10.columns if any(k in c.lower() for k in ["cap", "cat", "desc", "grupo", "capítulo", "categoria"])]
print("\nColumnas semánticamente relevantes detectadas:")
print(cols_relevantes_cie10)

for c in cols_relevantes_cie10[:3]:
    print(f"\nFrecuencias top para: {c}")
    display(cie10[c].value_counts(dropna=False).head(15))

In [ ]:
# =========================
# FASE 8A - CELDA 8
# Resumen de consistencia de códigos CIE-10
# =========================

faltantes_cie10_principal = sorted(list(resultado_cie10_principal["faltantes_main"]))[:30]
faltantes_cie10_total = sorted(list(resultado_cie10_total["faltantes_main"]))[:30]

print("Ejemplos de códigos del diagnóstico principal no encontrados en CIE-10:")
print(faltantes_cie10_principal)

print("\nEjemplos de códigos de cualquier diagnóstico no encontrados en CIE-10:")
print(faltantes_cie10_total)

## 8B — CIE-9

### Qué representa
Base de códigos clínicos que, en este proyecto, debe contrastarse contra procedimientos.

### Qué aporta
Si la relación es válida, puede aportar descripción y jerarquía de procedimientos.

### Qué vamos a validar
- limpieza de llave
- duplicados
- tipo de relación
- cobertura contra procedimientos de la base principal
- necesidad de agregación previa si la relación no es 1:1

In [ ]:
# =========================
# FASE 8B - CELDA 9
# Estandarización mínima CIE-9
# =========================

cie9 = cie9.copy()
cie9["Código"] = cie9["Código"].astype(str).str.strip().str.upper()

resultado_cie9_principal = auditar_auxiliar(
    cie9,
    "CIE-9 vs procedimiento principal",
    key_col="Código",
    codigos_main=proc_codes_main_principal
)

resultado_cie9_total = auditar_auxiliar(
    cie9,
    "CIE-9 vs todos los procedimientos",
    key_col="Código",
    codigos_main=proc_codes_main_all
)

In [ ]:
# =========================
# FASE 8B - CELDA 10
# Gráfico de nulos CIE-9
# =========================

nulls_cie9 = (cie9.isnull().sum() / len(cie9) * 100).sort_values(ascending=False)

plt.figure(figsize=(10, 5))
plt.bar(nulls_cie9.index.astype(str), nulls_cie9.values)
plt.xticks(rotation=90)
plt.ylabel("% nulos")
plt.title("CIE-9 — porcentaje de nulos por columna")
plt.tight_layout()
plt.show()

In [ ]:
# =========================
# FASE 8B - CELDA 11
# Categorías relevantes CIE-9
# =========================

print("Columnas disponibles en CIE-9:")
print(cie9.columns.tolist())

cols_relevantes_cie9 = [c for c in cie9.columns if any(k in c.lower() for k in ["cap", "cat", "desc", "grupo", "capítulo", "categoria"])]
print("\nColumnas semánticamente relevantes detectadas:")
print(cols_relevantes_cie9)

for c in cols_relevantes_cie9[:3]:
    print(f"\nFrecuencias top para: {c}")
    display(cie9[c].value_counts(dropna=False).head(15))

In [ ]:
# =========================
# FASE 8B - CELDA 12
# Resumen de consistencia de códigos CIE-9
# =========================

faltantes_cie9_principal = sorted(list(resultado_cie9_principal["faltantes_main"]))[:30]
faltantes_cie9_total = sorted(list(resultado_cie9_total["faltantes_main"]))[:30]

print("Ejemplos de códigos del procedimiento principal no encontrados en CIE-9:")
print(faltantes_cie9_principal)

print("\nEjemplos de códigos de cualquier procedimiento no encontrados en CIE-9:")
print(faltantes_cie9_total)

## 8C — Tablas GRD y auxiliares de clasificación

Estas bases no se auditan solo por cobertura, sino también por riesgo metodológico.

### Qué buscamos
- si contienen atributos clínicos útiles
- si contienen la lógica del target
- si exponen leakage
- si son utilizables antes del modelado o solo como referencia analítica

In [ ]:
# =========================
# FASE 8C - CELDA 13
# Exploración básica de tabla GRD
# =========================

# Ajusta el nombre si tu variable no se llama exactamente así
auxiliares_disponibles = [v for v in globals() if isinstance(globals()[v], pd.DataFrame)]
print("DataFrames disponibles:")
print(auxiliares_disponibles)

In [ ]:
# =========================
# FASE 8C - CELDA 14
# Explorar tablas GRD si existen
# =========================

# Reemplaza por el nombre real si corresponde
# Ejemplo: ir_grd, tablas_grd, grd_fonasa, etc.

for nombre_df in auxiliares_disponibles:
    if "grd" in nombre_df.lower() or "fonasa" in nombre_df.lower():
        print("=" * 100)
        print("Explorando:", nombre_df)
        print("=" * 100)
        df_tmp = globals()[nombre_df]
        print("Shape:", df_tmp.shape)
        print("Columnas:", df_tmp.columns.tolist())
        display(df_tmp.head(5))

## Evaluación analítica obligatoria de cada auxiliar

A partir de los resultados anteriores, para cada base se debe responder explícitamente:

- si de verdad enriquece,
- si aporta contexto clínico útil,
- si introduce ruido,
- si expone leakage,
- y si requiere agregación previa antes del merge.

In [ ]:
# =========================
# FASE 8 - CELDA 15
# Plantilla de conclusiones por auxiliar
# =========================

conclusiones_auxiliares = {
    "CIE-10": {
        "representa": "Diccionario de diagnósticos clínicos",
        "aporta": "Descripción y potencial jerarquía clínica",
        "llave": "Código",
        "enriquece": None,
        "contexto_clinico_util": None,
        "introduce_ruido": None,
        "expone_leakage": None,
        "requiere_agregacion_previa": None,
        "observaciones": ""
    },
    "CIE-9": {
        "representa": "Diccionario de procedimientos",
        "aporta": "Descripción y potencial jerarquía de procedimientos",
        "llave": "Código",
        "enriquece": None,
        "contexto_clinico_util": None,
        "introduce_ruido": None,
        "expone_leakage": None,
        "requiere_agregacion_previa": None,
        "observaciones": ""
    },
    "Tablas_GRD": {
        "representa": "Clasificación/atributos asociados a GRD",
        "aporta": "Referencia analítica del target",
        "llave": "Depende de la tabla",
        "enriquece": None,
        "contexto_clinico_util": None,
        "introduce_ruido": None,
        "expone_leakage": None,
        "requiere_agregacion_previa": None,
        "observaciones": ""
    }
}

conclusiones_auxiliares

## Cierre de la fase

El objetivo de esta fase no es decidir aún el merge final, sino dejar evidencia clara sobre:

- cuáles auxiliares sí conectan con la base principal,
- cuáles tienen calidad suficiente,
- cuáles agregan contexto útil,
- cuáles pueden introducir ruido,
- y cuáles no deben usarse por riesgo de leakage.

In [ ]:
# =========================
# FASE 8 - CELDA 16
# Resumen ejecutivo cuantitativo
# =========================

resumen_fase_8 = pd.DataFrame([
    {
        "auxiliar": "CIE-10 vs diag principal",
        "duplicados_llave": resultado_cie10_principal["duplicados_llave"],
        "max_registros_por_llave": resultado_cie10_principal["max_registros_por_llave"],
        "cobertura_pct": resultado_cie10_principal["cobertura_pct"]
    },
    {
        "auxiliar": "CIE-10 vs todos los diag",
        "duplicados_llave": resultado_cie10_total["duplicados_llave"],
        "max_registros_por_llave": resultado_cie10_total["max_registros_por_llave"],
        "cobertura_pct": resultado_cie10_total["cobertura_pct"]
    },
    {
        "auxiliar": "CIE-9 vs proc principal",
        "duplicados_llave": resultado_cie9_principal["duplicados_llave"],
        "max_registros_por_llave": resultado_cie9_principal["max_registros_por_llave"],
        "cobertura_pct": resultado_cie9_principal["cobertura_pct"]
    },
    {
        "auxiliar": "CIE-9 vs todos los proc",
        "duplicados_llave": resultado_cie9_total["duplicados_llave"],
        "max_registros_por_llave": resultado_cie9_total["max_registros_por_llave"],
        "cobertura_pct": resultado_cie9_total["cobertura_pct"]
    }
])

resumen_fase_8

# FASE 9 — Diseño de integración y merge

En esta fase se diseña y ejecuta la integración entre la base principal y las bases auxiliares.

Esta fase es previa al feature engineering y no debe improvisarse.

Decisiones que deben quedar explícitas:

- con qué llave se une cada auxiliar,
- qué columnas deben normalizarse antes del merge,
- si el merge será `left`, `inner` o si requiere agregación previa,
- qué hacer cuando una auxiliar tenga múltiples filas por llave,
- cómo medir la cobertura lograda,
- cómo verificar que no se duplicó accidentalmente la base principal.

El resultado esperado es un dataset enriquecido, consistente y auditado,
pero todavía no listo para modelar.

## Diseño conceptual de integración

Con base en la auditoría previa, se define el siguiente diseño:

- `CIE-10` se unirá contra el **diagnóstico principal**, usando una relación esperada 1:1.
- `CIE-9` se unirá contra el **procedimiento principal**, pero antes requiere agregación previa porque presenta múltiples filas por código.
- Las tablas GRD no se integrarán al dataset de modelado en esta fase, por riesgo de leakage.

Estrategia de merge:

- usar `left join` para preservar la base principal,
- medir cobertura antes y después,
- validar que el número de filas no cambie.

In [ ]:
# =========================
# FASE 9 - CELDA 1
# Copias de trabajo y shape base
# =========================

df_base = df_main.copy()

print("Filas base principal:", df_base.shape[0])
print("Columnas base principal:", df_base.shape[1])

# FASE 9 — Diseño de integración y merge

En esta fase se diseña y ejecuta la integración entre la base principal y las bases auxiliares.

Esta fase es previa al feature engineering y no debe improvisarse.

Aquí se definirá:

- con qué llave se une cada auxiliar,
- qué columnas deben normalizarse antes del merge,
- qué tipo de merge se utilizará,
- qué hacer cuando una auxiliar tenga múltiples filas por llave,
- cómo medir la cobertura lograda,
- cómo verificar que la base principal no fue duplicada accidentalmente.

El resultado esperado es un dataset enriquecido y auditado, pero todavía no listo para modelar.

## Diseño conceptual del merge

Según la fase anterior:

- `CIE-10` debe integrarse con los diagnósticos, porque representa diagnósticos clínicos.
- `CIE-9` debe integrarse con los procedimientos, porque representa procedimientos.
- `Tablas GRD` no se integrarán al dataset de modelado en esta fase, por riesgo de leakage.

Para mantener esta fase controlada y segura, se trabajará primero con:

- diagnóstico principal + CIE-10
- procedimiento principal + CIE-9

Esto permite enriquecer la base sin multiplicar la dimensionalidad todavía.

In [ ]:
# =========================
# FASE 9 - CELDA 1
# Copia de trabajo y verificación base
# =========================

df_base = df_main.copy()

print("Shape base principal:", df_base.shape)
print("Columnas actuales:", df_base.shape[1])

# Confirmar que las demográficas siguen en la base
print("¿Edad en años está en df_base?", "Edad en años" in df_base.columns)
print("¿Sexo (Desc) está en df_base?", "Sexo (Desc)" in df_base.columns)

## Definición de columnas clínicas de referencia

Se identifican explícitamente las columnas de diagnóstico principal y procedimiento principal que serán usadas para el merge.

In [ ]:
# =========================
# FASE 9 - CELDA 2
# Columnas base para integración
# =========================

col_diag_principal = "Diag 01 Principal (cod+des)"
col_proc_principal = "Proced 01 Principal (cod+des)"

print("Columna diagnóstico principal:", col_diag_principal)
print("Columna procedimiento principal:", col_proc_principal)

## Normalización de códigos antes del merge

Las llaves deben quedar comparables entre principal y auxiliares.

Se limpiará:

- el diagnóstico principal de la base principal,
- el procedimiento principal de la base principal,
- la llave `Código` en CIE-10,
- la llave `Código` en CIE-9.

In [ ]:
# =========================
# FASE 9 - CELDA 3
# Funciones de limpieza y normalización
# =========================

import pandas as pd
import numpy as np

def limpiar_texto(x):
    if pd.isna(x):
        return np.nan
    
    x = str(x).strip().upper()
    
    if x in ["", "-", "NAN", "NONE", "NULL"]:
        return np.nan
    
    return x

def extraer_codigo(x):
    x = limpiar_texto(x)
    if pd.isna(x):
        return np.nan
    return x.split(" ")[0]

In [ ]:
# =========================
# FASE 9 - CELDA 4
# Construcción de llaves limpias
# =========================

df_base["diag_principal_cod"] = df_base[col_diag_principal].apply(extraer_codigo)
df_base["proc_principal_cod"] = df_base[col_proc_principal].apply(extraer_codigo)

cie10_merge = cie10.copy()
cie9_merge = cie9.copy()

cie10_merge["Código"] = cie10_merge["Código"].apply(limpiar_texto)
cie9_merge["Código"] = cie9_merge["Código"].apply(limpiar_texto)

display(
    df_base[[col_diag_principal, "diag_principal_cod", col_proc_principal, "proc_principal_cod"]].head(10)
)

## Selección de columnas utilizables antes del merge

No todas las columnas auxiliares deben integrarse.

En esta fase se seleccionarán solo columnas útiles y razonables para enriquecer clínicamente la base principal.

In [ ]:
# =========================
# FASE 9 - CELDA 5
# Columnas auxiliares utilizables
# =========================

cols_cie10_usables = [c for c in ["Código", "Descripción", "Categoría", "Capítulo"] if c in cie10_merge.columns]
cols_cie9_usables = [c for c in ["Código", "Descripción", "Categoría", "Capítulo"] if c in cie9_merge.columns]

cie10_merge = cie10_merge[cols_cie10_usables].copy()
cie9_merge = cie9_merge[cols_cie9_usables].copy()

print("Columnas usables CIE-10:", cie10_merge.columns.tolist())
print("Columnas usables CIE-9:", cie9_merge.columns.tolist())

## Revisión de relación por llave antes del merge

Antes de unir, se valida si la auxiliar tiene una fila por llave o múltiples filas por llave.

Esto define si el merge puede ser directo o si requiere agregación previa.

In [ ]:
# =========================
# FASE 9 - CELDA 6
# Relación por llave en auxiliares
# =========================

print("CIE-10 duplicados por llave:", cie10_merge["Código"].duplicated().sum())
print("CIE-9 duplicados por llave:", cie9_merge["Código"].duplicated().sum())

print("\nMáximo registros por llave en CIE-10:", cie10_merge["Código"].value_counts().max())
print("Máximo registros por llave en CIE-9:", cie9_merge["Código"].value_counts().max())

## Agregación previa de CIE-9

Como CIE-9 presenta múltiples filas por código, se construirá una versión agregada a una sola fila por llave antes del merge.

Esto evita duplicación accidental de la base principal.

In [ ]:
# =========================
# FASE 9 - CELDA 7
# Agregación previa de CIE-9
# =========================

def primer_no_nulo(series):
    series = series.dropna()
    if len(series) == 0:
        return np.nan
    return series.iloc[0]

cie9_merge_agregado = (
    cie9_merge
    .groupby("Código", as_index=False)
    .agg({
        col: primer_no_nulo for col in cie9_merge.columns if col != "Código"
    })
)

print("Shape CIE-9 original:", cie9_merge.shape)
print("Shape CIE-9 agregado:", cie9_merge_agregado.shape)
print("Duplicados por llave en CIE-9 agregado:", cie9_merge_agregado["Código"].duplicated().sum())

## Cobertura previa al merge

Antes de integrar, se calcula la cobertura teórica de las llaves.

Esto servirá para contrastar la cobertura real observada post-merge.

In [ ]:
# =========================
# FASE 9 - CELDA 8
# Cobertura previa al merge
# =========================

diag_main_keys = set(df_base["diag_principal_cod"].dropna())
proc_main_keys = set(df_base["proc_principal_cod"].dropna())

diag_aux_keys = set(cie10_merge["Código"].dropna())
proc_aux_keys = set(cie9_merge_agregado["Código"].dropna())

cov_diag_pre = len(diag_main_keys & diag_aux_keys) / len(diag_main_keys) * 100 if len(diag_main_keys) > 0 else np.nan
cov_proc_pre = len(proc_main_keys & proc_aux_keys) / len(proc_main_keys) * 100 if len(proc_main_keys) > 0 else np.nan

print(f"Cobertura previa CIE-10 vs diagnóstico principal: {cov_diag_pre:.2f}%")
print(f"Cobertura previa CIE-9 vs procedimiento principal: {cov_proc_pre:.2f}%")

## Merge de CIE-10 con diagnóstico principal

Se aplica un `left join` para preservar toda la base principal.

Las columnas integradas se renombran con prefijo `diag_principal_`.

In [ ]:
# =========================
# FASE 9 - CELDA 9
# Merge CIE-10 con diagnóstico principal
# =========================

cie10_diag = cie10_merge.rename(columns={
    "Código": "diag_principal_cod",
    "Descripción": "diag_principal_desc_cie10",
    "Categoría": "diag_principal_categoria_cie10",
    "Capítulo": "diag_principal_capitulo_cie10"
})

filas_antes_1 = df_base.shape[0]
cols_antes_1 = df_base.shape[1]

df_merge_1 = df_base.merge(
    cie10_diag,
    on="diag_principal_cod",
    how="left"
)

print("Filas antes:", filas_antes_1)
print("Filas después:", df_merge_1.shape[0])
print("Columnas antes:", cols_antes_1)
print("Columnas después:", df_merge_1.shape[1])

## Chequeos post-merge 1

Se valida que:

- no haya cambiado el número de filas,
- no se haya duplicado la base,
- y que la cobertura real de las columnas integradas sea consistente.

In [ ]:
# =========================
# FASE 9 - CELDA 10
# Chequeos post-merge 1
# =========================

print("¿Se duplicó accidentalmente la base?", df_merge_1.shape[0] != filas_antes_1)

nulos_diag_desc = df_merge_1["diag_principal_desc_cie10"].isnull().mean() * 100
nulos_diag_cat = df_merge_1["diag_principal_categoria_cie10"].isnull().mean() * 100
nulos_diag_cap = df_merge_1["diag_principal_capitulo_cie10"].isnull().mean() * 100

print(f"% nulos nuevos en diag_principal_desc_cie10: {nulos_diag_desc:.2f}%")
print(f"% nulos nuevos en diag_principal_categoria_cie10: {nulos_diag_cat:.2f}%")
print(f"% nulos nuevos en diag_principal_capitulo_cie10: {nulos_diag_cap:.2f}%")

## Merge de CIE-9 agregado con procedimiento principal

Se aplica un `left join` sobre el procedimiento principal.

Las columnas integradas se renombran con prefijo `proc_principal_`.

In [ ]:
# =========================
# FASE 9 - CELDA 11
# Merge CIE-9 agregado con procedimiento principal
# =========================

cie9_proc = cie9_merge_agregado.rename(columns={
    "Código": "proc_principal_cod",
    "Descripción": "proc_principal_desc_cie9",
    "Categoría": "proc_principal_categoria_cie9",
    "Capítulo": "proc_principal_capitulo_cie9"
})

filas_antes_2 = df_merge_1.shape[0]
cols_antes_2 = df_merge_1.shape[1]

df_merge_2 = df_merge_1.merge(
    cie9_proc,
    on="proc_principal_cod",
    how="left"
)

print("Filas antes:", filas_antes_2)
print("Filas después:", df_merge_2.shape[0])
print("Columnas antes:", cols_antes_2)
print("Columnas después:", df_merge_2.shape[1])

## Chequeos post-merge 2

Se valida nuevamente:

- preservación del número de filas,
- ausencia de duplicación,
- cobertura real de las columnas nuevas,
- nulos creados por falta de match.

In [ ]:
# =========================
# FASE 9 - CELDA 12
# Chequeos post-merge 2
# =========================

print("¿Se duplicó accidentalmente la base?", df_merge_2.shape[0] != filas_antes_2)

nulos_proc_desc = df_merge_2["proc_principal_desc_cie9"].isnull().mean() * 100
nulos_proc_cat = df_merge_2["proc_principal_categoria_cie9"].isnull().mean() * 100
nulos_proc_cap = df_merge_2["proc_principal_capitulo_cie9"].isnull().mean() * 100

print(f"% nulos nuevos en proc_principal_desc_cie9: {nulos_proc_desc:.2f}%")
print(f"% nulos nuevos en proc_principal_categoria_cie9: {nulos_proc_cat:.2f}%")
print(f"% nulos nuevos en proc_principal_capitulo_cie9: {nulos_proc_cap:.2f}%")

## Validación explícita de columnas demográficas

Antes de cerrar la fase, se verifica explícitamente que las variables demográficas sigan presentes en el dataset enriquecido.

In [ ]:
# =========================
# FASE 9 - CELDA 13
# Verificación demográfica
# =========================

print("¿Edad en años está en df_merge_2?", "Edad en años" in df_merge_2.columns)
print("¿Sexo (Desc) está en df_merge_2?", "Sexo (Desc)" in df_merge_2.columns)

print([c for c in df_merge_2.columns if "edad" in c.lower() or "sexo" in c.lower()])

## Resumen cuantitativo del merge

Se resume el efecto total de la integración sobre filas y columnas.

In [ ]:
# =========================
# FASE 9 - CELDA 14
# Resumen cuantitativo
# =========================

resumen_merge = pd.DataFrame([
    {
        "etapa": "base_original",
        "filas": df_base.shape[0],
        "columnas": df_base.shape[1]
    },
    {
        "etapa": "post_merge_cie10",
        "filas": df_merge_1.shape[0],
        "columnas": df_merge_1.shape[1]
    },
    {
        "etapa": "post_merge_cie10_cie9",
        "filas": df_merge_2.shape[0],
        "columnas": df_merge_2.shape[1]
    }
])

resumen_merge

## Cobertura real de columnas traídas

Se calcula la cobertura observada de las columnas nuevas integradas.

In [ ]:
# =========================
# FASE 9 - CELDA 15
# Cobertura real post-merge
# =========================

cobertura_columnas_traidas = pd.Series({
    "diag_principal_desc_cie10": 100 - df_merge_2["diag_principal_desc_cie10"].isnull().mean() * 100,
    "diag_principal_categoria_cie10": 100 - df_merge_2["diag_principal_categoria_cie10"].isnull().mean() * 100,
    "diag_principal_capitulo_cie10": 100 - df_merge_2["diag_principal_capitulo_cie10"].isnull().mean() * 100,
    "proc_principal_desc_cie9": 100 - df_merge_2["proc_principal_desc_cie9"].isnull().mean() * 100,
    "proc_principal_categoria_cie9": 100 - df_merge_2["proc_principal_categoria_cie9"].isnull().mean() * 100,
    "proc_principal_capitulo_cie9": 100 - df_merge_2["proc_principal_capitulo_cie9"].isnull().mean() * 100
}).sort_values(ascending=False)

cobertura_columnas_traidas

## Resultado de la fase

El dataset `df_merge_2` representa una versión enriquecida de la base principal:

- conserva todas las filas originales,
- incorpora contexto clínico del diagnóstico principal,
- incorpora contexto procedimental del procedimiento principal,
- y mantiene trazabilidad del proceso de integración.

Este dataset todavía no está listo para modelar, pero sí queda listo para la siguiente fase de selección de variables y feature engineering.

In [ ]:
# =========================
# FASE 9 - CELDA 16
# Vista final del dataset enriquecido
# =========================

print("Shape final del dataset enriquecido:", df_merge_2.shape)
display(df_merge_2.head(5))

# FASE 10 — Selección inicial de variables

Antes de aplicar transformaciones o feature engineering, se realiza una selección inicial de variables.

El objetivo es:

- eliminar variables irrelevantes o peligrosas para el modelo,
- conservar variables con potencial predictivo,
- preparar una base coherente para la construcción de features.

Esta fase no transforma datos, solo filtra.

## Diagnóstico estructural de variables

Primero se revisa la estructura del dataset enriquecido para identificar:

- porcentaje de nulos,
- cardinalidad,
- tipo de dato,
- posibles columnas problemáticas.

In [ ]:
# =========================
# FASE 10 - CELDA 1
# Diagnóstico estructural de variables
# =========================

df_model_base = df_merge_2.copy()

resumen_vars = pd.DataFrame({
    "columna": df_model_base.columns,
    "nulos_%": df_model_base.isnull().mean() * 100,
    "unicos": df_model_base.nunique(),
    "dtype": df_model_base.dtypes.astype(str)
}).sort_values(by="nulos_%", ascending=False)

print("Shape inicial:", df_model_base.shape)
display(resumen_vars.head(20))

## Eliminación de variables irrelevantes

Se eliminan:

- IDs o identificadores técnicos,
- descripciones largas redundantes,
- columnas técnicas de auditoría.

Importante: en esta fase NO se eliminan los diagnósticos ni procedimientos secundarios,
porque serán materia prima para el feature engineering.

In [ ]:
# =========================
# FASE 10 - CELDA 2
# Eliminación dirigida de variables irrelevantes
# =========================

cols_drop = []

# IDs típicos
cols_drop += [c for c in df_model_base.columns if "id" in c.lower()]

# textos largos redundantes
cols_drop += [
    "diag_principal_desc_cie10",
    "proc_principal_desc_cie9"
]

# columnas técnicas
cols_drop += [
    "nulls_row",
    "nulls_pct_row"
]

cols_drop = list(set([c for c in cols_drop if c in df_model_base.columns]))

print("Columnas a eliminar:", cols_drop)

df_model_base = df_model_base.drop(columns=cols_drop)

print("Shape después de eliminación:", df_model_base.shape)

## Selección explícita de variables a conservar

Se conservan:

### Clínicas
- diagnóstico principal
- diagnósticos secundarios
- procedimiento principal
- procedimientos secundarios

### Enriquecidas (auxiliares)
- capítulo diagnóstico
- categoría diagnóstica
- capítulo procedimiento
- categoría procedimiento

### Demográficas
- edad
- sexo

In [ ]:
# =========================
# FASE 10 - CELDA 3
# Selección explícita de variables útiles
# =========================

cols_keep = []

# Target
cols_keep += ["GRD"]

# Diagnóstico principal
cols_keep += [
    "diag_principal_cod",
    "diag_principal_categoria_cie10",
    "diag_principal_capitulo_cie10"
]

# Procedimiento principal
cols_keep += [
    "proc_principal_cod",
    "proc_principal_categoria_cie9",
    "proc_principal_capitulo_cie9"
]

# Diagnósticos secundarios (todos los slots)
cols_keep += [c for c in df_model_base.columns if "Diag " in c and "Principal" not in c]

# Procedimientos secundarios (todos los slots)
cols_keep += [c for c in df_model_base.columns if "Proced " in c and "Principal" not in c]

# Variables demográficas: nombres reales
cols_keep += [c for c in ["Edad en años", "Sexo (Desc)"] if c in df_model_base.columns]

# Mantener solo existentes y sin duplicados
cols_keep = list(dict.fromkeys([c for c in cols_keep if c in df_model_base.columns]))

df_model_base = df_model_base[cols_keep].copy()

print("Shape final tras selección:", df_model_base.shape)

## Eliminación de columnas constantes o muy nulas

Se eliminan columnas que:

- tienen un solo valor único,
- o tienen más de un umbral alto de nulos (por ejemplo, >95%).

In [ ]:
# =========================
# FASE 10 - CELDA 4
# Eliminación de columnas constantes o muy nulas
# =========================

cols_const = [c for c in df_model_base.columns if df_model_base[c].nunique(dropna=False) <= 1]
cols_muy_nulas = [c for c in df_model_base.columns if df_model_base[c].isnull().mean() > 0.95]

print("Constantes:", cols_const)
print("Muy nulas:", cols_muy_nulas)

df_model_base = df_model_base.drop(columns=cols_const + cols_muy_nulas)

print("Shape final limpio:", df_model_base.shape)

## Validación final de la fase

Se comprueba que:

- las variables demográficas siguen presentes,
- los secundarios siguen presentes,
- la base quedó lista para feature engineering.

In [ ]:
# =========================
# FASE 10 - CELDA 5
# Validación final
# =========================

print("Edad en años:", "Edad en años" in df_model_base.columns)
print("Sexo (Desc):", "Sexo (Desc)" in df_model_base.columns)

print("Hay diagnósticos secundarios:",
      any("Diag " in c and "Principal" not in c for c in df_model_base.columns))

print("Hay procedimientos secundarios:",
      any("Proced " in c and "Principal" not in c for c in df_model_base.columns))

print("\nDuplicados:", df_model_base.duplicated().sum())

print("\nDataset listo para Feature Engineering:", df_model_base.shape)
display(df_model_base.head())

# FASE 11 — Feature engineering

En esta fase se construyen variables derivadas a partir de la base seleccionada en la Fase 10.

El objetivo es transformar la información clínica y demográfica en features más útiles para modelado.

Aquí se trabajará sobre:

- limpieza de códigos,
- estandarización de categorías,
- agrupación de categorías raras,
- conteos por episodio,
- indicadores de presencia/ausencia,
- agregaciones clínicas,
- discretizaciones razonables,
- transformaciones simples de variables sesgadas.

El resultado de esta fase será un dataset enriquecido y representativo del episodio clínico,
pero todavía no modelado.

In [ ]:
df_fe = df_model_base.copy()

print("Shape inicial:", df_fe.shape)

In [ ]:
def limpiar_texto(x):
    if pd.isna(x):
        return np.nan
    x = str(x).strip().upper()
    if x in ["", "-", "NAN", "NONE", "NULL"]:
        return np.nan
    return x

def extraer_codigo(x):
    x = limpiar_texto(x)
    if pd.isna(x):
        return np.nan
    return x.split(" ")[0]

In [ ]:
diag_cols = [c for c in df_fe.columns if c.startswith("Diag")]
proc_cols = [c for c in df_fe.columns if c.startswith("Proced")]

print(len(diag_cols), "columnas de diagnóstico")
print(len(proc_cols), "columnas de procedimientos")

In [ ]:
for col in diag_cols:
    df_fe[col + "_cod"] = df_fe[col].apply(extraer_codigo)

for col in proc_cols:
    df_fe[col + "_cod"] = df_fe[col].apply(extraer_codigo)

In [ ]:
diag_cod_cols = [c for c in df_fe.columns if "Diag" in c and c.endswith("_cod")]
proc_cod_cols = [c for c in df_fe.columns if "Proced" in c and c.endswith("_cod")]

df_fe["n_diagnosticos"] = df_fe[diag_cod_cols].notnull().sum(axis=1)
df_fe["n_diagnosticos_unicos"] = df_fe[diag_cod_cols].apply(lambda x: len(set(x.dropna())), axis=1)

df_fe["n_procedimientos"] = df_fe[proc_cod_cols].notnull().sum(axis=1)
df_fe["n_procedimientos_unicos"] = df_fe[proc_cod_cols].apply(lambda x: len(set(x.dropna())), axis=1)

In [ ]:
df_fe["tiene_diag_sec"] = (df_fe["n_diagnosticos"] > 1).astype(int)
df_fe["tiene_proc"] = (df_fe["n_procedimientos"] > 0).astype(int)

df_fe["diag_alta_carga"] = (df_fe["n_diagnosticos"] >= 5).astype(int)
df_fe["proc_alta_carga"] = (df_fe["n_procedimientos"] >= 3).astype(int)

df_fe["caso_complejo"] = (
    (df_fe["diag_alta_carga"] == 1) |
    (df_fe["proc_alta_carga"] == 1)
).astype(int)

In [ ]:
df_fe["carga_total"] = df_fe["n_diagnosticos"] + df_fe["n_procedimientos"]
df_fe["interaccion_diag_proc"] = df_fe["n_diagnosticos"] * df_fe["n_procedimientos"]

In [ ]:
df_fe["ratio_diag"] = df_fe["n_diagnosticos_unicos"] / df_fe["n_diagnosticos"].replace(0, np.nan)
df_fe["ratio_proc"] = df_fe["n_procedimientos_unicos"] / df_fe["n_procedimientos"].replace(0, np.nan)
df_fe["proc_por_diag"] = df_fe["n_procedimientos"] / df_fe["n_diagnosticos"].replace(0, np.nan)

In [ ]:
df_fe["edad"] = pd.to_numeric(df_fe["Edad en años"], errors="coerce")

df_fe["grupo_edad"] = pd.cut(
    df_fe["edad"],
    bins=[-1, 0, 14, 44, 64, np.inf],
    labels=["RN", "PEDIATRICO", "ADULTO_JOVEN", "ADULTO", "ADULTO_MAYOR"]
)

df_fe["sexo_bin"] = df_fe["Sexo (Desc)"].map({
    "HOMBRE": 0,
    "MUJER": 1,
    "Hombre": 0,
    "Mujer": 1
})

In [ ]:
def agrupar_raras(serie, min_freq=0.01):
    freq = serie.value_counts(normalize=True)
    raras = freq[freq < min_freq].index
    return serie.replace(raras, "OTRAS")

df_fe["diag_cat_agrup"] = agrupar_raras(df_fe["diag_principal_categoria_cie10"])
df_fe["proc_cat_agrup"] = agrupar_raras(df_fe["proc_principal_categoria_cie9"])

In [ ]:
df_fe["log_n_diag"] = np.log1p(df_fe["n_diagnosticos"])
df_fe["log_n_proc"] = np.log1p(df_fe["n_procedimientos"])
df_fe["log_carga_total"] = np.log1p(df_fe["carga_total"])

In [ ]:
# SOLO eliminar texto crudo (NO eliminar estructura)

cols_texto = [
    c for c in df_fe.columns
    if ("Diag " in c or "Proced " in c) and not c.endswith("_cod")
]

df_fe = df_fe.drop(columns=cols_texto)

print("Columnas eliminadas:", len(cols_texto))
print("Shape final:", df_fe.shape)

In [ ]:
nuevas_features = [
    "n_diagnosticos",
    "n_diagnosticos_unicos",
    "n_procedimientos",
    "n_procedimientos_unicos",
    "tiene_diag_sec",
    "tiene_proc",
    "diag_alta_carga",
    "proc_alta_carga",
    "caso_complejo",
    "carga_total",
    "interaccion_diag_proc",
    "ratio_diag",
    "ratio_proc",
    "proc_por_diag",
    "edad",
    "grupo_edad",
    "sexo_bin",
    "diag_cat_agrup",
    "proc_cat_agrup",
    "log_n_diag",
    "log_n_proc",
    "log_carga_total"
]

print("Total nuevas features:", len(nuevas_features))

In [ ]:
df_fe.head()

In [ ]:
print("Shape actual:", df_fe.shape)

print("\nColumnas con cod+des:")
print([c for c in df_fe.columns if "(cod+des)" in c][:95])

print("\nColumnas _cod:")
print([c for c in df_fe.columns if c.endswith("_cod")][:95])

print("\nConteos clave:")
cols_check = [
    "n_diagnosticos",
    "n_procedimientos",
    "ratio_diag",
    "ratio_proc",
    "carga_total",
    "edad",
    "grupo_edad",
    "sexo_bin"
]
for c in cols_check:
    print(c, c in df_fe.columns)

# FASE 12 — Definición del esquema de partición

Antes del entrenamiento se define explícitamente el esquema de partición del dataset.

En este proyecto, el target `GRD` corresponde a una clasificación multiclase con fuerte desbalance y presencia de clases muy raras.

Por esta razón, no es metodológicamente correcto asumir que todas las clases pueden estratificarse de forma estable en un esquema `train / validation / test`.

En esta fase se decidirá:

- qué clases pueden participar en un split estratificado,
- qué clases deben quedar solo en entrenamiento por soporte insuficiente,
- cómo construir los conjuntos train / validation / test,
- y cómo documentar el riesgo residual de fuga o sesgo.

## Preparación del dataset para partición

Se parte desde el dataset final construido en la Fase 11 (`df_fe`).

En esta etapa todavía no se aplica encoding ni entrenamiento.

In [ ]:
# =========================
# FASE 12 - CELDA 1
# Preparación de X e y
# =========================

df_split = df_fe.copy()

target_col = "GRD"

X = df_split.drop(columns=[target_col])
y = df_split[target_col]

print("Shape dataset completo:", df_split.shape)
print("Shape X:", X.shape)
print("Shape y:", y.shape)
print("Cantidad de clases únicas en GRD:", y.nunique())

## Diagnóstico del soporte por clase

Se revisa cuántas observaciones tiene cada clase del target.

Esto permite identificar clases que no pueden participar en una partición estratificada 70 / 15 / 15 de manera estable.

In [ ]:
# =========================
# FASE 12 - CELDA 2
# Frecuencia por clase
# =========================

freq_target = y.value_counts().sort_values()

print("Cantidad de clases con 1 observación:", (freq_target == 1).sum())
print("Cantidad de clases con 2 observaciones:", (freq_target == 2).sum())
print("Cantidad de clases con 3 o menos observaciones:", (freq_target <= 3).sum())
print("Cantidad de clases con 5 o menos observaciones:", (freq_target <= 5).sum())
print("Cantidad de clases con 6 o menos observaciones:", (freq_target <= 6).sum())

display(freq_target.head(20))

## Definición de clases aptas para estratificación

Como el esquema objetivo es `70 / 15 / 15`, se utilizará una regla práctica:

- clases con **7 o más observaciones** → aptas para estratificación,
- clases con **menos de 7 observaciones** → demasiado raras para validation/test estables.

Las clases raras se conservarán en train, pero no se exigirán en validation ni test.

In [ ]:
# =========================
# FASE 12 - CELDA 3
# Umbral de clases raras
# =========================

min_casos_para_split = 7

clases_frecuentes = freq_target[freq_target >= min_casos_para_split].index
clases_raras = freq_target[freq_target < min_casos_para_split].index

print("Umbral mínimo para split estable:", min_casos_para_split)
print("Cantidad de clases frecuentes:", len(clases_frecuentes))
print("Cantidad de clases raras:", len(clases_raras))
print("Observaciones en clases raras:", y.isin(clases_raras).sum())

## Separación entre bloque estratificable y bloque raro

Se separa el dataset en dos partes:

- bloque frecuente: puede dividirse con estratificación,
- bloque raro: se reservará inicialmente para entrenamiento.

In [ ]:
# =========================
# FASE 12 - CELDA 4
# Separación de bloques
# =========================

mask_frecuentes = y.isin(clases_frecuentes)
mask_raras = y.isin(clases_raras)

X_freq = X.loc[mask_frecuentes].copy()
y_freq = y.loc[mask_frecuentes].copy()

X_raras = X.loc[mask_raras].copy()
y_raras = y.loc[mask_raras].copy()

print("Shape bloque frecuente:", X_freq.shape)
print("Shape bloque raro:", X_raras.shape)

## Definición del esquema base de partición

Sobre el bloque frecuente se aplicará un split estratificado:

- 70% train
- 15% validation
- 15% test

El bloque raro se añadirá posteriormente al conjunto de entrenamiento.

In [ ]:
# =========================
# FASE 12 - CELDA 5
# Parámetros del split
# =========================

from sklearn.model_selection import train_test_split

SEED = 42

train_size = 0.70
val_size = 0.15
test_size = 0.15

print("Semilla:", SEED)
print("Train:", train_size)
print("Validation:", val_size)
print("Test:", test_size)

## Split train vs temporal en bloque frecuente

Se separa primero el conjunto de entrenamiento respecto del bloque temporal.

In [ ]:
# =========================
# FASE 12 - CELDA 6
# Split Train vs Temp
# =========================

X_train_freq, X_temp, y_train_freq, y_temp = train_test_split(
    X_freq,
    y_freq,
    test_size=(1 - train_size),
    random_state=SEED,
    stratify=y_freq
)

print("Shape X_train_freq:", X_train_freq.shape)
print("Shape X_temp:", X_temp.shape)
print("Shape y_train_freq:", y_train_freq.shape)
print("Shape y_temp:", y_temp.shape)

## Split validation vs test en bloque frecuente

Luego, el bloque temporal se divide en validation y test.

In [ ]:
# =========================
# FASE 12 - CELDA 7
# Split Validation vs Test
# =========================

val_ratio_ajustado = val_size / (val_size + test_size)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=(1 - val_ratio_ajustado),
    random_state=SEED,
    stratify=y_temp
)

print("Shape X_val:", X_val.shape)
print("Shape X_test:", X_test.shape)
print("Shape y_val:", y_val.shape)
print("Shape y_test:", y_test.shape)

## Incorporación de clases raras al entrenamiento

Las observaciones correspondientes a clases raras se agregan al conjunto de entrenamiento.

Esto permite que el modelo vea esas clases durante el aprendizaje,
aunque no se exija una evaluación estable sobre ellas en validation y test.

In [ ]:
# =========================
# FASE 12 - CELDA 8
# Añadir clases raras a train
# =========================

X_train = pd.concat([X_train_freq, X_raras], axis=0)
y_train = pd.concat([y_train_freq, y_raras], axis=0)

print("Shape final X_train:", X_train.shape)
print("Shape final y_train:", y_train.shape)
print("Clases raras añadidas a train:", y_raras.nunique())

## Verificación de tamaños finales

Se revisa la proporción final de cada subset respecto al dataset completo.

In [ ]:
# =========================
# FASE 12 - CELDA 9
# Verificación de proporciones
# =========================

n_total = len(df_split)

resumen_split = pd.DataFrame({
    "subset": ["train", "validation", "test"],
    "n_filas": [len(X_train), len(X_val), len(X_test)]
})

resumen_split["proporcion"] = resumen_split["n_filas"] / n_total

display(resumen_split)

## Verificación de la distribución del target

Se compara la distribución del target en el total y en cada subset.

En validation y test solo deberían aparecer clases frecuentes.

In [ ]:
# =========================
# FASE 12 - CELDA 10
# Distribución por subset
# =========================

def resumen_target(y_subset, nombre, top_n=10):
    tabla = y_subset.value_counts(normalize=True).head(top_n) * 100
    return pd.DataFrame({
        "subset": nombre,
        "GRD": tabla.index,
        "porcentaje": tabla.values
    })

dist_total = resumen_target(y, "total")
dist_train = resumen_target(y_train, "train")
dist_val = resumen_target(y_val, "validation")
dist_test = resumen_target(y_test, "test")

display(pd.concat([dist_total, dist_train, dist_val, dist_test], axis=0))

## Verificación de presencia de clases raras

Se comprueba explícitamente que las clases raras quedaron solo en entrenamiento.

In [ ]:
# =========================
# FASE 12 - CELDA 11
# Clases raras por subset
# =========================

raras_en_train = y_train.isin(clases_raras).sum()
raras_en_val = y_val.isin(clases_raras).sum()
raras_en_test = y_test.isin(clases_raras).sum()

print("Observaciones de clases raras en train:", raras_en_train)
print("Observaciones de clases raras en validation:", raras_en_val)
print("Observaciones de clases raras en test:", raras_en_test)

## Revisión de intersecciones entre subsets

Se valida que train, validation y test no compartan filas.

In [ ]:
# =========================
# FASE 12 - CELDA 12
# Intersecciones entre subsets
# =========================

idx_train = set(X_train.index)
idx_val = set(X_val.index)
idx_test = set(X_test.index)

print("Intersección train-val:", len(idx_train & idx_val))
print("Intersección train-test:", len(idx_train & idx_test))
print("Intersección val-test:", len(idx_val & idx_test))

## Revisión de duplicados completos dentro de cada subset

Se documenta la presencia de duplicados completos dentro de cada conjunto.

In [ ]:
# =========================
# FASE 12 - CELDA 13
# Duplicados por subset
# =========================

print("Duplicados completos en X_train:", X_train.duplicated().sum())
print("Duplicados completos en X_val:", X_val.duplicated().sum())
print("Duplicados completos en X_test:", X_test.duplicated().sum())

## Decisión sobre validación cruzada

En esta etapa no se aplicará CV todavía.

Primero se construirá un baseline con este esquema simple y trazable.
La CV podrá incorporarse después para comparación de modelos y ajuste fino.

In [ ]:
# =========================
# FASE 12 - CELDA 14
# Decisión metodológica sobre CV
# =========================

usar_cv_inicial = False

print("¿Se usará validación cruzada en esta etapa inicial?:", usar_cv_inicial)

## Resumen metodológico de la partición

Con base en el análisis realizado, el esquema de partición definido es:

- clasificación multiclase,
- split por fila/episodio,
- estratificación sobre clases con soporte suficiente,
- clases raras reservadas a entrenamiento,
- esquema aproximado 70 / 15 / 15,
- sin CV inicial,
- con advertencia metodológica sobre la ausencia de identificador confiable de paciente.

In [ ]:
# =========================
# FASE 12 - CELDA 15
# Resumen final de la fase
# =========================

decision_split = {
    "tipo_problema": "clasificacion_multiclase",
    "split_aprox": "70_15_15",
    "estratificacion": True,
    "variable_estratificacion": "GRD",
    "umbral_clases_frecuentes": min_casos_para_split,
    "clases_raras_solo_train": True,
    "unidad_split": "fila/episodio",
    "cv_inicial": False,
    "riesgo_duplicados": int(df_split.duplicated().sum()),
    "comentario": "No se dispone de identificador confiable de paciente; las clases raras se reservan a entrenamiento."
}

decision_split

## Resultado de la fase

La partición quedó definida de forma explícita, honesta y compatible con la estructura real del target.

Esto deja preparado el proyecto para pasar a la siguiente etapa:
codificación de variables y construcción del baseline de modelado.

# FASE 13 — Preparación para modelado

En esta fase se deja preparado el dataset para entrenar modelos de clasificación.

Aquí se definen explícitamente:

- variables que entrarán al baseline,
- estrategia de encoding,
- scaling cuando corresponde,
- construcción de pipelines,
- tratamiento del desbalance,
- y selección de modelos baseline.

Dado que este proyecto corresponde a una clasificación multiclase con fuerte desbalance y alta cardinalidad clínica, la preparación para modelado no puede hacerse de manera automática.

La meta de esta fase no es maximizar rendimiento todavía, sino construir una base estable, reproducible y metodológicamente sana para comenzar a modelar.

## Punto de partida

Se parte desde los subsets definidos en la Fase 12:

- `X_train`, `y_train`
- `X_val`, `y_val`
- `X_test`, `y_test`

y desde la versión final del dataset con feature engineering (`df_fe`).

En esta fase no se entrenará aún el modelo final:
primero se dejará todo listo para hacerlo bien.

In [ ]:
# =========================
# FASE 13 - CELDA 1
# Verificación de subsets
# =========================

print("Shape X_train:", X_train.shape)
print("Shape y_train:", y_train.shape)

print("Shape X_val:", X_val.shape)
print("Shape y_val:", y_val.shape)

print("Shape X_test:", X_test.shape)
print("Shape y_test:", y_test.shape)

## Revisión de la estructura actual del baseline

Antes de decidir encoding y scaling, se revisan las columnas disponibles y se separan por tipo:

- numéricas,
- binarias,
- categóricas controladas,
- alta cardinalidad excluida temporalmente.

In [ ]:
# =========================
# FASE 13 - CELDA 2
# Definición de columnas para baseline
# =========================

num_cols = [
    "edad",
    "n_diagnosticos",
    "n_diagnosticos_unicos",
    "n_procedimientos",
    "n_procedimientos_unicos",
    "ratio_diag",
    "ratio_proc",
    "proc_por_diag",
    "carga_total",
    "interaccion_diag_proc",
    "log_carga_total"
]

bin_cols = [
    "sexo_bin",
    "diag_alta_carga",
    "proc_alta_carga",
    "caso_complejo"
]

cat_cols = [
    "grupo_edad",
    "diag_principal_categoria_cie10_agrupada",
    "diag_principal_capitulo_cie10",
    "proc_principal_categoria_cie9_agrupada",
    "proc_principal_capitulo_cie9"
]

# Mantener solo columnas existentes
num_cols = [c for c in num_cols if c in X_train.columns]
bin_cols = [c for c in bin_cols if c in X_train.columns]
cat_cols = [c for c in cat_cols if c in X_train.columns]

print("Numéricas:", len(num_cols))
print(num_cols)

print("\nBinarias:", len(bin_cols))
print(bin_cols)

print("\nCategóricas:", len(cat_cols))
print(cat_cols)

## Variables excluidas temporalmente del baseline

Las variables clínicas de alta cardinalidad no se incorporarán todavía al baseline inicial.

Esto incluye:

- códigos diagnósticos específicos,
- códigos procedimentales específicos,
- y todos los slots clínicos `_cod`.

La razón no es que sean inútiles, sino que requieren una estrategia distinta
(frequency encoding, hashing, target encoding controlado o modelos especializados).

Para el baseline inicial conviene privilegiar estabilidad e interpretabilidad.

In [ ]:
# =========================
# FASE 13 - CELDA 3
# Variables de alta cardinalidad excluidas
# =========================

high_card_cols = [
    c for c in X_train.columns
    if c.endswith("_cod") or c in ["diag_principal_cod", "proc_principal_cod"]
]

print("Cantidad de variables de alta cardinalidad excluidas del baseline:", len(high_card_cols))
print(high_card_cols[:20])

## Construcción del subconjunto baseline

Se arma una primera versión de modelado usando solamente:

- variables numéricas,
- variables binarias,
- variables categóricas controladas.

Esto permite construir un baseline estable antes de explorar configuraciones más complejas.

In [ ]:
# =========================
# FASE 13 - CELDA 4
# Subsets para baseline
# =========================

baseline_features = num_cols + bin_cols + cat_cols
baseline_features = list(dict.fromkeys(baseline_features))

X_train_base = X_train[baseline_features].copy()
X_val_base = X_val[baseline_features].copy()
X_test_base = X_test[baseline_features].copy()

print("Cantidad de features baseline:", len(baseline_features))
print("Shape X_train_base:", X_train_base.shape)
print("Shape X_val_base:", X_val_base.shape)
print("Shape X_test_base:", X_test_base.shape)

## Revisión de nulos antes del preprocesamiento

Antes de aplicar encoding o scaling, se revisa el porcentaje de nulos en el baseline.

Esto permite justificar la estrategia de imputación dentro del pipeline.

In [ ]:
# =========================
# FASE 13 - CELDA 5
# Revisión de nulos
# =========================

nulos_train = (X_train_base.isnull().mean() * 100).sort_values(ascending=False)

print("Top columnas con más nulos en train:")
display(nulos_train.head(20))

## Revisión de cardinalidad categórica

Se revisa la cardinalidad real de las variables categóricas seleccionadas para el baseline.

Esto es importante porque condiciona la expansión del OneHotEncoder.

In [ ]:
# =========================
# FASE 13 - CELDA 6
# Cardinalidad categórica
# =========================

for c in cat_cols:
    print(c, "->", X_train_base[c].nunique(dropna=False))

## Definición del preprocesamiento

Se aplicará el siguiente tratamiento por tipo de variable:

### Numéricas
- imputación con mediana,
- escalamiento con `StandardScaler`.

### Binarias
- imputación con moda,
- sin escalamiento.

### Categóricas
- imputación con moda,
- `OneHotEncoder(handle_unknown="ignore")`.

Esto deja el pipeline listo para modelos lineales y también para modelos sensibles a escala como SVM o MLP.

In [ ]:
# =========================
# FASE 13 - CELDA 7
# Preprocesadores
# =========================

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

binary_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent"))
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, num_cols),
        ("bin", binary_transformer, bin_cols),
        ("cat", categorical_transformer, cat_cols)
    ],
    remainder="drop"
)

preprocessor

## Verificación del espacio transformado

Antes de entrenar, se revisa cuántas columnas produce realmente el preprocesador.

Esto permite verificar si el baseline sigue siendo razonable en dimensión.

In [ ]:
# =========================
# FASE 13 - CELDA 8
# Shape transformado del preprocesador
# =========================

X_train_trans = preprocessor.fit_transform(X_train_base)

print("Shape transformado de X_train_base:", X_train_trans.shape)

## Tratamiento de clases raras

En este proyecto ya se tomó una decisión importante en la Fase 12:

- las clases con soporte insuficiente se reservan inicialmente para entrenamiento,
- no se exige evaluación estable sobre ellas en validation y test.

En esta etapa no se aplicará sampling sintético.

In [ ]:
# =========================
# FASE 13 - CELDA 9
# Resumen de clases raras
# =========================

print("Cantidad de clases frecuentes:", len(clases_frecuentes))
print("Cantidad de clases raras:", len(clases_raras))
print("Observaciones raras en train:", y_train.isin(clases_raras).sum())
print("Observaciones raras en val:", y_val.isin(clases_raras).sum())
print("Observaciones raras en test:", y_test.isin(clases_raras).sum())

## Decisión sobre class weights y sampling

Dado el fuerte desbalance del problema:

- no se usará oversampling en esta etapa inicial,
- no se usará SMOTE,
- y sí se privilegiará el uso de modelos que permitan `class_weight="balanced"` o variantes equivalentes.

Esto permite construir un baseline más estable y metodológicamente defendible.

In [ ]:
# =========================
# FASE 13 - CELDA 10
# Decisión metodológica sobre balance
# =========================

usar_sampling_inicial = False
usar_class_weight = True

print("¿Se usará sampling en baseline?:", usar_sampling_inicial)
print("¿Se usará class_weight en baseline?:", usar_class_weight)

## Selección del baseline inicial

Para el primer baseline se prioriza un modelo:

- reproducible,
- compatible con multiclase,
- compatible con `class_weight`,
- y suficientemente simple como para interpretar resultados iniciales.

La primera opción será una `LogisticRegression` multiclase.

In [ ]:
# =========================
# FASE 13 - CELDA 11
# Baseline lineal propuesto
# =========================

from sklearn.linear_model import LogisticRegression

baseline_model = LogisticRegression(
    max_iter=2000,
    class_weight="balanced",
    solver="lbfgs"
)

baseline_model

## Construcción del pipeline completo del baseline

Se integra el preprocesamiento con el modelo dentro de una sola estructura reproducible.
Esto evita fuga de información y asegura consistencia entre entrenamiento y evaluación.

In [ ]:
# =========================
# FASE 13 - CELDA 12
# Pipeline baseline
# =========================

baseline_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", baseline_model)
])

baseline_pipeline

## Smoke test del pipeline

Antes de entrenar formalmente, se realiza una prueba controlada sobre una muestra pequeña.

Esto permite verificar que el pipeline corre correctamente y que no existen errores estructurales.

In [ ]:
# =========================
# FASE 13 - CELDA 13
# Smoke test
# =========================

X_train_smoke = X_train_base.head(300).copy()
y_train_smoke = y_train.head(300).copy()

baseline_pipeline.fit(X_train_smoke, y_train_smoke)

print("Smoke test completado correctamente.")

## Preparación de una segunda línea de baseline

Además del baseline lineal, conviene dejar preparado un segundo baseline no lineal,
más robusto a relaciones complejas y menos dependiente de la geometría lineal del espacio.

La segunda opción sugerida será `RandomForestClassifier`.

In [ ]:
# =========================
# FASE 13 - CELDA 14
# Segundo baseline sugerido
# =========================

from sklearn.ensemble import RandomForestClassifier

baseline_tree = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced_subsample",
    n_jobs=-1
)

baseline_tree

## Resumen metodológico de preparación para modelado

La preparación para modelado queda definida así:

- baseline inicial sobre variables controladas,
- exclusión temporal de alta cardinalidad específica,
- imputación dentro del pipeline,
- scaling solo sobre numéricas,
- OneHotEncoder para categóricas controladas,
- uso de class weights,
- sin sampling sintético en la etapa inicial,
- baseline lineal primero y baseline de árboles después.

In [ ]:
# =========================
# FASE 13 - CELDA 15
# Resumen final de la fase
# =========================

decision_model_prep = {
    "baseline_features": len(baseline_features),
    "num_cols": len(num_cols),
    "bin_cols": len(bin_cols),
    "cat_cols": len(cat_cols),
    "high_card_cols_excluidas": len(high_card_cols),
    "usar_scaling": True,
    "usar_onehot": True,
    "usar_sampling_inicial": False,
    "usar_class_weight": True,
    "baseline_1": "LogisticRegression",
    "baseline_2_sugerido": "RandomForestClassifier"
}

decision_model_prep

## Resultado de la fase

La preparación para modelado quedó definida y operacionalizada en código.

Esto deja el proyecto listo para pasar a la siguiente etapa:
entrenamiento del baseline y evaluación inicial en validation y test.