In [21]:
import pandas as pd

df = pd.read_csv("../data/raw/dataset_elpino.csv", sep=";")

In [19]:
df.shape

(14561, 68)

In [22]:
df.head()

,Diag 01 Principal (cod+des),Diag 02 Secundario (cod+des),Diag 03 Secundario (cod+des),Diag 04 Secundario (cod+des),Diag 05 Secundario (cod+des),Diag 06 Secundario (cod+des),Diag 07 Secundario (cod+des),Diag 08 Secundario (cod+des),Diag 09 Secundario (cod+des),Diag 10 Secundario (cod+des),...,Proced 24 Secundario (cod+des),Proced 25 Secundario (cod+des),Proced 26 Secundario (cod+des),Proced 27 Secundario (cod+des),Proced 28 Secundario (cod+des),Proced 29 Secundario (cod+des),Proced 30 Secundario (cod+des),Edad en años,Sexo (Desc),GRD
0,A41.8 - Otras septicemias especificadas,B37.6 - Endocarditis debida a candida (I39.8*),"I39.8 - Endocarditis, válvula no especificada,...",N10 - Nefritis tubulointersticial aguda,B96.1 - Klebsiella pneumoniae [K. pneumoniae] ...,L89.9 - Úlcera de decúbito y area de presión n...,L08.9 - Infección local de la piel y del tejid...,B96.2 - Escherichia coli [E. coli] como causa ...,A41.5 - Sepsis por otros organnismos Gram nega...,J86.9 - Piotórax sin fístula,...,99.84 - AISLAMIENTO,88.72 - ECOCARDIOGRAFIA,90.42 - EXAMEN MICROSCOPICO RESPIRATORIO.CULTIVO,90.52 - EXAMEN MICROSCOPICO SANGRE.CULTIVO,91.39 - EXAMEN MICROSCOPICO URINARIO INFERIOR....,91.33 - EXAMEN MICROSCOPICO URINARIO INFERIOR....,87.03 - TOMOGRAFIA AXIAL COMPUTERIZADA CABEZA,40,Hombre,184103 - MH SEPTICEMIA W/MCC
1,"U07.1 - COVID-19, virus identificado",J12.8 - Neumonía debida a otros virus,R06.0 - Disnea,R05 - Tos,"R50.9 - Fiebre, no especificada",Z29.0 - Aislamiento,Z01.7 - Examen de laboratorio,"J96.00 - Insuficiencia respiratoria aguda, Tip...",J94.2 - Hemotórax,J92.9 - Paquipleuritis sin asbestosis,...,91.62 - EXAMEN MICROSCOPICO PIEL.CULTIVO,90.43 - EXAMEN MICROSCOPICO RESPIRATORIO.CULTI...,91.39 - EXAMEN MICROSCOPICO URINARIO INFERIOR....,90.52 - EXAMEN MICROSCOPICO SANGRE.CULTIVO,91.32 - EXAMEN MICROSCOPICO URINARIO INFERIOR....,96.59 - IRRIGACION HERIDA OTRA,90.99 - EXAMEN MICROSCOPICO DIGESTIVO INFERIOR...,53,Hombre,041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
2,K56.5 - Adherencias [bridas] intestinales con ...,R57.2 - Shock séptico,R57.1 - Choque hipovolémico,J80 - Síndrome de dificultad respiratoria del ...,Y95 - Afección nosocomial,J15.0 - Neumonía debida a Klebsiella pneumoniae,U82.2 - Resistencia a Betalactamasas de amplio...,B95.6 - Staphylococcus aureus como causa de en...,B96.8 - Otros agentes bacterianos especificado...,B37.1 - Candidiasis pulmonar,...,99.84 - AISLAMIENTO,91.73 - EXAMEN MICROSCOPICO HERIDA OPERATORIA....,90.53 - EXAMEN MICROSCOPICO SANGRE.CULTIVO Y S...,99.26 - INYECCION TRANQUILIZANTE,89.39 - OTRAS MEDICIONES Y EXAMENES NO QUIRURG...,89.66 - GASOMETRIA VENA,89.65 - GASOMETRIA ARTERIA,65,Hombre,041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
3,K76.8 - Otras enfermedades especificadas del h...,K66.1 - Hemoperitoneo,"N18.5 - Enfermedad renal crónica, estadio 5",D64.9 - Anemia de tipo no especificado,E87.5 - Hiperpotasemia,E87.2 - Acidosis,J81 - Edema pulmonar,N17.8 - Otras insuficiencias renales agudas,J44.9 - Enfermedad pulmonar obstructiva crónic...,R41.0 - Desorientación no especificada,...,57.94 - SONDAJE URINARIO PERMANENTE,00.13 - INYECCION NESIRITIDE,00.17 - INFUSON AGENTE VASOPRESOR,99.04 - TRANSFUSION CONCENTRADO HEMATIES,99.18 - INYECCION ELECTROLITO,99.21 - INYECCION ANTIBIOTICO,99.23 - INYECCION ESTEROIDE,61,Hombre,041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...
4,T81.0 - Hemorragia y hematoma que complican un...,"Y83.2 - Operación quirúrgica con anastomosis, ...",S31.1 - Herida de la pared abdominal,S36.80 - Traumatismo de otros órganos intraabd...,W31.62 - Contacto traumático con otras maquina...,"J96.09 - Insuficiencia respiratoria aguda, Tip...",J15.0 - Neumonía debida a Klebsiella pneumoniae,U82.2 - Resistencia a Betalactamasas de amplio...,"U07.1 - COVID-19, virus identificado","N39.0 - Infección de vías urinarias, sitio no ...",...,90.52 - EXAMEN MICROSCOPICO SANGRE.CULTIVO,91.39 - EXAMEN MICROSCOPICO URINARIO INFERIOR....,91.32 - EXAMEN MICROSCOPICO URINARIO INFERIOR....,93.90 - RESPIRACION PRESION POSITIVA CONTINUA ...,99.15 - INFUSION PARENTERAL SUSTANCIA NUTRITIV...,96.59 - IRRIGACION HERIDA OTRA,45.13 - ESOFAGOGASTRODUODENOSCOPIA [EGD],30,Hombre,041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...

In [23]:
df.tail(5)

,Diag 01 Principal (cod+des),Diag 02 Secundario (cod+des),Diag 03 Secundario (cod+des),Diag 04 Secundario (cod+des),Diag 05 Secundario (cod+des),Diag 06 Secundario (cod+des),Diag 07 Secundario (cod+des),Diag 08 Secundario (cod+des),Diag 09 Secundario (cod+des),Diag 10 Secundario (cod+des),...,Proced 24 Secundario (cod+des),Proced 25 Secundario (cod+des),Proced 26 Secundario (cod+des),Proced 27 Secundario (cod+des),Proced 28 Secundario (cod+des),Proced 29 Secundario (cod+des),Proced 30 Secundario (cod+des),Edad en años,Sexo (Desc),GRD
14556,E10.1 - Diabetes mellitus tipo 1 con cetoacidosis,"J45.9 - Asma, no especificada",F10.2 - Trastornos mentales y del comportamien...,F17.2 - Trastornos mentales y del comportamien...,Z91.1 - Historia personal de incumplimiento de...,-,-,-,-,-,...,-,-,-,-,-,-,-,26,Mujer,104101 - MH DIABETES Y ENFERMEDADES METABÓLICA...
14557,"S09.9 - Traumatismo de la cabeza, no especificado","W18.24 - Otras caídas en el mismo nivel, escue...",R55 - Síncope y colapso,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,10,Hombre,014242 - MH TRAUMATISMO CEFÁLICO W/CC
14558,K92.1 - Melena,I10 - Hipertensión esencial (primaria),E11.9 - Diabetes mellitus tipo 2 sin complicac...,"I50.9 - Insuficiencia cardíaca, no especificada","K25.9 - Úlcera gástrica, no especificada como ...","M16.9 - Coxartrosis, no especificada",G47.3 - Apnea del sueño,Z99.8 - Dependencia de otras máquinas y dispos...,-,-,...,-,-,-,-,-,-,-,58,Hombre,064182 - MH OTROS DIAGNÓSTICOS SOBRE APARATO D...
14559,E78.1 - Hipergliceridemia pura,I10 - Hipertensión esencial (primaria),Z92.2 - Historia personal de uso (presente) de...,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,47,Hombre,104121 - MH ERRORES CONGÉNITOS DE METABOLISMO
14560,"S06.51 - Hemorragia subdural traumática, con h...","S06.21 - Traumatismo cerebral difuso, con heri...","W18.09 - Otras caídas en el mismo nivel, vivie...",J69.0 - Neumonitis debida a aspiración de alim...,D29.1 - Tumor benigno de la próstata,Z59.0 - Problemas relacionados con la falta de...,Z02.7 - Extensión de certificado médico,-,-,-,...,89.66 - GASOMETRIA VENA,89.66 - GASOMETRIA VENA,90.39 - EXAMEN MICROSCOPICO ORL.OTRO,90.42 - EXAMEN MICROSCOPICO RESPIRATORIO.CULTIVO,90.52 - EXAMEN MICROSCOPICO SANGRE.CULTIVO,90.59 - EXAMEN MICROSCOPICO SANGRE.OTRO,90.59 - EXAMEN MICROSCOPICO SANGRE.OTRO,73,Hombre,041203 - PH PROCEDIMIENTOS NO COMPLEJOS SOBRE ...

In [20]:
for col in df.columns[:15]:
    print(f"{col} --> {df[col].iloc[0]}")

Diag 01 Principal (cod+des) --> A41.8 - Otras septicemias especificadas
Diag 02 Secundario (cod+des) --> B37.6 - Endocarditis debida a candida (I39.8*)
Diag 03 Secundario (cod+des) --> I39.8 - Endocarditis, válvula no especificada, en enfermedades clasificadas en otra parte
Diag 04 Secundario (cod+des) --> N10 - Nefritis tubulointersticial aguda
Diag 05 Secundario (cod+des) --> B96.1 - Klebsiella pneumoniae [K. pneumoniae] como causa de enfermedades clasificadas en otros capítulos
Diag 06 Secundario (cod+des) --> L89.9 - Úlcera de decúbito y area de presión no especificadas
Diag 07 Secundario (cod+des) --> L08.9 - Infección local de la piel y del tejido subcutáneo, no especificada
Diag 08 Secundario (cod+des) --> B96.2 - Escherichia coli [E. coli] como causa de enfermedades clasificadas en otros capítulos
Diag 09 Secundario (cod+des) --> A41.5 - Sepsis por otros organnismos Gram negativos
Diag 10 Secundario (cod+des) --> J86.9 - Piotórax sin fístula
Diag 11 Secundario (cod+des) --> U07.1 - COVID-19, virus identificado
Diag 12 Secundario (cod+des) --> Y95 - Afección nosocomial
Diag 13 Secundario (cod+des) --> N18.5 - Enfermedad renal crónica, estadio 5
Diag 14 Secundario (cod+des) --> E87.1 - Hiposmolaridad e hiponatremia
Diag 15 Secundario (cod+des) --> D64.9 - Anemia de tipo no especificado

In [24]:
df.columns.tolist()

['Diag 01 Principal (cod+des)',
 'Diag 02 Secundario (cod+des)',
 'Diag 03 Secundario (cod+des)',
 'Diag 04 Secundario (cod+des)',
 'Diag 05 Secundario (cod+des)',
 'Diag 06 Secundario (cod+des)',
 'Diag 07 Secundario (cod+des)',
 'Diag 08 Secundario (cod+des)',
 'Diag 09 Secundario (cod+des)',
 'Diag 10 Secundario (cod+des)',
 'Diag 11 Secundario (cod+des)',
 'Diag 12 Secundario (cod+des)',
 'Diag 13 Secundario (cod+des)',
 'Diag 14 Secundario (cod+des)',
 'Diag 15 Secundario (cod+des)',
 'Diag 16 Secundario (cod+des)',
 'Diag 17 Secundario (cod+des)',
 'Diag 18 Secundario (cod+des)',
 'Diag 19 Secundario (cod+des)',
 'Diag 20 Secundario (cod+des)',
 'Diag 21 Secundario (cod+des)',
 'Diag 22 Secundario (cod+des)',
 'Diag 23 Secundario (cod+des)',
 'Diag 24 Secundario (cod+des)',
 'Diag 25 Secundario (cod+des)',
 'Diag 26 Secundario (cod+des)',
 'Diag 27 Secundario (cod+des)',
 'Diag 28 Secundario (cod+des)',
 'Diag 29 Secundario (cod+des)',
 'Diag 30 Secundario (cod+des)',
 'Diag 31 Secundario (cod+des)',
 'Diag 32 Secundario (cod+des)',
 'Diag 33 Secundario (cod+des)',
 'Diag 34 Secundario (cod+des)',
 'Diag 35 Secundario (cod+des)',
 'Proced 01 Principal (cod+des)',
 'Proced 02 Secundario (cod+des)',
 'Proced 03 Secundario (cod+des)',
 'Proced 04 Secundario (cod+des)',
 'Proced 05 Secundario (cod+des)',
 'Proced 06 Secundario (cod+des)',
 'Proced 07 Secundario (cod+des)',
 'Proced 08 Secundario (cod+des)',
 'Proced 09 Secundario (cod+des)',
 'Proced 10 Secundario (cod+des)',
 'Proced 11 Secundario (cod+des)',
 'Proced 12 Secundario (cod+des)',
 'Proced 13 Secundario (cod+des)',
 'Proced 14 Secundario (cod+des)',
 'Proced 15 Secundario (cod+des)',
 'Proced 16 Secundario (cod+des)',
 'Proced 17 Secundario (cod+des)',
 'Proced 18 Secundario (cod+des)',
 'Proced 19 Secundario (cod+des)',
 'Proced 20 Secundario (cod+des)',
 'Proced 21 Secundario (cod+des)',
 'Proced 22 Secundario (cod+des)',
 'Proced 23 Secundario (cod+des)',
 'Proced 24 Secundario (cod+des)',
 'Proced 25 Secundario (cod+des)',
 'Proced 26 Secundario (cod+des)',
 'Proced 27 Secundario (cod+des)',
 'Proced 28 Secundario (cod+des)',
 'Proced 29 Secundario (cod+des)',
 'Proced 30 Secundario (cod+des)',
 'Edad en años',
 'Sexo (Desc)',
 'GRD']

In [25]:
cols = df.columns

diagnosticos = [c for c in cols if "Diag" in c]
procedimientos = [c for c in cols if "Proced" in c]
edad = [c for c in cols if "Edad" in c]
sexo = [c for c in cols if "Sexo" in c]
grd = [c for c in cols if "GRD" in c]

clasificadas = set(diagnosticos + procedimientos + edad + sexo + grd)

pendientes = [c for c in cols if c not in clasificadas]

print("Diagnósticos:", len(diagnosticos))
print("Procedimientos:", len(procedimientos))
print("Edad:", edad)
print("Sexo:", sexo)
print("GRD:", grd)
print("Pendientes:", pendientes)

Diagnósticos: 35
Procedimientos: 30
Edad: ['Edad en años']
Sexo: ['Sexo (Desc)']
GRD: ['GRD']
Pendientes: []

In [26]:
df["GRD"].head(10)

0                         184103 - MH SEPTICEMIA W/MCC
1    041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
2    041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
3    041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...
4    041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...
5    041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
6    041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
7    041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
8    041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...
9    041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...
Name: GRD, dtype: object

In [27]:
df["GRD"].tail(10)

14551    194121 - MH TRASTORNOS DE LA PERSONALIDAD Y DE...
14552            061131 - PH PROCEDIMIENTOS SOBRE APÉNDICE
14553                 134161 - MH TRASTORNOS DEL ANTEPARTO
14554    158172 - MH NEONATO, PESO AL NACER >2499 GR SI...
14555                                094121 - MH CELULITIS
14556    104101 - MH DIABETES Y ENFERMEDADES METABÓLICA...
14557                014242 - MH TRAUMATISMO CEFÁLICO W/CC
14558    064182 - MH OTROS DIAGNÓSTICOS SOBRE APARATO D...
14559        104121 - MH ERRORES CONGÉNITOS DE METABOLISMO
14560    041203 - PH PROCEDIMIENTOS NO COMPLEJOS SOBRE ...
Name: GRD, dtype: object

In [28]:
df["GRD"].nunique()

526

In [30]:
df["GRD"].value_counts()

GRD
146101 - PH CESÁREA                                                                           813
146121 - PH PARTO VAGINAL CON PROCED., EXCEPTO ESTERILIZACIÓN Y/O DILATACIÓN Y LEGRADO        639
146131 - PH PARTO VAGINAL                                                                     538
158171 - MH NEONATO, PESO AL NACER >2499 GR SIN PROCEDIMIENTO MAYOR                           389
134161 - MH TRASTORNOS DEL ANTEPARTO                                                          325
                                                                                             ...
214103 - MH LESIONES DE MÚLTIPLES SITIOS NO ESPECIFICADOS W/MCC                                 1
054223 - MH MIOCARDIOPATÍA W/MCC                                                                1
114142 - MH DISFUNCIÓN, REACCIÓN O COMPL. POR DISP., INJ. O TRAS. DEL TRACTO URINARIO W/CC      1
131122 - PH INTERRUPCIÓN TUBÁRICA ABIERTA W/CC                                                  1
134153 - MH FALSO TRABAJO DEL PARTO W/MCC                                                       1
Name: count, Length: 526, dtype: int64

In [31]:
df["GRD"].value_counts().describe()

count    526.00000
mean      27.68251
std       67.28699
min        1.00000
25%        3.00000
50%        8.00000
75%       23.75000
max      813.00000
Name: count, dtype: float64

# Analisis Archivos Secundarios
## CIE - 10

In [32]:
import pandas as pd

cie10 = pd.read_excel("../data/raw/CIE-10.xlsx")

In [33]:
xls = pd.ExcelFile("../data/raw/CIE-10.xlsx")
xls.sheet_names

['CIE 10']

In [34]:
cie10.head()

,Versión,Código,Descripción,Categoría,Sección,Capítulo
0,CIE-v2013,A00,Cólera,A00 CÓLERA,A00-A09 ENFERMEDADES INFECCIOSAS INTESTINALES,Cap.01 CIERTAS ENFERMEDADES INFECCIOSAS Y PAR...
1,CIE-v2013,A00.0,"Cólera debido a Vibrio cholerae O1, biotipo ch...",A00 CÓLERA,A00-A09 ENFERMEDADES INFECCIOSAS INTESTINALES,Cap.01 CIERTAS ENFERMEDADES INFECCIOSAS Y PAR...
2,CIE-v2013,A00.1,"Cólera debido a Vibrio cholerae O1, biotipo El...",A00 CÓLERA,A00-A09 ENFERMEDADES INFECCIOSAS INTESTINALES,Cap.01 CIERTAS ENFERMEDADES INFECCIOSAS Y PAR...
3,CIE-v2013,A00.9,"Cólera, no especificado",A00 CÓLERA,A00-A09 ENFERMEDADES INFECCIOSAS INTESTINALES,Cap.01 CIERTAS ENFERMEDADES INFECCIOSAS Y PAR...
4,CIE-v2013,A01,Fiebres tifoidea y paratifoidea,A01 FIEBRES TIFOIDEA Y PARATIFOIDEA,A00-A09 ENFERMEDADES INFECCIOSAS INTESTINALES,Cap.01 CIERTAS ENFERMEDADES INFECCIOSAS Y PAR...

In [35]:
cie10.columns.tolist()

['Versión', 'Código', 'Descripción', 'Categoría', 'Sección', 'Capítulo']

## CIE - 9

In [36]:
cie9 = pd.read_excel("../data/raw/CIE-9.xlsx")

In [37]:
xls = pd.ExcelFile("../data/raw/CIE-9.xlsx")
xls.sheet_names

['CIE 9']

In [38]:
cie9.head()

,Código,Descripción,Categoría,Sección,Capítulo
0,0.00,PROCEDIMIENTO E INTERVENCION NCOC,"00 PROCEDIMIENTOS E INTERVENCIONES, NO CLASIFI...",00. (00 00) PROCEDIMIENTOS E INTERVENCIONES NO...,00. (00 00) PROCEDIMIENTOS E INTERVENCIONES NO...
1,0.00,ULTRASONIDO TERAPEUTICO,"00 PROCEDIMIENTOS E INTERVENCIONES, NO CLASIFI...",00. (00 00) PROCEDIMIENTOS E INTERVENCIONES NO...,00. (00 00) PROCEDIMIENTOS E INTERVENCIONES NO...
2,0.01,ULTRASONIDO TERAPEUTICO.VASO CABEZA Y CUELLO,"00 PROCEDIMIENTOS E INTERVENCIONES, NO CLASIFI...",00. (00 00) PROCEDIMIENTOS E INTERVENCIONES NO...,00. (00 00) PROCEDIMIENTOS E INTERVENCIONES NO...
3,0.02,ULTRASONIDO TERAPEUTICO.CORAZON,"00 PROCEDIMIENTOS E INTERVENCIONES, NO CLASIFI...",00. (00 00) PROCEDIMIENTOS E INTERVENCIONES NO...,00. (00 00) PROCEDIMIENTOS E INTERVENCIONES NO...
4,0.03,ULTRASONIDO TERAPEUTICO.VASO PERIFERICO,"00 PROCEDIMIENTOS E INTERVENCIONES, NO CLASIFI...",00. (00 00) PROCEDIMIENTOS E INTERVENCIONES NO...,00. (00 00) PROCEDIMIENTOS E INTERVENCIONES NO...

In [39]:
cie9.columns.tolist()

['Código', 'Descripción', 'Categoría', 'Sección', 'Capítulo']

## IR - GRD

In [41]:
ir_grd = pd.read_excel("../data/raw/IR-GRD V3.1 CON PRECIOS FONASA 2016.xlsx")

In [42]:
xls = pd.ExcelFile("../data/raw/IR-GRD V3.1 CON PRECIOS FONASA 2016.xlsx")
xls.sheet_names

['IR-GRD v3.1']

In [43]:
ir_grd.head()

,IR-GRD CÓDIGO,NOMBRE DEL GRUPO GRD,Peso v31,CDM_COD,CATEGORÍA DIAGNÓSTICA MAYOR CDM,TIPO_COD,TIPO GRD,Precio FONASA 2016
0,11011,PH PROCEDIMIENTOS VASCULARES INTRACRANEALES,2.4330,1,SISTEMA NERVIOSO,PH,PROCEDIMIENTO HOSPITALIZADO,3.936157e+06
1,11012,PH PROCEDIMIENTOS VASCULARES INTRACRANEALES W/CC,3.6066,1,SISTEMA NERVIOSO,PH,PROCEDIMIENTO HOSPITALIZADO,5.834832e+06
2,11013,PH PROCEDIMIENTOS VASCULARES INTRACRANEALES W/MCC,5.8425,1,SISTEMA NERVIOSO,PH,PROCEDIMIENTO HOSPITALIZADO,9.452117e+06
3,11101,PH CRANEOTOMÍA,1.8731,1,SISTEMA NERVIOSO,PH,PROCEDIMIENTO HOSPITALIZADO,3.030340e+06
4,11102,PH CRANEOTOMÍA W/CC,2.4218,1,SISTEMA NERVIOSO,PH,PROCEDIMIENTO HOSPITALIZADO,3.918038e+06

In [44]:
ir_grd.columns.tolist()

['IR-GRD CÓDIGO',
 'NOMBRE DEL GRUPO GRD',
 'Peso v31',
 'CDM_COD',
 'CATEGORÍA DIAGNÓSTICA MAYOR CDM',
 'TIPO_COD',
 'TIPO GRD',
 'Precio FONASA 2016']

## Tablas Maestras Bases GRD

In [45]:
xls = pd.ExcelFile("../data/raw/Tablas maestras bases GRD.xlsx")
xls.sheet_names

['Hospitales',
 'Tipo de Pabellon',
 'IR - GRD',
 'Severidad GRD',
 'Mortalidad GRD']

In [48]:
import pandas as pd

ruta = "../data/raw/Tablas maestras bases GRD.xlsx"

xls = pd.ExcelFile(ruta)
hojas = xls.sheet_names

resumen = []

for hoja in hojas:
    df_temp = pd.read_excel(ruta, sheet_name=hoja)
    
    columnas = df_temp.columns.tolist()
    
    resumen.append({
        "Hoja": hoja,
        "Columnas": columnas
    })

# Mostrar resultados
for r in resumen:
    print(f"\n--- Hoja: {r['Hoja']} ---")
    print("Columnas:")
    for col in r["Columnas"]:
        print(f"- {col}")

--- Hoja: Hospitales ---
Columnas:
- HOSPITALES
- Unnamed: 1

--- Hoja: Tipo de Pabellon ---
Columnas:
- TIPO DE PABELLON
- Unnamed: 1

--- Hoja: IR - GRD ---
Columnas:
- IR- GRD
- Unnamed: 1

--- Hoja: Severidad GRD ---
Columnas:
- Severidad
- Unnamed: 1

--- Hoja: Mortalidad GRD ---
Columnas:
- Mortalidad
- Unnamed: 1

# Modelacion de las variables

In [51]:
df_raw = df.copy()
df_work = df_raw.copy()

In [52]:
print("df_raw shape:", df_raw.shape)
print("df_work shape:", df_work.shape)
print("Mismas columnas:", list(df_raw.columns) == list(df_work.columns))
print("Son el mismo objeto en memoria:", df_raw is df_work)

df_raw shape: (14561, 68)
df_work shape: (14561, 68)
Mismas columnas: True
Son el mismo objeto en memoria: False

In [53]:
# 1. Filas
print("Filas iguales:", df_raw.shape[0] == df_work.shape[0])

# 2. Columnas (cantidad)
print("Columnas iguales (cantidad):", df_raw.shape[1] == df_work.shape[1])

# 3. Nombres columnas
print("Columnas iguales (nombres):", all(df_raw.columns == df_work.columns))

# 4. Tipos de datos
print("Tipos iguales:", all(df_raw.dtypes == df_work.dtypes))

Filas iguales: True
Columnas iguales (cantidad): True
Columnas iguales (nombres): True
Tipos iguales: True

In [54]:
for col in df_work.columns:
    print(col)

Diag 01 Principal (cod+des)
Diag 02 Secundario (cod+des)
Diag 03 Secundario (cod+des)
Diag 04 Secundario (cod+des)
Diag 05 Secundario (cod+des)
Diag 06 Secundario (cod+des)
Diag 07 Secundario (cod+des)
Diag 08 Secundario (cod+des)
Diag 09 Secundario (cod+des)
Diag 10 Secundario (cod+des)
Diag 11 Secundario (cod+des)
Diag 12 Secundario (cod+des)
Diag 13 Secundario (cod+des)
Diag 14 Secundario (cod+des)
Diag 15 Secundario (cod+des)
Diag 16 Secundario (cod+des)
Diag 17 Secundario (cod+des)
Diag 18 Secundario (cod+des)
Diag 19 Secundario (cod+des)
Diag 20 Secundario (cod+des)
Diag 21 Secundario (cod+des)
Diag 22 Secundario (cod+des)
Diag 23 Secundario (cod+des)
Diag 24 Secundario (cod+des)
Diag 25 Secundario (cod+des)
Diag 26 Secundario (cod+des)
Diag 27 Secundario (cod+des)
Diag 28 Secundario (cod+des)
Diag 29 Secundario (cod+des)
Diag 30 Secundario (cod+des)
Diag 31 Secundario (cod+des)
Diag 32 Secundario (cod+des)
Diag 33 Secundario (cod+des)
Diag 34 Secundario (cod+des)
Diag 35 Secundario (cod+des)
Proced 01 Principal (cod+des)
Proced 02 Secundario (cod+des)
Proced 03 Secundario (cod+des)
Proced 04 Secundario (cod+des)
Proced 05 Secundario (cod+des)
Proced 06 Secundario (cod+des)
Proced 07 Secundario (cod+des)
Proced 08 Secundario (cod+des)
Proced 09 Secundario (cod+des)
Proced 10 Secundario (cod+des)
Proced 11 Secundario (cod+des)
Proced 12 Secundario (cod+des)
Proced 13 Secundario (cod+des)
Proced 14 Secundario (cod+des)
Proced 15 Secundario (cod+des)
Proced 16 Secundario (cod+des)
Proced 17 Secundario (cod+des)
Proced 18 Secundario (cod+des)
Proced 19 Secundario (cod+des)
Proced 20 Secundario (cod+des)
Proced 21 Secundario (cod+des)
Proced 22 Secundario (cod+des)
Proced 23 Secundario (cod+des)
Proced 24 Secundario (cod+des)
Proced 25 Secundario (cod+des)
Proced 26 Secundario (cod+des)
Proced 27 Secundario (cod+des)
Proced 28 Secundario (cod+des)
Proced 29 Secundario (cod+des)
Proced 30 Secundario (cod+des)
Edad en años
Sexo (Desc)
GRD

In [55]:
cols_diag = [col for col in df_work.columns if col.startswith("Diag")]
cols_proc = [col for col in df_work.columns if col.startswith("Proced")]

cols_demo = [
    "Edad en años",
    "Sexo (Desc)"
]

col_target = "GRD"

In [56]:
print("Diagnósticos:", len(cols_diag))
print("Procedimientos:", len(cols_proc))
print("Demográficas:", cols_demo)
print("Target:", col_target)

Diagnósticos: 35
Procedimientos: 30
Demográficas: ['Edad en años', 'Sexo (Desc)']
Target: GRD

In [57]:
set(cols_diag + cols_proc + cols_demo + [col_target]) == set(df_work.columns)

True

In [58]:
valores_sospechosos = set()

for col in cols_diag + cols_proc:
    uniques = df_work[col].dropna().unique()
    
    for val in uniques:
        if isinstance(val, str):
            val_strip = val.strip()
            
            if val_strip in ["-", "", " ", "NA", "N/A", "null"]:
                valores_sospechosos.add(val_strip)

valores_sospechosos

{'-'}

In [60]:
print(cie10.columns.tolist())
print(cie9.columns.tolist())

['Versión', 'Código', 'Descripción', 'Categoría', 'Sección', 'Capítulo']
['Código', 'Descripción', 'Categoría', 'Sección', 'Capítulo']

In [61]:
"-" in cie10["Código"].astype(str).str.strip().values

False

In [62]:
"-" in cie9["Código"].astype(str).str.strip().values

False

In [63]:
print(cie10["Código"].astype(str).str.strip().head(10).tolist())
print(cie9["Código"].astype(str).str.strip().head(10).tolist())

['A00', 'A00.0', 'A00.1', 'A00.9', 'A01', 'A01.0', 'A01.1', 'A01.2', 'A01.3', 'A01.4']
['0.0', '0.0', '0.01', '0.02', '0.03', '0.09', '0.1', '0.1', '0.11', '0.12']

## Sacamos -

In [64]:
import numpy as np

df_work[cols_diag + cols_proc] = df_work[cols_diag + cols_proc].replace("-", np.nan)

In [65]:
quedan_guiones = (df_work[cols_diag + cols_proc] == "-").sum().sum()
print("Guiones restantes en columnas clínicas:", quedan_guiones)

Guiones restantes en columnas clínicas: 0

In [66]:
print("Nulos en primeras 3 columnas diagnósticas:")
print(df_work[cols_diag[:3]].isna().sum())

print("\nNulos en primeras 3 columnas de procedimientos:")
print(df_work[cols_proc[:3]].isna().sum())

Nulos en primeras 3 columnas diagnósticas:
Diag 01 Principal (cod+des)        0
Diag 02 Secundario (cod+des)    1209
Diag 03 Secundario (cod+des)    2687
dtype: int64

Nulos en primeras 3 columnas de procedimientos:
Proced 01 Principal (cod+des)       0
Proced 02 Secundario (cod+des)    134
Proced 03 Secundario (cod+des)    342
dtype: int64

In [67]:
print("¿Edad contiene NaN nuevos?:", df_work["Edad en años"].isna().sum())
print("¿Sexo contiene NaN nuevos?:", df_work["Sexo (Desc)"].isna().sum())
print("¿GRD contiene NaN nuevos?:", df_work["GRD"].isna().sum())

¿Edad contiene NaN nuevos?: 0
¿Sexo contiene NaN nuevos?: 0
¿GRD contiene NaN nuevos?: 0

## Impacto "-"

In [68]:
total_nulos = df_work[cols_diag + cols_proc].isna().sum().sum()
print("Total nulos actuales (clínicos):", total_nulos)

Total nulos actuales (clínicos): 649545

In [69]:
nulos_diag = df_work[cols_diag].isna().sum().sum()
nulos_proc = df_work[cols_proc].isna().sum().sum()

print("Nulos en diagnósticos:", nulos_diag)
print("Nulos en procedimientos:", nulos_proc)

Nulos en diagnósticos: 405175
Nulos en procedimientos: 244370

In [70]:
print("Consistencia total:", total_nulos == (nulos_diag + nulos_proc))

Consistencia total: True

In [71]:
for col in cols_diag[:3]:
    print(f"\n--- {col} ---")
    print(df_work[col].dropna().head(5).tolist())

--- Diag 01 Principal (cod+des) ---
['A41.8 - Otras septicemias especificadas', 'U07.1 - COVID-19, virus identificado', 'K56.5 - Adherencias [bridas] intestinales con obstrucción', 'K76.8 - Otras enfermedades especificadas del hígado', 'T81.0 - Hemorragia y hematoma que complican un procedimiento, no clasificados en otra parte']

--- Diag 02 Secundario (cod+des) ---
['B37.6 - Endocarditis debida a candida (I39.8*)', 'J12.8 - Neumonía debida a otros virus', 'R57.2 - Shock séptico', 'K66.1 - Hemoperitoneo', 'Y83.2 - Operación quirúrgica con anastomosis, derivación o injerto']

--- Diag 03 Secundario (cod+des) ---
['I39.8 - Endocarditis, válvula no especificada, en enfermedades clasificadas en otra parte', 'R06.0 - Disnea', 'R57.1 - Choque hipovolémico', 'N18.5 - Enfermedad renal crónica, estadio 5', 'S31.1 - Herida de la pared abdominal']

In [72]:
for col in cols_proc[:3]:
    print(f"\n--- {col} ---")
    print(df_work[col].dropna().head(5).tolist())

--- Proced 01 Principal (cod+des) ---
['86.28 - DESBRIDAMIENTO HERIDA,INFECCION O QUEMADURA NO ESCISIONAL', '31.1 - TRAQUEOSTOMIA TEMPORAL', '86.22 - DESBRIDAMIENTO HERIDA,INFECCION O QUEMADURA ESCISIONAL', '54.19 - LAPAROTOMIA.OTRA', '54.11 - LAPAROTOMIA EXPLORATORIA']

--- Proced 02 Secundario (cod+des) ---
['34.91 - TORACOCENTESIS', '86.28 - DESBRIDAMIENTO HERIDA,INFECCION O QUEMADURA NO ESCISIONAL', '54.59 - LISIS ADHERENCIA PERITONEO.OTRA', '39.98 - CONTROL HEMORRAGIA NEOM', '45.90 - ANASTOMOSIS INTESTINO.NEOM']

--- Proced 03 Secundario (cod+des) ---
['88.38 - TOMOGRAFIA AXIAL COMPUTERIZADA OTRA', '96.72 - VENTILACION MECANICA CONTINUA OTRA.DURANTE 96 HORAS O MAS', '96.72 - VENTILACION MECANICA CONTINUA OTRA.DURANTE 96 HORAS O MAS', '86.28 - DESBRIDAMIENTO HERIDA,INFECCION O QUEMADURA NO ESCISIONAL', '46.73 - SUTURA INTESTINO DELGADO SALVO DUODENO']

In [73]:
cols_clinicas = cols_diag + cols_proc

patron_muestra = {}

for col in cols_clinicas[:10]:
    serie = df_work[col].dropna().astype(str)
    total = len(serie)
    con_delimitador = serie.str.contains(" - ", regex=False).sum()
    
    patron_muestra[col] = {
        "total_no_nulos": total,
        "con_delimitador": con_delimitador
    }

patron_muestra

{'Diag 01 Principal (cod+des)': {'total_no_nulos': 14561,
  'con_delimitador': np.int64(14561)},
 'Diag 02 Secundario (cod+des)': {'total_no_nulos': 13352,
  'con_delimitador': np.int64(13352)},
 'Diag 03 Secundario (cod+des)': {'total_no_nulos': 11874,
  'con_delimitador': np.int64(11874)},
 'Diag 04 Secundario (cod+des)': {'total_no_nulos': 10434,
  'con_delimitador': np.int64(10434)},
 'Diag 05 Secundario (cod+des)': {'total_no_nulos': 9190,
  'con_delimitador': np.int64(9190)},
 'Diag 06 Secundario (cod+des)': {'total_no_nulos': 8167,
  'con_delimitador': np.int64(8167)},
 'Diag 07 Secundario (cod+des)': {'total_no_nulos': 7153,
  'con_delimitador': np.int64(7153)},
 'Diag 08 Secundario (cod+des)': {'total_no_nulos': 5977,
  'con_delimitador': np.int64(5977)},
 'Diag 09 Secundario (cod+des)': {'total_no_nulos': 4842,
  'con_delimitador': np.int64(4842)},
 'Diag 10 Secundario (cod+des)': {'total_no_nulos': 3865,
  'con_delimitador': np.int64(3865)}}

In [74]:
columnas_con_problemas = []

for col in cols_clinicas:
    serie = df_work[col].dropna().astype(str)
    if len(serie) == 0:
        continue
    
    cumple = serie.str.contains(" - ", regex=False).all()
    
    if not cumple:
        columnas_con_problemas.append(col)

columnas_con_problemas

[]

# Separacion de las variables

In [75]:
df_diag_split = df_work.copy()

In [76]:
for col in cols_diag:
    
    # split controlado en máximo 1 división
    split = df_diag_split[col].str.split(" - ", n=1, expand=True)
    
    # nuevas columnas
    df_diag_split[f"{col}_cod"] = split[0]
    df_diag_split[f"{col}_desc"] = split[1]

In [77]:
nuevas_cols_diag = [col for col in df_diag_split.columns if col.endswith("_cod") or col.endswith("_desc")]
len(nuevas_cols_diag)

70

In [78]:
cols_test = cols_diag[:2]

for col in cols_test:
    print(f"\n--- {col} ---")
    print(df_diag_split[[col, f"{col}_cod", f"{col}_desc"]].head(5))

--- Diag 01 Principal (cod+des) ---
                         Diag 01 Principal (cod+des)  \
0            A41.8 - Otras septicemias especificadas
1               U07.1 - COVID-19, virus identificado
2  K56.5 - Adherencias [bridas] intestinales con ...
3  K76.8 - Otras enfermedades especificadas del h...
4  T81.0 - Hemorragia y hematoma que complican un...

  Diag 01 Principal (cod+des)_cod  \
0                           A41.8
1                           U07.1
2                           K56.5
3                           K76.8
4                           T81.0

                    Diag 01 Principal (cod+des)_desc
0                    Otras septicemias especificadas
1                       COVID-19, virus identificado
2  Adherencias [bridas] intestinales con obstrucción
3        Otras enfermedades especificadas del hígado
4  Hemorragia y hematoma que complican un procedi...

--- Diag 02 Secundario (cod+des) ---
                        Diag 02 Secundario (cod+des)  \
0     B37.6 - Endocarditis debida a candida (I39.8*)
1              J12.8 - Neumonía debida a otros virus
2                              R57.2 - Shock séptico
3                              K66.1 - Hemoperitoneo
4  Y83.2 - Operación quirúrgica con anastomosis, ...

  Diag 02 Secundario (cod+des)_cod  \
0                            B37.6
1                            J12.8
2                            R57.2
3                            K66.1
4                            Y83.2

                   Diag 02 Secundario (cod+des)_desc
0             Endocarditis debida a candida (I39.8*)
1                      Neumonía debida a otros virus
2                                      Shock séptico
3                                      Hemoperitoneo
4  Operación quirúrgica con anastomosis, derivaci...

In [79]:
for col in cols_diag[:3]:
    original_nan = df_diag_split[col].isna().sum()
    cod_nan = df_diag_split[f"{col}_cod"].isna().sum()
    desc_nan = df_diag_split[f"{col}_desc"].isna().sum()
    
    print(col)
    print("Original:", original_nan, "| Cod:", cod_nan, "| Desc:", desc_nan)
    print("-" * 40)

Diag 01 Principal (cod+des)
Original: 0 | Cod: 0 | Desc: 0
----------------------------------------
Diag 02 Secundario (cod+des)
Original: 1209 | Cod: 1209 | Desc: 1209
----------------------------------------
Diag 03 Secundario (cod+des)
Original: 2687 | Cod: 2687 | Desc: 2687
----------------------------------------

In [80]:
for col in cols_proc:
    
    split = df_diag_split[col].str.split(" - ", n=1, expand=True)
    
    df_diag_split[f"{col}_cod"] = split[0]
    df_diag_split[f"{col}_desc"] = split[1]

C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_cod"] = split[0]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_desc"] = split[1]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_cod"] = split[0]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_desc"] = split[1]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_cod"] = split[0]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_desc"] = split[1]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_cod"] = split[0]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_desc"] = split[1]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_cod"] = split[0]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_desc"] = split[1]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_cod"] = split[0]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_desc"] = split[1]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_cod"] = split[0]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_desc"] = split[1]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_cod"] = split[0]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_desc"] = split[1]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_cod"] = split[0]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_desc"] = split[1]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_cod"] = split[0]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_desc"] = split[1]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_cod"] = split[0]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_desc"] = split[1]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_cod"] = split[0]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_desc"] = split[1]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_cod"] = split[0]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_desc"] = split[1]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_cod"] = split[0]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_desc"] = split[1]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_cod"] = split[0]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_desc"] = split[1]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_cod"] = split[0]
C:\Users\inait\AppData\Local\Temp\ipykernel_23328\2252667611.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diag_split[f"{col}_desc"] = split[1]

In [81]:
nuevas_cols_proc = [col for col in df_diag_split.columns if col.startswith("Proced") and (col.endswith("_cod") or col.endswith("_desc"))]
len(nuevas_cols_proc)

60

In [82]:
cols_test_proc = cols_proc[:2]

for col in cols_test_proc:
    print(f"\n--- {col} ---")
    print(df_diag_split[[col, f"{col}_cod", f"{col}_desc"]].head(5))

--- Proced 01 Principal (cod+des) ---
                       Proced 01 Principal (cod+des)  \
0  86.28 - DESBRIDAMIENTO HERIDA,INFECCION O QUEM...
1                      31.1 - TRAQUEOSTOMIA TEMPORAL
2  86.22 - DESBRIDAMIENTO HERIDA,INFECCION O QUEM...
3                           54.19 - LAPAROTOMIA.OTRA
4                   54.11 - LAPAROTOMIA EXPLORATORIA

  Proced 01 Principal (cod+des)_cod  \
0                             86.28
1                              31.1
2                             86.22
3                             54.19
4                             54.11

                  Proced 01 Principal (cod+des)_desc
0  DESBRIDAMIENTO HERIDA,INFECCION O QUEMADURA NO...
1                             TRAQUEOSTOMIA TEMPORAL
2  DESBRIDAMIENTO HERIDA,INFECCION O QUEMADURA ES...
3                                   LAPAROTOMIA.OTRA
4                           LAPAROTOMIA EXPLORATORIA

--- Proced 02 Secundario (cod+des) ---
                      Proced 02 Secundario (cod+des)  \
0                             34.91 - TORACOCENTESIS
1  86.28 - DESBRIDAMIENTO HERIDA,INFECCION O QUEM...
2            54.59 - LISIS ADHERENCIA PERITONEO.OTRA
3                    39.98 - CONTROL HEMORRAGIA NEOM
4                 45.90 - ANASTOMOSIS INTESTINO.NEOM

  Proced 02 Secundario (cod+des)_cod  \
0                              34.91
1                              86.28
2                              54.59
3                              39.98
4                              45.90

                 Proced 02 Secundario (cod+des)_desc
0                                     TORACOCENTESIS
1  DESBRIDAMIENTO HERIDA,INFECCION O QUEMADURA NO...
2                    LISIS ADHERENCIA PERITONEO.OTRA
3                            CONTROL HEMORRAGIA NEOM
4                         ANASTOMOSIS INTESTINO.NEOM

In [83]:
for col in cols_proc[:3]:
    original_nan = df_diag_split[col].isna().sum()
    cod_nan = df_diag_split[f"{col}_cod"].isna().sum()
    desc_nan = df_diag_split[f"{col}_desc"].isna().sum()
    
    print(col)
    print("Original:", original_nan, "| Cod:", cod_nan, "| Desc:", desc_nan)
    print("-" * 40)

Proced 01 Principal (cod+des)
Original: 0 | Cod: 0 | Desc: 0
----------------------------------------
Proced 02 Secundario (cod+des)
Original: 134 | Cod: 134 | Desc: 134
----------------------------------------
Proced 03 Secundario (cod+des)
Original: 342 | Cod: 342 | Desc: 342
----------------------------------------

In [84]:
cols_check = [
    "Diag 01 Principal (cod+des)",
    "Diag 01 Principal (cod+des)_cod",
    "Diag 01 Principal (cod+des)_desc",
    "Proced 01 Principal (cod+des)",
    "Proced 01 Principal (cod+des)_cod",
    "Proced 01 Principal (cod+des)_desc"
]

for col in cols_check:
    print(col, "->", col in df_diag_split.columns)

Diag 01 Principal (cod+des) -> True
Diag 01 Principal (cod+des)_cod -> True
Diag 01 Principal (cod+des)_desc -> True
Proced 01 Principal (cod+des) -> True
Proced 01 Principal (cod+des)_cod -> True
Proced 01 Principal (cod+des)_desc -> True

In [85]:
df_diag_split[
    [
        "Diag 01 Principal (cod+des)",
        "Diag 01 Principal (cod+des)_cod",
        "Diag 01 Principal (cod+des)_desc",
        "Proced 01 Principal (cod+des)",
        "Proced 01 Principal (cod+des)_cod",
        "Proced 01 Principal (cod+des)_desc"
    ]
].head(3)

,Diag 01 Principal (cod+des),Diag 01 Principal (cod+des)_cod,Diag 01 Principal (cod+des)_desc,Proced 01 Principal (cod+des),Proced 01 Principal (cod+des)_cod,Proced 01 Principal (cod+des)_desc
0,A41.8 - Otras septicemias especificadas,A41.8,Otras septicemias especificadas,"86.28 - DESBRIDAMIENTO HERIDA,INFECCION O QUEM...",86.28,"DESBRIDAMIENTO HERIDA,INFECCION O QUEMADURA NO..."
1,"U07.1 - COVID-19, virus identificado",U07.1,"COVID-19, virus identificado",31.1 - TRAQUEOSTOMIA TEMPORAL,31.1,TRAQUEOSTOMIA TEMPORAL
2,K56.5 - Adherencias [bridas] intestinales con ...,K56.5,Adherencias [bridas] intestinales con obstrucción,"86.22 - DESBRIDAMIENTO HERIDA,INFECCION O QUEM...",86.22,"DESBRIDAMIENTO HERIDA,INFECCION O QUEMADURA ES..."

# Comparacion de filas

In [86]:
print("Filas df_work (original):", df_work.shape[0])
print("Filas df_diag_split (procesado):", df_diag_split.shape[0])

Filas df_work (original): 14561
Filas df_diag_split (procesado): 14561

In [87]:
df_work.shape[0] == df_diag_split.shape[0]

True

In [88]:
cols_cod = [col for col in df_diag_split.columns if col.endswith("_cod")]
cols_desc = [col for col in df_diag_split.columns if col.endswith("_desc")]

print("Columnas _cod:", len(cols_cod))
print("Columnas _desc:", len(cols_desc))

Columnas _cod: 65
Columnas _desc: 65

In [89]:
errores_nombres = []

for col in cols_cod + cols_desc:
    
    if "_cod" in col:
        base = col.replace("_cod", "")
    elif "_desc" in col:
        base = col.replace("_desc", "")
    
    if base not in df_diag_split.columns:
        errores_nombres.append(col)

errores_nombres

[]

In [90]:
sorted(cols_cod[:10])

['Diag 01 Principal (cod+des)_cod',
 'Diag 02 Secundario (cod+des)_cod',
 'Diag 03 Secundario (cod+des)_cod',
 'Diag 04 Secundario (cod+des)_cod',
 'Diag 05 Secundario (cod+des)_cod',
 'Diag 06 Secundario (cod+des)_cod',
 'Diag 07 Secundario (cod+des)_cod',
 'Diag 08 Secundario (cod+des)_cod',
 'Diag 09 Secundario (cod+des)_cod',
 'Diag 10 Secundario (cod+des)_cod']

In [91]:
cobertura_diag = {}

for col in cols_diag:
    col_cod = f"{col}_cod"
    no_nulos = df_diag_split[col_cod].notna().sum()
    
    cobertura_diag[col] = no_nulos

cobertura_diag

{'Diag 01 Principal (cod+des)': np.int64(14561),
 'Diag 02 Secundario (cod+des)': np.int64(13352),
 'Diag 03 Secundario (cod+des)': np.int64(11874),
 'Diag 04 Secundario (cod+des)': np.int64(10434),
 'Diag 05 Secundario (cod+des)': np.int64(9190),
 'Diag 06 Secundario (cod+des)': np.int64(8167),
 'Diag 07 Secundario (cod+des)': np.int64(7153),
 'Diag 08 Secundario (cod+des)': np.int64(5977),
 'Diag 09 Secundario (cod+des)': np.int64(4842),
 'Diag 10 Secundario (cod+des)': np.int64(3865),
 'Diag 11 Secundario (cod+des)': np.int64(2987),
 'Diag 12 Secundario (cod+des)': np.int64(2323),
 'Diag 13 Secundario (cod+des)': np.int64(1800),
 'Diag 14 Secundario (cod+des)': np.int64(1431),
 'Diag 15 Secundario (cod+des)': np.int64(1138),
 'Diag 16 Secundario (cod+des)': np.int64(923),
 'Diag 17 Secundario (cod+des)': np.int64(759),
 'Diag 18 Secundario (cod+des)': np.int64(623),
 'Diag 19 Secundario (cod+des)': np.int64(515),
 'Diag 20 Secundario (cod+des)': np.int64(429),
 'Diag 21 Secundario (cod+des)': np.int64(353),
 'Diag 22 Secundario (cod+des)': np.int64(304),
 'Diag 23 Secundario (cod+des)': np.int64(253),
 'Diag 24 Secundario (cod+des)': np.int64(215),
 'Diag 25 Secundario (cod+des)': np.int64(194),
 'Diag 26 Secundario (cod+des)': np.int64(154),
 'Diag 27 Secundario (cod+des)': np.int64(130),
 'Diag 28 Secundario (cod+des)': np.int64(110),
 'Diag 29 Secundario (cod+des)': np.int64(93),
 'Diag 30 Secundario (cod+des)': np.int64(76),
 'Diag 31 Secundario (cod+des)': np.int64(67),
 'Diag 32 Secundario (cod+des)': np.int64(57),
 'Diag 33 Secundario (cod+des)': np.int64(43),
 'Diag 34 Secundario (cod+des)': np.int64(40),
 'Diag 35 Secundario (cod+des)': np.int64(28)}

In [92]:
sorted(cobertura_diag.items(), key=lambda x: x[0])

[('Diag 01 Principal (cod+des)', np.int64(14561)),
 ('Diag 02 Secundario (cod+des)', np.int64(13352)),
 ('Diag 03 Secundario (cod+des)', np.int64(11874)),
 ('Diag 04 Secundario (cod+des)', np.int64(10434)),
 ('Diag 05 Secundario (cod+des)', np.int64(9190)),
 ('Diag 06 Secundario (cod+des)', np.int64(8167)),
 ('Diag 07 Secundario (cod+des)', np.int64(7153)),
 ('Diag 08 Secundario (cod+des)', np.int64(5977)),
 ('Diag 09 Secundario (cod+des)', np.int64(4842)),
 ('Diag 10 Secundario (cod+des)', np.int64(3865)),
 ('Diag 11 Secundario (cod+des)', np.int64(2987)),
 ('Diag 12 Secundario (cod+des)', np.int64(2323)),
 ('Diag 13 Secundario (cod+des)', np.int64(1800)),
 ('Diag 14 Secundario (cod+des)', np.int64(1431)),
 ('Diag 15 Secundario (cod+des)', np.int64(1138)),
 ('Diag 16 Secundario (cod+des)', np.int64(923)),
 ('Diag 17 Secundario (cod+des)', np.int64(759)),
 ('Diag 18 Secundario (cod+des)', np.int64(623)),
 ('Diag 19 Secundario (cod+des)', np.int64(515)),
 ('Diag 20 Secundario (cod+des)', np.int64(429)),
 ('Diag 21 Secundario (cod+des)', np.int64(353)),
 ('Diag 22 Secundario (cod+des)', np.int64(304)),
 ('Diag 23 Secundario (cod+des)', np.int64(253)),
 ('Diag 24 Secundario (cod+des)', np.int64(215)),
 ('Diag 25 Secundario (cod+des)', np.int64(194)),
 ('Diag 26 Secundario (cod+des)', np.int64(154)),
 ('Diag 27 Secundario (cod+des)', np.int64(130)),
 ('Diag 28 Secundario (cod+des)', np.int64(110)),
 ('Diag 29 Secundario (cod+des)', np.int64(93)),
 ('Diag 30 Secundario (cod+des)', np.int64(76)),
 ('Diag 31 Secundario (cod+des)', np.int64(67)),
 ('Diag 32 Secundario (cod+des)', np.int64(57)),
 ('Diag 33 Secundario (cod+des)', np.int64(43)),
 ('Diag 34 Secundario (cod+des)', np.int64(40)),
 ('Diag 35 Secundario (cod+des)', np.int64(28))]

In [93]:
cobertura_proc = {}

for col in cols_proc:
    col_cod = f"{col}_cod"
    no_nulos = df_diag_split[col_cod].notna().sum()
    
    cobertura_proc[col] = no_nulos

cobertura_proc

{'Proced 01 Principal (cod+des)': np.int64(14561),
 'Proced 02 Secundario (cod+des)': np.int64(14427),
 'Proced 03 Secundario (cod+des)': np.int64(14219),
 'Proced 04 Secundario (cod+des)': np.int64(13956),
 'Proced 05 Secundario (cod+des)': np.int64(13599),
 'Proced 06 Secundario (cod+des)': np.int64(13081),
 'Proced 07 Secundario (cod+des)': np.int64(12426),
 'Proced 08 Secundario (cod+des)': np.int64(11549),
 'Proced 09 Secundario (cod+des)': np.int64(10624),
 'Proced 10 Secundario (cod+des)': np.int64(9579),
 'Proced 11 Secundario (cod+des)': np.int64(8470),
 'Proced 12 Secundario (cod+des)': np.int64(7220),
 'Proced 13 Secundario (cod+des)': np.int64(6115),
 'Proced 14 Secundario (cod+des)': np.int64(5202),
 'Proced 15 Secundario (cod+des)': np.int64(4450),
 'Proced 16 Secundario (cod+des)': np.int64(3894),
 'Proced 17 Secundario (cod+des)': np.int64(3485),
 'Proced 18 Secundario (cod+des)': np.int64(3170),
 'Proced 19 Secundario (cod+des)': np.int64(2894),
 'Proced 20 Secundario (cod+des)': np.int64(2648),
 'Proced 21 Secundario (cod+des)': np.int64(2441),
 'Proced 22 Secundario (cod+des)': np.int64(2240),
 'Proced 23 Secundario (cod+des)': np.int64(2065),
 'Proced 24 Secundario (cod+des)': np.int64(1895),
 'Proced 25 Secundario (cod+des)': np.int64(1710),
 'Proced 26 Secundario (cod+des)': np.int64(1572),
 'Proced 27 Secundario (cod+des)': np.int64(1423),
 'Proced 28 Secundario (cod+des)': np.int64(1300),
 'Proced 29 Secundario (cod+des)': np.int64(1182),
 'Proced 30 Secundario (cod+des)': np.int64(1063)}

In [94]:
inconsistencias = []

for col in cols_diag + cols_proc:
    
    cod = df_diag_split[f"{col}_cod"]
    desc = df_diag_split[f"{col}_desc"]
    
    # casos raros
    mask_cod_vacio_desc_lleno = cod.isna() & desc.notna()
    mask_cod_lleno_desc_vacio = cod.notna() & desc.isna()
    
    if mask_cod_vacio_desc_lleno.sum() > 0 or mask_cod_lleno_desc_vacio.sum() > 0:
        inconsistencias.append(col)

inconsistencias

[]

# Preparar catalogos

In [96]:
cie10_codigos = set(cie10["Código"].dropna().astype(str).str.strip())
cie9_codigos = set(cie9["Código"].dropna().astype(str).str.strip())

In [97]:
validacion_diag = {}

for col in cols_diag[:5]:  # muestra
    cod_col = f"{col}_cod"
    
    codigos = df_diag_split[cod_col].dropna().astype(str).str.strip()
    
    validos = codigos.isin(cie10_codigos).sum()
    total = len(codigos)
    
    validacion_diag[col] = {
        "total": total,
        "validos": validos,
        "porcentaje": validos / total if total > 0 else 0
    }

validacion_diag

{'Diag 01 Principal (cod+des)': {'total': 14561,
  'validos': np.int64(14561),
  'porcentaje': np.float64(1.0)},
 'Diag 02 Secundario (cod+des)': {'total': 13352,
  'validos': np.int64(13320),
  'porcentaje': np.float64(0.9976033553025764)},
 'Diag 03 Secundario (cod+des)': {'total': 11874,
  'validos': np.int64(11847),
  'porcentaje': np.float64(0.9977261243052047)},
 'Diag 04 Secundario (cod+des)': {'total': 10434,
  'validos': np.int64(10400),
  'porcentaje': np.float64(0.9967414222733372)},
 'Diag 05 Secundario (cod+des)': {'total': 9190,
  'validos': np.int64(9163),
  'porcentaje': np.float64(0.9970620239390642)}}

In [98]:
validacion_proc = {}

for col in cols_proc[:5]:
    cod_col = f"{col}_cod"
    
    codigos = df_diag_split[cod_col].dropna().astype(str).str.strip()
    
    validos = codigos.isin(cie9_codigos).sum()
    total = len(codigos)
    
    validacion_proc[col] = {
        "total": total,
        "validos": validos,
        "porcentaje": validos / total if total > 0 else 0
    }

validacion_proc

{'Proced 01 Principal (cod+des)': {'total': 14561,
  'validos': np.int64(14074),
  'porcentaje': np.float64(0.9665544948835931)},
 'Proced 02 Secundario (cod+des)': {'total': 14427,
  'validos': np.int64(13788),
  'porcentaje': np.float64(0.9557080474111042)},
 'Proced 03 Secundario (cod+des)': {'total': 14219,
  'validos': np.int64(12813),
  'porcentaje': np.float64(0.9011182220971939)},
 'Proced 04 Secundario (cod+des)': {'total': 13956,
  'validos': np.int64(12919),
  'porcentaje': np.float64(0.925695041559186)},
 'Proced 05 Secundario (cod+des)': {'total': 13599,
  'validos': np.int64(13334),
  'porcentaje': np.float64(0.980513273034782)}}

In [99]:
codigos_invalidos_diag = set()

for col in cols_diag[:5]:
    codigos = df_diag_split[f"{col}_cod"].dropna().astype(str).str.strip()
    
    invalidos = codigos[~codigos.isin(cie10_codigos)]
    codigos_invalidos_diag.update(invalidos)

list(codigos_invalidos_diag)[:10]

['U09.9', 'U08.9']

In [100]:
cols_originales = [col for col in df_diag_split.columns if "(cod+des)" in col]

df_model = df_diag_split.drop(columns=cols_originales)

# BLOQUE K

In [101]:
completitud_diag = []

total_filas = df_diag_split.shape[0]

for col in cols_diag:
    col_cod = f"{col}_cod"
    
    no_nulos = df_diag_split[col_cod].notna().sum()
    nulos = total_filas - no_nulos
    
    completitud_diag.append({
        "columna": col,
        "no_nulos": no_nulos,
        "nulos": nulos,
        "pct_no_nulos": no_nulos / total_filas,
        "pct_nulos": nulos / total_filas
    })

import pandas as pd
df_completitud_diag = pd.DataFrame(completitud_diag)

df_completitud_diag

                         columna  no_nulos  nulos  pct_no_nulos  pct_nulos
0    Diag 01 Principal (cod+des)     14561      0      1.000000   0.000000
1   Diag 02 Secundario (cod+des)     13352   1209      0.916970   0.083030
2   Diag 03 Secundario (cod+des)     11874   2687      0.815466   0.184534
3   Diag 04 Secundario (cod+des)     10434   4127      0.716572   0.283428
4   Diag 05 Secundario (cod+des)      9190   5371      0.631138   0.368862
5   Diag 06 Secundario (cod+des)      8167   6394      0.560882   0.439118
6   Diag 07 Secundario (cod+des)      7153   7408      0.491244   0.508756
7   Diag 08 Secundario (cod+des)      5977   8584      0.410480   0.589520
8   Diag 09 Secundario (cod+des)      4842   9719      0.332532   0.667468
9   Diag 10 Secundario (cod+des)      3865  10696      0.265435   0.734565
10  Diag 11 Secundario (cod+des)      2987  11574      0.205137   0.794863
11  Diag 12 Secundario (cod+des)      2323  12238      0.159536   0.840464
12  Diag 13 Secundario (cod+des)      1800  12761      0.123618   0.876382
13  Diag 14 Secundario (cod+des)      1431  13130      0.098276   0.901724
14  Diag 15 Secundario (cod+des)      1138  13423      0.078154   0.921846
15  Diag 16 Secundario (cod+des)       923  13638      0.063389   0.936611
16  Diag 17 Secundario (cod+des)       759  13802      0.052126   0.947874
17  Diag 18 Secundario (cod+des)       623  13938      0.042786   0.957214
18  Diag 19 Secundario (cod+des)       515  14046      0.035368   0.964632
19  Diag 20 Secundario (cod+des)       429  14132      0.029462   0.970538
20  Diag 21 Secundario (cod+des)       353  14208      0.024243   0.975757
21  Diag 22 Secundario (cod+des)       304  14257      0.020878   0.979122
22  Diag 23 Secundario (cod+des)       253  14308      0.017375   0.982625
23  Diag 24 Secundario (cod+des)       215  14346      0.014765   0.985235
24  Diag 25 Secundario (cod+des)       194  14367      0.013323   0.986677
25  Diag 26 Secundario (cod+des)       154  14407      0.010576   0.989424
26  Diag 27 Secundario (cod+des)       130  14431      0.008928   0.991072
27  Diag 28 Secundario (cod+des)       110  14451      0.007554   0.992446
28  Diag 29 Secundario (cod+des)        93  14468      0.006387   0.993613
29  Diag 30 Secundario (cod+des)        76  14485      0.005219   0.994781
30  Diag 31 Secundario (cod+des)        67  14494      0.004601   0.995399
31  Diag 32 Secundario (cod+des)        57  14504      0.003915   0.996085
32  Diag 33 Secundario (cod+des)        43  14518      0.002953   0.997047
33  Diag 34 Secundario (cod+des)        40  14521      0.002747   0.997253
34  Diag 35 Secundario (cod+des)        28  14533      0.001923   0.998077

In [102]:
df_completitud_diag = df_completitud_diag.sort_values(by="columna")
df_completitud_diag.head(15)

                         columna  no_nulos  nulos  pct_no_nulos  pct_nulos
0    Diag 01 Principal (cod+des)     14561      0      1.000000   0.000000
1   Diag 02 Secundario (cod+des)     13352   1209      0.916970   0.083030
2   Diag 03 Secundario (cod+des)     11874   2687      0.815466   0.184534
3   Diag 04 Secundario (cod+des)     10434   4127      0.716572   0.283428
4   Diag 05 Secundario (cod+des)      9190   5371      0.631138   0.368862
5   Diag 06 Secundario (cod+des)      8167   6394      0.560882   0.439118
6   Diag 07 Secundario (cod+des)      7153   7408      0.491244   0.508756
7   Diag 08 Secundario (cod+des)      5977   8584      0.410480   0.589520
8   Diag 09 Secundario (cod+des)      4842   9719      0.332532   0.667468
9   Diag 10 Secundario (cod+des)      3865  10696      0.265435   0.734565
10  Diag 11 Secundario (cod+des)      2987  11574      0.205137   0.794863
11  Diag 12 Secundario (cod+des)      2323  12238      0.159536   0.840464
12  Diag 13 Secundario (cod+des)      1800  12761      0.123618   0.876382
13  Diag 14 Secundario (cod+des)      1431  13130      0.098276   0.901724
14  Diag 15 Secundario (cod+des)      1138  13423      0.078154   0.921846

In [103]:
df_completitud_diag.head(20)

                         columna  no_nulos  nulos  pct_no_nulos  pct_nulos
0    Diag 01 Principal (cod+des)     14561      0      1.000000   0.000000
1   Diag 02 Secundario (cod+des)     13352   1209      0.916970   0.083030
2   Diag 03 Secundario (cod+des)     11874   2687      0.815466   0.184534
3   Diag 04 Secundario (cod+des)     10434   4127      0.716572   0.283428
4   Diag 05 Secundario (cod+des)      9190   5371      0.631138   0.368862
5   Diag 06 Secundario (cod+des)      8167   6394      0.560882   0.439118
6   Diag 07 Secundario (cod+des)      7153   7408      0.491244   0.508756
7   Diag 08 Secundario (cod+des)      5977   8584      0.410480   0.589520
8   Diag 09 Secundario (cod+des)      4842   9719      0.332532   0.667468
9   Diag 10 Secundario (cod+des)      3865  10696      0.265435   0.734565
10  Diag 11 Secundario (cod+des)      2987  11574      0.205137   0.794863
11  Diag 12 Secundario (cod+des)      2323  12238      0.159536   0.840464
12  Diag 13 Secundario (cod+des)      1800  12761      0.123618   0.876382
13  Diag 14 Secundario (cod+des)      1431  13130      0.098276   0.901724
14  Diag 15 Secundario (cod+des)      1138  13423      0.078154   0.921846
15  Diag 16 Secundario (cod+des)       923  13638      0.063389   0.936611
16  Diag 17 Secundario (cod+des)       759  13802      0.052126   0.947874
17  Diag 18 Secundario (cod+des)       623  13938      0.042786   0.957214
18  Diag 19 Secundario (cod+des)       515  14046      0.035368   0.964632
19  Diag 20 Secundario (cod+des)       429  14132      0.029462   0.970538

In [104]:
df_completitud_diag.tail(10)

                         columna  no_nulos  nulos  pct_no_nulos  pct_nulos
25  Diag 26 Secundario (cod+des)       154  14407      0.010576   0.989424
26  Diag 27 Secundario (cod+des)       130  14431      0.008928   0.991072
27  Diag 28 Secundario (cod+des)       110  14451      0.007554   0.992446
28  Diag 29 Secundario (cod+des)        93  14468      0.006387   0.993613
29  Diag 30 Secundario (cod+des)        76  14485      0.005219   0.994781
30  Diag 31 Secundario (cod+des)        67  14494      0.004601   0.995399
31  Diag 32 Secundario (cod+des)        57  14504      0.003915   0.996085
32  Diag 33 Secundario (cod+des)        43  14518      0.002953   0.997047
33  Diag 34 Secundario (cod+des)        40  14521      0.002747   0.997253
34  Diag 35 Secundario (cod+des)        28  14533      0.001923   0.998077

In [105]:
completitud_proc = []

total_filas = df_diag_split.shape[0]

for col in cols_proc:
    col_cod = f"{col}_cod"
    
    no_nulos = df_diag_split[col_cod].notna().sum()
    nulos = total_filas - no_nulos
    
    completitud_proc.append({
        "columna": col,
        "no_nulos": no_nulos,
        "nulos": nulos,
        "pct_no_nulos": no_nulos / total_filas,
        "pct_nulos": nulos / total_filas
    })

import pandas as pd
df_completitud_proc = pd.DataFrame(completitud_proc)

df_completitud_proc

                           columna  no_nulos  nulos  pct_no_nulos  pct_nulos
0    Proced 01 Principal (cod+des)     14561      0      1.000000   0.000000
1   Proced 02 Secundario (cod+des)     14427    134      0.990797   0.009203
2   Proced 03 Secundario (cod+des)     14219    342      0.976513   0.023487
3   Proced 04 Secundario (cod+des)     13956    605      0.958451   0.041549
4   Proced 05 Secundario (cod+des)     13599    962      0.933933   0.066067
5   Proced 06 Secundario (cod+des)     13081   1480      0.898359   0.101641
6   Proced 07 Secundario (cod+des)     12426   2135      0.853375   0.146625
7   Proced 08 Secundario (cod+des)     11549   3012      0.793146   0.206854
8   Proced 09 Secundario (cod+des)     10624   3937      0.729620   0.270380
9   Proced 10 Secundario (cod+des)      9579   4982      0.657853   0.342147
10  Proced 11 Secundario (cod+des)      8470   6091      0.581691   0.418309
11  Proced 12 Secundario (cod+des)      7220   7341      0.495845   0.504155
12  Proced 13 Secundario (cod+des)      6115   8446      0.419957   0.580043
13  Proced 14 Secundario (cod+des)      5202   9359      0.357256   0.642744
14  Proced 15 Secundario (cod+des)      4450  10111      0.305611   0.694389
15  Proced 16 Secundario (cod+des)      3894  10667      0.267427   0.732573
16  Proced 17 Secundario (cod+des)      3485  11076      0.239338   0.760662
17  Proced 18 Secundario (cod+des)      3170  11391      0.217705   0.782295
18  Proced 19 Secundario (cod+des)      2894  11667      0.198750   0.801250
19  Proced 20 Secundario (cod+des)      2648  11913      0.181856   0.818144
20  Proced 21 Secundario (cod+des)      2441  12120      0.167640   0.832360
21  Proced 22 Secundario (cod+des)      2240  12321      0.153836   0.846164
22  Proced 23 Secundario (cod+des)      2065  12496      0.141817   0.858183
23  Proced 24 Secundario (cod+des)      1895  12666      0.130142   0.869858
24  Proced 25 Secundario (cod+des)      1710  12851      0.117437   0.882563
25  Proced 26 Secundario (cod+des)      1572  12989      0.107960   0.892040
26  Proced 27 Secundario (cod+des)      1423  13138      0.097727   0.902273
27  Proced 28 Secundario (cod+des)      1300  13261      0.089280   0.910720
28  Proced 29 Secundario (cod+des)      1182  13379      0.081176   0.918824
29  Proced 30 Secundario (cod+des)      1063  13498      0.073003   0.926997

In [106]:
df_completitud_proc = df_completitud_proc.sort_values(by="columna")

df_completitud_proc.head(15)

                           columna  no_nulos  nulos  pct_no_nulos  pct_nulos
0    Proced 01 Principal (cod+des)     14561      0      1.000000   0.000000
1   Proced 02 Secundario (cod+des)     14427    134      0.990797   0.009203
2   Proced 03 Secundario (cod+des)     14219    342      0.976513   0.023487
3   Proced 04 Secundario (cod+des)     13956    605      0.958451   0.041549
4   Proced 05 Secundario (cod+des)     13599    962      0.933933   0.066067
5   Proced 06 Secundario (cod+des)     13081   1480      0.898359   0.101641
6   Proced 07 Secundario (cod+des)     12426   2135      0.853375   0.146625
7   Proced 08 Secundario (cod+des)     11549   3012      0.793146   0.206854
8   Proced 09 Secundario (cod+des)     10624   3937      0.729620   0.270380
9   Proced 10 Secundario (cod+des)      9579   4982      0.657853   0.342147
10  Proced 11 Secundario (cod+des)      8470   6091      0.581691   0.418309
11  Proced 12 Secundario (cod+des)      7220   7341      0.495845   0.504155
12  Proced 13 Secundario (cod+des)      6115   8446      0.419957   0.580043
13  Proced 14 Secundario (cod+des)      5202   9359      0.357256   0.642744
14  Proced 15 Secundario (cod+des)      4450  10111      0.305611   0.694389

In [107]:
df_completitud_proc.head(20)

                           columna  no_nulos  nulos  pct_no_nulos  pct_nulos
0    Proced 01 Principal (cod+des)     14561      0      1.000000   0.000000
1   Proced 02 Secundario (cod+des)     14427    134      0.990797   0.009203
2   Proced 03 Secundario (cod+des)     14219    342      0.976513   0.023487
3   Proced 04 Secundario (cod+des)     13956    605      0.958451   0.041549
4   Proced 05 Secundario (cod+des)     13599    962      0.933933   0.066067
5   Proced 06 Secundario (cod+des)     13081   1480      0.898359   0.101641
6   Proced 07 Secundario (cod+des)     12426   2135      0.853375   0.146625
7   Proced 08 Secundario (cod+des)     11549   3012      0.793146   0.206854
8   Proced 09 Secundario (cod+des)     10624   3937      0.729620   0.270380
9   Proced 10 Secundario (cod+des)      9579   4982      0.657853   0.342147
10  Proced 11 Secundario (cod+des)      8470   6091      0.581691   0.418309
11  Proced 12 Secundario (cod+des)      7220   7341      0.495845   0.504155
12  Proced 13 Secundario (cod+des)      6115   8446      0.419957   0.580043
13  Proced 14 Secundario (cod+des)      5202   9359      0.357256   0.642744
14  Proced 15 Secundario (cod+des)      4450  10111      0.305611   0.694389
15  Proced 16 Secundario (cod+des)      3894  10667      0.267427   0.732573
16  Proced 17 Secundario (cod+des)      3485  11076      0.239338   0.760662
17  Proced 18 Secundario (cod+des)      3170  11391      0.217705   0.782295
18  Proced 19 Secundario (cod+des)      2894  11667      0.198750   0.801250
19  Proced 20 Secundario (cod+des)      2648  11913      0.181856   0.818144

In [108]:
df_completitud_proc.tail(10)

                           columna  no_nulos  nulos  pct_no_nulos  pct_nulos
20  Proced 21 Secundario (cod+des)      2441  12120      0.167640   0.832360
21  Proced 22 Secundario (cod+des)      2240  12321      0.153836   0.846164
22  Proced 23 Secundario (cod+des)      2065  12496      0.141817   0.858183
23  Proced 24 Secundario (cod+des)      1895  12666      0.130142   0.869858
24  Proced 25 Secundario (cod+des)      1710  12851      0.117437   0.882563
25  Proced 26 Secundario (cod+des)      1572  12989      0.107960   0.892040
26  Proced 27 Secundario (cod+des)      1423  13138      0.097727   0.902273
27  Proced 28 Secundario (cod+des)      1300  13261      0.089280   0.910720
28  Proced 29 Secundario (cod+des)      1182  13379      0.081176   0.918824
29  Proced 30 Secundario (cod+des)      1063  13498      0.073003   0.926997

### Top 10 Diagnosticos

In [118]:
cols_diag_top10 = [f"{col}_cod" for col in cols_diag[:10]]

pct_no_nulos_diag = df_diag_split[cols_diag_top10].notna().mean().mean()
pct_nulos_diag = 1 - pct_no_nulos_diag

### Top 15 Procedimientos

In [119]:
cols_proc_top15 = [f"{col}_cod" for col in cols_proc[:15]]

pct_no_nulos_proc = df_diag_split[cols_proc_top15].notna().mean().mean()
pct_nulos_proc = 1 - pct_no_nulos_proc

### Demograficas

In [126]:
cols_demo_reales = ["Edad en años", "Sexo (Desc)"]

for col in cols_demo_reales:
    print(col, "->", col in df_diag_split.columns)

Edad en años -> True
Sexo (Desc) -> True

In [127]:
pct_no_nulos_demo = df_diag_split[cols_demo_reales].notna().mean().mean()
pct_nulos_demo = 1 - pct_no_nulos_demo

In [128]:
"GRD" in df_diag_split.columns

True

In [129]:
import pandas as pd

resumen_bloques = pd.DataFrame({
    "bloque": ["Diagnósticos", "Procedimientos", "Demográficos", "Target"],
    "pct_no_nulos": [
        pct_no_nulos_diag,
        pct_no_nulos_proc,
        pct_no_nulos_demo,
        pct_no_nulos_target
    ],
    "pct_nulos": [
        pct_nulos_diag,
        pct_nulos_proc,
        pct_nulos_demo,
        pct_nulos_target
    ]
})

resumen_bloques

           bloque  pct_no_nulos  pct_nulos
0    Diagnósticos      0.614072   0.385928
1  Procedimientos      0.730160   0.269840
2    Demográficos      1.000000   0.000000
3          Target      1.000000   0.000000

In [130]:
pct_nulos_por_col = df_diag_split.isna().mean()

In [131]:
umbral_95 = 0.95
umbral_99 = 0.99

In [132]:
cols_muy_vacias_95 = pct_nulos_por_col[pct_nulos_por_col > umbral_95].index.tolist()
cols_muy_vacias_99 = pct_nulos_por_col[pct_nulos_por_col > umbral_99].index.tolist()

In [133]:
len(cols_muy_vacias_95), len(cols_muy_vacias_99)

(54, 27)

In [134]:
cols_muy_vacias_95[:20]

['Diag 18 Secundario (cod+des)',
 'Diag 19 Secundario (cod+des)',
 'Diag 20 Secundario (cod+des)',
 'Diag 21 Secundario (cod+des)',
 'Diag 22 Secundario (cod+des)',
 'Diag 23 Secundario (cod+des)',
 'Diag 24 Secundario (cod+des)',
 'Diag 25 Secundario (cod+des)',
 'Diag 26 Secundario (cod+des)',
 'Diag 27 Secundario (cod+des)',
 'Diag 28 Secundario (cod+des)',
 'Diag 29 Secundario (cod+des)',
 'Diag 30 Secundario (cod+des)',
 'Diag 31 Secundario (cod+des)',
 'Diag 32 Secundario (cod+des)',
 'Diag 33 Secundario (cod+des)',
 'Diag 34 Secundario (cod+des)',
 'Diag 35 Secundario (cod+des)',
 'Diag 18 Secundario (cod+des)_cod',
 'Diag 18 Secundario (cod+des)_desc']

In [135]:
cols_muy_vacias_99[:20]

['Diag 27 Secundario (cod+des)',
 'Diag 28 Secundario (cod+des)',
 'Diag 29 Secundario (cod+des)',
 'Diag 30 Secundario (cod+des)',
 'Diag 31 Secundario (cod+des)',
 'Diag 32 Secundario (cod+des)',
 'Diag 33 Secundario (cod+des)',
 'Diag 34 Secundario (cod+des)',
 'Diag 35 Secundario (cod+des)',
 'Diag 27 Secundario (cod+des)_cod',
 'Diag 27 Secundario (cod+des)_desc',
 'Diag 28 Secundario (cod+des)_cod',
 'Diag 28 Secundario (cod+des)_desc',
 'Diag 29 Secundario (cod+des)_cod',
 'Diag 29 Secundario (cod+des)_desc',
 'Diag 30 Secundario (cod+des)_cod',
 'Diag 30 Secundario (cod+des)_desc',
 'Diag 31 Secundario (cod+des)_cod',
 'Diag 31 Secundario (cod+des)_desc',
 'Diag 32 Secundario (cod+des)_cod']

Durante la fase de preparación y análisis estructural de los datos, se tomaron las siguientes decisiones metodológicas con el objetivo de asegurar la calidad, consistencia y trazabilidad del dataset:

Se creó una copia de trabajo del dataset original, con el fin de preservar la integridad de los datos fuente y permitir iteraciones seguras durante el proceso de limpieza y transformación.
Se identificó que el valor "-" en las columnas clínicas (diagnósticos y procedimientos) representaba ausencia de información, por lo que fue tratado como valor faltante (NaN) para su correcto manejo en el análisis.
Se realizó la separación de columnas compuestas que contenían tanto código como descripción (formato cod+des) en dos variables independientes, permitiendo un tratamiento más preciso de la información clínica.
Se verificó que el proceso de transformación no generó pérdida de registros, asegurando la consistencia del número de filas entre el dataset original y el dataset transformado.
Se evaluó la completitud de los datos tanto a nivel de posición (diagnósticos y procedimientos) como a nivel de bloque (diagnósticos, procedimientos, variables demográficas y variable objetivo), permitiendo caracterizar la densidad real de la información disponible.

A partir del análisis exploratorio y estructural del dataset, se identificaron las siguientes limitaciones y desafíos que deberán ser considerados en las etapas posteriores de modelado:

Se observa una alta sparsity en las posiciones avanzadas de diagnósticos secundarios, donde la completitud disminuye significativamente a medida que aumenta la posición, generando una gran cantidad de valores faltantes en columnas profundas.
Aunque los procedimientos presentan una mayor densidad relativa en comparación con los diagnósticos, también exhiben una disminución progresiva de completitud en posiciones avanzadas, lo que introduce heterogeneidad en la disponibilidad de información clínica.
El dataset original contenía múltiples columnas compuestas en formato código + descripción, lo que implicó un proceso adicional de transformación y puede introducir complejidad en la representación de variables.
Existe una gran cantidad de columnas altamente vacías (sobre 95% y 99% de valores nulos), lo que puede afectar negativamente el rendimiento de ciertos modelos si no se maneja adecuadamente la selección o reducción de variables.
La estructura del dataset, basada en posiciones (diagnósticos y procedimientos secuenciales), puede no ser la representación óptima para modelos de aprendizaje automático, por lo que podría requerirse una transformación hacia representaciones más compactas o informativas.
Se anticipa la necesidad de aplicar técnicas de reducción de dimensionalidad o selección de variables, con el fin de mitigar el efecto de la alta dispersión y mejorar la eficiencia del modelado.
Finalmente, aunque las variables demográficas y la variable objetivo presentan completitud total, su capacidad explicativa por sí sola es limitada, por lo que el desempeño del modelo dependerá fuertemente de cómo se representen los bloques clínicos.

En esta fase se realizó la preparación estructural del dataset, donde se transformaron los valores faltantes representados como "-" en valores nulos reales y se separaron las variables clínicas originalmente compuestas en código y descripción, manteniendo la lógica posicional del registro. Asimismo, se trabajó sobre una copia del dataset original, asegurando la integridad de los datos sin pérdida de filas durante el proceso de transformación.

A partir del análisis exploratorio, se confirmó que el dataset presenta una estructura jerárquica en los bloques clínicos, donde los diagnósticos muestran una disminución progresiva en su completitud a medida que aumenta la posición, mientras que los procedimientos presentan una mayor densidad relativa en múltiples niveles. También se validó que las variables demográficas y la variable objetivo se encuentran completamente disponibles.

Sin embargo, persisten desafíos relevantes asociados a la alta sparsity en posiciones avanzadas, la existencia de múltiples columnas altamente vacías y la necesidad de definir una representación adecuada para los bloques clínicos, dado que la estructura posicional no necesariamente es óptima para el modelado.

En este contexto, el dataset queda correctamente preparado y comprendido a nivel estructural, permitiendo avanzar hacia la siguiente fase de ingeniería de variables, donde se definirán estrategias para representar de manera eficiente la información clínica y maximizar la capacidad predictiva del modelo.

In [136]:
df_model = pd.DataFrame(index=df_diag_split.index)

In [141]:
df_model = pd.DataFrame(index=df_diag_split.index)

df_model["n_diag"] = df_diag_split[cols_diag_top10].notna().sum(axis=1)
df_model["n_proc"] = df_diag_split[cols_proc_top15].notna().sum(axis=1)

df_model["diag_principal"] = df_diag_split["Diag 01 Principal (cod+des)_cod"]
df_model["proc_principal"] = df_diag_split["Proced 01 Principal (cod+des)_cod"]

df_model["diag_principal"] = (
    df_model["diag_principal"]
    .astype(str)
    .str.strip()
    .str.upper()
)

df_model["proc_principal"] = (
    df_model["proc_principal"]
    .astype(str)
    .str.strip()
    .str.upper()
)

df_model["has_proc"] = (df_model["n_proc"] > 0).astype(int)
df_model["multi_diag"] = (df_model["n_diag"] > 1).astype(int)

In [142]:
df_model.head()

   n_diag  n_proc diag_principal proc_principal  has_proc  multi_diag
0      10      15          A41.8          86.28         1           1
1      10      15          U07.1           31.1         1           1
2      10      15          K56.5          86.22         1           1
3      10      15          K76.8          54.19         1           1
4      10      15          T81.0          54.11         1           1

In [143]:
df_model.isna().sum()

n_diag            0
n_proc            0
diag_principal    0
proc_principal    0
has_proc          0
multi_diag        0
dtype: int64

In [144]:
df_model[["n_diag", "n_proc"]].describe()

             n_diag        n_proc
count  14561.000000  14561.000000
mean       6.140718     10.952407
std        3.197834      3.797176
min        1.000000      1.000000
25%        3.000000      8.000000
50%        6.000000     11.000000
75%       10.000000     15.000000
max       10.000000     15.000000

In [145]:
df_model[["n_diag", "n_proc"]].value_counts().head(10)

n_diag  n_proc
10      15        2341
8       15         323
10      13         315
7       15         314
9       15         308
6       15         295
10      12         291
        14         282
5       15         259
10      11         247
Name: count, dtype: int64

In [146]:
fila = 0

print("Diagnósticos top 10 fila 0:")
print(df_diag_split[cols_diag_top10].iloc[fila])

print("\nProcedimientos top 15 fila 0:")
print(df_diag_split[cols_proc_top15].iloc[fila])

Diagnósticos top 10 fila 0:
Diag 01 Principal (cod+des)_cod     A41.8
Diag 02 Secundario (cod+des)_cod    B37.6
Diag 03 Secundario (cod+des)_cod    I39.8
Diag 04 Secundario (cod+des)_cod      N10
Diag 05 Secundario (cod+des)_cod    B96.1
Diag 06 Secundario (cod+des)_cod    L89.9
Diag 07 Secundario (cod+des)_cod    L08.9
Diag 08 Secundario (cod+des)_cod    B96.2
Diag 09 Secundario (cod+des)_cod    A41.5
Diag 10 Secundario (cod+des)_cod    J86.9
Name: 0, dtype: object

Procedimientos top 15 fila 0:
Proced 01 Principal (cod+des)_cod     86.28
Proced 02 Secundario (cod+des)_cod    34.91
Proced 03 Secundario (cod+des)_cod    88.38
Proced 04 Secundario (cod+des)_cod    87.41
Proced 05 Secundario (cod+des)_cod    88.75
Proced 06 Secundario (cod+des)_cod    88.01
Proced 07 Secundario (cod+des)_cod    88.43
Proced 08 Secundario (cod+des)_cod    88.41
Proced 09 Secundario (cod+des)_cod    87.44
Proced 10 Secundario (cod+des)_cod    99.29
Proced 11 Secundario (cod+des)_cod    99.19
Proced 12 Secundario (cod+des)_cod    99.18
Proced 13 Secundario (cod+des)_cod    99.21
Proced 14 Secundario (cod+des)_cod    99.26
Proced 15 Secundario (cod+des)_cod    99.23
Name: 0, dtype: object

In [170]:
df_model["edad"] = df_diag_split["Edad en años"]

In [169]:
df_model["sexo"] = df_diag_split["Sexo (Desc)"]

In [172]:
df_model["edad_grupo"] = pd.cut(
    df_model["edad"],
    bins=[-1, 18, 40, 65, 150],
    labels=["niño", "adulto_joven", "adulto", "adulto_mayor"]
)

In [171]:
df_model["sexo"] = (
    df_model["sexo"]
    .astype(str)
    .str.strip()
    .str.upper()
)

In [173]:
df_model["sexo_bin"] = df_model["sexo"].map({
    "HOMBRE": 1,
    "MUJER": 0
})

In [174]:
df_model["sexo"].value_counts()

sexo
MUJER     9617
HOMBRE    4944
Name: count, dtype: int64

In [175]:
df_model[["edad", "sexo"]].head()

   edad    sexo
0    40  HOMBRE
1    53  HOMBRE
2    65  HOMBRE
3    61  HOMBRE
4    30  HOMBRE

In [176]:
df_model[["edad"]].describe()

               edad
count  14561.000000
mean      39.426550
std       24.681545
min        0.000000
25%       23.000000
50%       36.000000
75%       60.000000
max      121.000000

In [177]:
df_model.isna().sum()

n_diag            0
n_proc            0
diag_principal    0
proc_principal    0
has_proc          0
multi_diag        0
edad              0
sexo              0
sexo_bin          0
edad_grupo        0
dtype: int64

In [178]:
y = df_diag_split["GRD"].copy()

In [179]:
print(y.shape)
print(df_model.shape)

(14561,)
(14561, 10)

In [180]:
y.isna().sum()

np.int64(0)

In [181]:
y.head(10)

0                         184103 - MH SEPTICEMIA W/MCC
1    041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
2    041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
3    041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...
4    041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...
5    041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
6    041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
7    041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
8    041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...
9    041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...
Name: GRD, dtype: object

In [182]:
y.nunique()

526

In [183]:
X = df_model.copy()

In [184]:
X.dtypes

n_diag               int64
n_proc               int64
diag_principal      object
proc_principal      object
has_proc             int64
multi_diag           int64
edad                 int64
sexo                object
sexo_bin             int64
edad_grupo        category
dtype: object

In [185]:
X.dtypes

n_diag               int64
n_proc               int64
diag_principal      object
proc_principal      object
has_proc             int64
multi_diag           int64
edad                 int64
sexo                object
sexo_bin             int64
edad_grupo        category
dtype: object

In [186]:
X.head()

,n_diag,n_proc,diag_principal,proc_principal,has_proc,multi_diag,edad,sexo,sexo_bin,edad_grupo
0,10,15,A41.8,86.28,1,1,40,HOMBRE,1,adulto_joven
1,10,15,U07.1,31.1,1,1,53,HOMBRE,1,adulto
2,10,15,K56.5,86.22,1,1,65,HOMBRE,1,adulto
3,10,15,K76.8,54.19,1,1,61,HOMBRE,1,adulto
4,10,15,T81.0,54.11,1,1,30,HOMBRE,1,adulto_joven

In [187]:
X = X.drop(columns=["sexo"])

In [188]:
X.head()

,n_diag,n_proc,diag_principal,proc_principal,has_proc,multi_diag,edad,sexo_bin,edad_grupo
0,10,15,A41.8,86.28,1,1,40,1,adulto_joven
1,10,15,U07.1,31.1,1,1,53,1,adulto
2,10,15,K56.5,86.22,1,1,65,1,adulto
3,10,15,K76.8,54.19,1,1,61,1,adulto
4,10,15,T81.0,54.11,1,1,30,1,adulto_joven

In [189]:
# Partimos desde df_model ya construido
X = df_model.copy()

# Eliminamos sexo porque ya está representado en sexo_bin
if "sexo" in X.columns:
    X = X.drop(columns=["sexo"])

# Target
y = df_diag_split["GRD"].copy()

In [190]:
# Numéricas / binarias
cols_numericas = [
    "n_diag",
    "n_proc",
    "has_proc",
    "multi_diag",
    "edad",
    "sexo_bin"
]

# Categóricas
cols_categoricas = [
    "diag_principal",
    "proc_principal",
    "edad_grupo"
]

In [191]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(
                handle_unknown="infrequent_if_exist",
                min_frequency=20,   # agrupa categorías raras
                sparse_output=False
            ),
            cols_categoricas
        ),
        (
            "num",
            "passthrough",
            cols_numericas
        )
    ]
)

In [192]:
X_encoded = preprocessor.fit_transform(X)

In [193]:
# nombres de columnas categóricas transformadas
cat_feature_names = preprocessor.named_transformers_["cat"].get_feature_names_out(cols_categoricas)

# nombres finales
feature_names = list(cat_feature_names) + cols_numericas

In [194]:
import pandas as pd

X_encoded_df = pd.DataFrame(
    X_encoded,
    columns=feature_names,
    index=X.index
)

In [195]:
print("Shape original X:", X.shape)
print("Shape encoded X:", X_encoded_df.shape)

print("\nPrimeras columnas:")
print(X_encoded_df.head())

print("\nNulos en X_encoded_df:")
print(X_encoded_df.isna().sum().sum())

Shape original X: (14561, 9)
Shape encoded X: (14561, 257)

Primeras columnas:
   diag_principal_A08.0  diag_principal_A09.0  diag_principal_A09.9  \
0                   0.0                   0.0                   0.0
1                   0.0                   0.0                   0.0
2                   0.0                   0.0                   0.0
3                   0.0                   0.0                   0.0
4                   0.0                   0.0                   0.0

   diag_principal_A41.8  diag_principal_A41.9  diag_principal_C16.9  \
0                   1.0                   0.0                   0.0
1                   0.0                   0.0                   0.0
2                   0.0                   0.0                   0.0
3                   0.0                   0.0                   0.0
4                   0.0                   0.0                   0.0

   diag_principal_C50.9  diag_principal_C64  diag_principal_D25.9  \
0                   0.0                 0.0                   0.0
1                   0.0                 0.0                   0.0
2                   0.0                 0.0                   0.0
3                   0.0                 0.0                   0.0
4                   0.0                 0.0                   0.0

   diag_principal_D39.1  ...  edad_grupo_adulto  edad_grupo_adulto_joven  \
0                   0.0  ...                0.0                      1.0
1                   0.0  ...                1.0                      0.0
2                   0.0  ...                1.0                      0.0
3                   0.0  ...                1.0                      0.0
4                   0.0  ...                0.0                      1.0

   edad_grupo_adulto_mayor  edad_grupo_niño  n_diag  n_proc  has_proc  \
0                      0.0              0.0    10.0    15.0       1.0
1                      0.0              0.0    10.0    15.0       1.0
2                      0.0              0.0    10.0    15.0       1.0
3                      0.0              0.0    10.0    15.0       1.0
4                      0.0              0.0    10.0    15.0       1.0

   multi_diag  edad  sexo_bin
0         1.0  40.0       1.0
1         1.0  53.0       1.0
2         1.0  65.0       1.0
3         1.0  61.0       1.0
4         1.0  30.0       1.0

[5 rows x 257 columns]

Nulos en X_encoded_df:
0

In [196]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# =========================
# 1. Base final para modelar
# =========================
X = df_model.copy()

if "sexo" in X.columns:
    X = X.drop(columns=["sexo"])

y = df_diag_split["GRD"].copy()

# =========================
# 2. Definir columnas
# =========================
cols_numericas = [
    "n_diag",
    "n_proc",
    "has_proc",
    "multi_diag",
    "edad",
    "sexo_bin"
]

cols_categoricas = [
    "diag_principal",
    "proc_principal",
    "edad_grupo"
]

# =========================
# 3. Preprocesador
# =========================
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(
                handle_unknown="infrequent_if_exist",
                min_frequency=20,
                sparse_output=False
            ),
            cols_categoricas
        ),
        (
            "num",
            "passthrough",
            cols_numericas
        )
    ]
)

# =========================
# 4. Fit + transform
# =========================
X_encoded = preprocessor.fit_transform(X)

# =========================
# 5. Nombres de columnas
# =========================
cat_feature_names = preprocessor.named_transformers_["cat"].get_feature_names_out(cols_categoricas)
feature_names = list(cat_feature_names) + cols_numericas

# =========================
# 6. DataFrame final
# =========================
X_encoded_df = pd.DataFrame(
    X_encoded,
    columns=feature_names,
    index=X.index
)

X_final = X_encoded_df
y_final = y

# =========================
# 7. Validaciones
# =========================
print("Shape original X:", X.shape)
print("Shape encoded X:", X_final.shape)
print("Nulos en X_final:", X_final.isna().sum().sum())

print("\nPrimeras filas:")
print(X_final.head())

Shape original X: (14561, 9)
Shape encoded X: (14561, 257)
Nulos en X_final: 0

Primeras filas:
   diag_principal_A08.0  diag_principal_A09.0  diag_principal_A09.9  \
0                   0.0                   0.0                   0.0
1                   0.0                   0.0                   0.0
2                   0.0                   0.0                   0.0
3                   0.0                   0.0                   0.0
4                   0.0                   0.0                   0.0

   diag_principal_A41.8  diag_principal_A41.9  diag_principal_C16.9  \
0                   1.0                   0.0                   0.0
1                   0.0                   0.0                   0.0
2                   0.0                   0.0                   0.0
3                   0.0                   0.0                   0.0
4                   0.0                   0.0                   0.0

   diag_principal_C50.9  diag_principal_C64  diag_principal_D25.9  \
0                   0.0                 0.0                   0.0
1                   0.0                 0.0                   0.0
2                   0.0                 0.0                   0.0
3                   0.0                 0.0                   0.0
4                   0.0                 0.0                   0.0

   diag_principal_D39.1  ...  edad_grupo_adulto  edad_grupo_adulto_joven  \
0                   0.0  ...                0.0                      1.0
1                   0.0  ...                1.0                      0.0
2                   0.0  ...                1.0                      0.0
3                   0.0  ...                1.0                      0.0
4                   0.0  ...                0.0                      1.0

   edad_grupo_adulto_mayor  edad_grupo_niño  n_diag  n_proc  has_proc  \
0                      0.0              0.0    10.0    15.0       1.0
1                      0.0              0.0    10.0    15.0       1.0
2                      0.0              0.0    10.0    15.0       1.0
3                      0.0              0.0    10.0    15.0       1.0
4                      0.0              0.0    10.0    15.0       1.0

   multi_diag  edad  sexo_bin
0         1.0  40.0       1.0
1         1.0  53.0       1.0
2         1.0  65.0       1.0
3         1.0  61.0       1.0
4         1.0  30.0       1.0

[5 rows x 257 columns]

In [204]:
y_grouped = y_final.astype(str).str[:3]

In [206]:
print("Clases originales:", y_final.nunique())
print("Clases agrupadas:", y_grouped.nunique())

Clases originales: 526
Clases agrupadas: 37

In [212]:
conteo_grouped = y_grouped.value_counts()

print("Clases agrupadas totales:", y_grouped.nunique())
print("Clases con 1 caso:", (conteo_grouped == 1).sum())
print("Clases con menos de 2 casos:", (conteo_grouped < 2).sum())
print("Clases con menos de 5 casos:", (conteo_grouped < 5).sum())

Clases agrupadas totales: 37
Clases con 1 caso: 1
Clases con menos de 2 casos: 1
Clases con menos de 5 casos: 3

In [213]:
clases_validas = conteo_grouped[conteo_grouped >= 2].index

mask = y_grouped.isin(clases_validas)

X_grouped = X_final[mask].copy()
y_grouped_filtrado = y_grouped[mask].copy()

print("Shape original:", X_final.shape, y_grouped.shape)
print("Shape filtrado:", X_grouped.shape, y_grouped_filtrado.shape)
print("Nuevas clases:", y_grouped_filtrado.nunique())

Shape original: (14561, 257) (14561,)
Shape filtrado: (14560, 257) (14560,)
Nuevas clases: 36

In [214]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_grouped,
    y_grouped_filtrado,
    test_size=0.2,
    random_state=42,
    stratify=y_grouped_filtrado
)

In [215]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy agrupado filtrado:", accuracy_score(y_test, y_pred))

Accuracy agrupado filtrado: 0.7908653846153846

In [216]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         014       0.72      0.80      0.76       114
         021       0.00      0.00      0.00         1
         024       0.00      0.00      0.00         5
         031       0.00      0.00      0.00         2
         034       0.40      0.13      0.20        15
         041       0.76      0.78      0.77       103
         044       0.84      0.89      0.86       307
         051       0.50      0.15      0.24        13
         054       0.75      0.73      0.74       170
         061       0.72      0.81      0.77       200
         064       0.64      0.66      0.65       134
         071       0.87      0.90      0.89       112
         074       0.70      0.63      0.66        87
         081       0.78      0.86      0.82        44
         084       0.25      0.15      0.19        13
         091       0.63      0.68      0.66        59
         094       0.67      0.60      0.63        65
         104       0.61      0.33      0.42        43
         111       0.75      0.60      0.67        35
         114       0.87      0.89      0.88       122
         121       0.60      0.64      0.62        14
         124       0.80      0.44      0.57         9
         131       0.82      0.82      0.82       160
         134       0.75      0.83      0.79       139
         146       0.98      1.00      0.99       587
         158       0.84      0.90      0.87       151
         161       0.40      0.33      0.36         6
         164       0.38      0.24      0.29        21
         174       0.00      0.00      0.00         3
         184       0.45      0.35      0.39        26
         194       0.55      0.59      0.57        64
         201       0.00      0.00      0.00         1
         204       0.00      0.00      0.00         6
         214       0.45      0.36      0.40        58
         224       0.29      0.17      0.22        23

    accuracy                           0.79      2912
   macro avg       0.54      0.49      0.51      2912
weighted avg       0.78      0.79      0.78      2912

c:\Users\inait\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\inait\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\inait\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [217]:
from sklearn.metrics import precision_score, recall_score, f1_score

print("Precision (macro):", precision_score(y_test, y_pred, average="macro"))
print("Recall (macro):", recall_score(y_test, y_pred, average="macro"))
print("F1 (macro):", f1_score(y_test, y_pred, average="macro"))

print("\nPrecision (weighted):", precision_score(y_test, y_pred, average="weighted"))
print("Recall (weighted):", recall_score(y_test, y_pred, average="weighted"))
print("F1 (weighted):", f1_score(y_test, y_pred, average="weighted"))

Precision (macro): 0.5363083193186841
Recall (macro): 0.49375169444064365
F1 (macro): 0.5054645645641013

Precision (weighted): 0.7790516443841285
Recall (weighted): 0.7908653846153846
F1 (weighted): 0.7821504197975441

c:\Users\inait\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\inait\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [218]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\inait\appdata\local\programs\python\python314\lib\site-packages (from xgboost) (2.3.4)
Requirement already satisfied: scipy in c:\users\inait\appdata\local\programs\python\python314\lib\site-packages (from xgboost) (1.16.3)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   --- ------------------------------------ 9.4/101.7 MB 47.9 MB/s eta 0:00:02
   -------- ------------------------------- 21.0/101.7 MB 52.9 MB/s eta 0:00:02
   ----------- ---------------------------- 30.4/101.7 MB 50.3 MB/s eta 0:00:02
   --------------- ------------------------ 39.3/101.7 MB 48.0 MB/s eta 0:00:02
   ------------------------ --------------- 61.3/101.7 MB 60.1 MB/s eta 0:00:01
   ----------------------------- ---------- 75.5/101.7 MB 63.0 MB/s eta 0:00:01
   ----------------------------- ---------- 76.0/101.7 MB 53.8 MB/s eta 0:00:01
   -------------------------------- ------- 82.3/101.7 MB 50.6 MB/s eta 0:00:01
   ------------------------------------ --- 93.6/101.7 MB 51.1 MB/s eta 0:00:01
   --------------------------------------  101.4/101.7 MB 52.0 MB/s eta 0:00:01
   --------------------------------------  101.4/101.7 MB 52.0 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 43.4 MB/s  0:00:02
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [220]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y_train_enc = le.fit_transform(y_train)
y_test_enc = le.transform(y_test)

In [221]:
from xgboost import XGBClassifier

model_xgb = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
    eval_metric="mlogloss"
)

model_xgb.fit(X_train, y_train_enc)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=-1,
              num_parallel_tree=None, ...)

In [222]:
y_pred_enc = model_xgb.predict(X_test)

In [223]:
y_pred = le.inverse_transform(y_pred_enc)

In [225]:
from sklearn.metrics import precision_score, recall_score, f1_score

print("Precision (macro):", precision_score(y_test, y_pred, average="macro"))
print("Recall (macro):", recall_score(y_test, y_pred, average="macro"))
print("F1 (macro):", f1_score(y_test, y_pred, average="macro"))

print("\nPrecision (weighted):", precision_score(y_test, y_pred, average="weighted"))
print("Recall (weighted):", recall_score(y_test, y_pred, average="weighted"))
print("F1 (weighted):", f1_score(y_test, y_pred, average="weighted"))
print("Accuracy agrupado filtrado:", accuracy_score(y_test, y_pred))

Precision (macro): 0.5822778672056004
Recall (macro): 0.5299703251903081
F1 (macro): 0.5467844654211557

Precision (weighted): 0.8228493889885508
Recall (weighted): 0.8324175824175825
F1 (weighted): 0.8242974778246752
Accuracy agrupado filtrado: 0.8324175824175825

c:\Users\inait\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\inait\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])