In [ ]:
import pandas as pd


df = pd.read_csv('../data/processed/elpino_categories.csv')
df_encodeado = df.copy()

col_diag = [c for c in df.columns if 'Diag' in c and "(cod+des)"in c]
col_proc= [c for c in df.columns if 'Proced' in c and "(cod+des)"in c]
df_encodeado

,Diag 01 Principal (cod+des),Diag 02 Secundario (cod+des),Diag 03 Secundario (cod+des),Diag 04 Secundario (cod+des),Diag 05 Secundario (cod+des),Diag 06 Secundario (cod+des),Diag 07 Secundario (cod+des),Diag 08 Secundario (cod+des),Diag 09 Secundario (cod+des),Diag 10 Secundario (cod+des),...,Proced 24 Secundario (cod+des),Proced 25 Secundario (cod+des),Proced 26 Secundario (cod+des),Proced 27 Secundario (cod+des),Proced 28 Secundario (cod+des),Proced 29 Secundario (cod+des),Proced 30 Secundario (cod+des),Edad en años,Sexo (Desc),GRD
0,A41,B37,I39,N10,B96,L89,L08,B96,A41,J86,...,99,88,90,90,91,91,87,40,1,184103 - MH SEPTICEMIA W/MCC
1,U07,J12,R06,R05,R50,Z29,Z01,J96,J94,J92,...,91,90,91,90,91,96,90,53,1,041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
2,K56,R57,R57,J80,Y95,J15,U82,B95,B96,B37,...,99,91,90,99,89,89,89,65,1,041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
3,K76,K66,N18,D64,E87,E87,J81,N17,J44,R41,...,57,00,00,99,99,99,99,61,1,041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...
4,T81,Y83,S31,S36,W31,J96,J15,U82,U07,N39,...,90,91,91,93,99,96,45,30,1,041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14556,E10,J45,F10,F17,Z91,-,-,-,-,-,...,-,-,-,-,-,-,-,26,0,104101 - MH DIABETES Y ENFERMEDADES METABÓLICA...
14557,S09,W18,R55,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,10,1,014242 - MH TRAUMATISMO CEFÁLICO W/CC
14558,K92,I10,E11,I50,K25,M16,G47,Z99,-,-,...,-,-,-,-,-,-,-,58,1,064182 - MH OTROS DIAGNÓSTICOS SOBRE APARATO D...
14559,E78,I10,Z92,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,47,1,104121 - MH ERRORES CONGÉNITOS DE METABOLISMO
14560,S06,S06,W18,J69,D29,Z59,Z02,-,-,-,...,89,89,90,90,90,90,90,73,1,041203 - PH PROCEDIMIENTOS NO COMPLEJOS SOBRE ...

In [3]:
cols_diag = [c for c in df.columns if "Diag" in c]

df_encodeado["diagnosticos"] = df[cols_diag].values.tolist()
df_encodeado

,Diag 01 Principal (cod+des),Diag 02 Secundario (cod+des),Diag 03 Secundario (cod+des),Diag 04 Secundario (cod+des),Diag 05 Secundario (cod+des),Diag 06 Secundario (cod+des),Diag 07 Secundario (cod+des),Diag 08 Secundario (cod+des),Diag 09 Secundario (cod+des),Diag 10 Secundario (cod+des),...,Proced 25 Secundario (cod+des),Proced 26 Secundario (cod+des),Proced 27 Secundario (cod+des),Proced 28 Secundario (cod+des),Proced 29 Secundario (cod+des),Proced 30 Secundario (cod+des),Edad en años,Sexo (Desc),GRD,diagnosticos
0,A41,B37,I39,N10,B96,L89,L08,B96,A41,J86,...,88,90,90,91,91,87,40,1,184103 - MH SEPTICEMIA W/MCC,"[A41, B37, I39, N10, B96, L89, L08, B96, A41, ..."
1,U07,J12,R06,R05,R50,Z29,Z01,J96,J94,J92,...,90,91,90,91,96,90,53,1,041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...,"[U07, J12, R06, R05, R50, Z29, Z01, J96, J94, ..."
2,K56,R57,R57,J80,Y95,J15,U82,B95,B96,B37,...,91,90,99,89,89,89,65,1,041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...,"[K56, R57, R57, J80, Y95, J15, U82, B95, B96, ..."
3,K76,K66,N18,D64,E87,E87,J81,N17,J44,R41,...,00,00,99,99,99,99,61,1,041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...,"[K76, K66, N18, D64, E87, E87, J81, N17, J44, ..."
4,T81,Y83,S31,S36,W31,J96,J15,U82,U07,N39,...,91,91,93,99,96,45,30,1,041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...,"[T81, Y83, S31, S36, W31, J96, J15, U82, U07, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14556,E10,J45,F10,F17,Z91,-,-,-,-,-,...,-,-,-,-,-,-,26,0,104101 - MH DIABETES Y ENFERMEDADES METABÓLICA...,"[E10, J45, F10, F17, Z91, -, -, -, -, -, -, -,..."
14557,S09,W18,R55,-,-,-,-,-,-,-,...,-,-,-,-,-,-,10,1,014242 - MH TRAUMATISMO CEFÁLICO W/CC,"[S09, W18, R55, -, -, -, -, -, -, -, -, -, -, ..."
14558,K92,I10,E11,I50,K25,M16,G47,Z99,-,-,...,-,-,-,-,-,-,58,1,064182 - MH OTROS DIAGNÓSTICOS SOBRE APARATO D...,"[K92, I10, E11, I50, K25, M16, G47, Z99, -, -,..."
14559,E78,I10,Z92,-,-,-,-,-,-,-,...,-,-,-,-,-,-,47,1,104121 - MH ERRORES CONGÉNITOS DE METABOLISMO,"[E78, I10, Z92, -, -, -, -, -, -, -, -, -, -, ..."
14560,S06,S06,W18,J69,D29,Z59,Z02,-,-,-,...,89,90,90,90,90,90,73,1,041203 - PH PROCEDIMIENTOS NO COMPLEJOS SOBRE ...,"[S06, S06, W18, J69, D29, Z59, Z02, -, -, -, -..."

In [6]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense

# Convertir códigos a índices
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()


X_diag = mlb.fit_transform(df_encodeado["diagnosticos"])
X_diag
df_encodeado

NameError: name 'mlb' is not defined

In [11]:
df

col_grd = [c for c in df.columns if 'GRD' in c]
col_grd
for col in col_grd:
    df[col] = (
        df[col].str.split(" - ").str[0]
    )
df.to_csv('../data/processed/elpino_categories.csv', index=False)